// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/metadata/v1/types.proto

// Package pluggableharness.metadata.v1 defines the typed metadata-block
// vocabulary plugins publish and frontends render — the "Metadata" surface
// of the four frontend state surfaces (input, state, metadata, transcript)
// described in specifications/frontend/. A block never carries a color, a
// width, or a position: Tone is a closed token scale the frontend maps to
// whatever it has (including a screen reader saying "warning"), and the
// closed oneof body is the only set of kinds every conforming frontend is
// required to render.

package metadatav1

import (
	v1 "github.com/pluggableharness/agent/pkg/common/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tone is a closed token scale for a MetadataBlock's presentation intent.
// Frontends map each token to their own vocabulary (ANSI color, CSS class,
// spoken label); a block never names a color value.
type Tone int32

const (
	// Zero value. Never valid for a real block; its presence means a caller
	// forgot to set the field.
	Tone_TONE_UNSPECIFIED Tone = 0
	// Ordinary, unemphasized content.
	Tone_TONE_NEUTRAL Tone = 1
	// Informational emphasis without implying success or failure.
	Tone_TONE_INFO Tone = 2
	// A successful or healthy condition.
	Tone_TONE_SUCCESS Tone = 3
	// A cautionary condition that is not yet a failure.
	Tone_TONE_WARNING Tone = 4
	// A failure or high-severity condition.
	Tone_TONE_DANGER Tone = 5
)

// Enum value maps for Tone.
var (
	Tone_name = map[int32]string{
		0: "TONE_UNSPECIFIED",
		1: "TONE_NEUTRAL",
		2: "TONE_INFO",
		3: "TONE_SUCCESS",
		4: "TONE_WARNING",
		5: "TONE_DANGER",
	}
	Tone_value = map[string]int32{
		"TONE_UNSPECIFIED": 0,
		"TONE_NEUTRAL":     1,
		"TONE_INFO":        2,
		"TONE_SUCCESS":     3,
		"TONE_WARNING":     4,
		"TONE_DANGER":      5,
	}
)

func (x Tone) Enum() *Tone {
	p := new(Tone)
	*p = x
	return p
}

func (x Tone) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tone) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_metadata_v1_types_proto_enumTypes[0].Descriptor()
}

func (Tone) Type() protoreflect.EnumType {
	return &file_pluggableharness_metadata_v1_types_proto_enumTypes[0]
}

func (x Tone) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tone.Descriptor instead.
func (Tone) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_metadata_v1_types_proto_rawDescGZIP(), []int{0}
}

// Liveness reports whether the producing plugin is still connected.
// The kernel never deletes a block: on publisher exit or RetractMetadata
// it flips liveness to DISCONNECTED and republishes; the frontend decides
// whether that means gray, drop, or "plugin gone."
type Liveness int32

const (
	// Zero value. Never valid for a real block.
	Liveness_LIVENESS_UNSPECIFIED Liveness = 0
	// The producing plugin is still live and owns this block.
	Liveness_LIVENESS_LIVE Liveness = 1
	// The producing plugin has exited or explicitly retracted the block.
	Liveness_LIVENESS_DISCONNECTED Liveness = 2
)

// Enum value maps for Liveness.
var (
	Liveness_name = map[int32]string{
		0: "LIVENESS_UNSPECIFIED",
		1: "LIVENESS_LIVE",
		2: "LIVENESS_DISCONNECTED",
	}
	Liveness_value = map[string]int32{
		"LIVENESS_UNSPECIFIED":  0,
		"LIVENESS_LIVE":         1,
		"LIVENESS_DISCONNECTED": 2,
	}
)

func (x Liveness) Enum() *Liveness {
	p := new(Liveness)
	*p = x
	return p
}

func (x Liveness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Liveness) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_metadata_v1_types_proto_enumTypes[1].Descriptor()
}

func (Liveness) Type() protoreflect.EnumType {
	return &file_pluggableharness_metadata_v1_types_proto_enumTypes[1]
}

func (x Liveness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Liveness.Descriptor instead.
func (Liveness) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_metadata_v1_types_proto_rawDescGZIP(), []int{1}
}

// MetadataBlock is one keyed, typed contribution to a session's metadata
// surface. Identified by id within a session; upserted by PublishMetadata
// and never deleted by the kernel.
type MetadataBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable id within the session. The publishing plugin chooses it; a
	// second PublishMetadata with the same id upserts.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The plugin that currently owns this block. Server-derived from the
	// authenticated callback connection on PublishMetadata — a client MUST
	// NOT supply this; the kernel overwrites any client-set value.
	Producer *v1.ProducerRef `protobuf:"bytes,2,opt,name=producer,proto3" json:"producer,omitempty"`
	// Ordering/eviction hint for space-constrained frontends. Higher wins.
	// Unset (zero) means declaration order among equal-priority peers.
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Presentation intent token. MUST be set to a non-UNSPECIFIED value.
	Tone Tone `protobuf:"varint,4,opt,name=tone,proto3,enum=pluggableharness.metadata.v1.Tone" json:"tone,omitempty"`
	// Whether the producer is still connected. MUST be set.
	Liveness Liveness `protobuf:"varint,5,opt,name=liveness,proto3,enum=pluggableharness.metadata.v1.Liveness" json:"liveness,omitempty"`
	// The session this block belongs to. MUST be set. Carried on the block
	// (rather than only on the publish request) so a bus subscriber can
	// filter without a second lookup.
	SessionId string `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Exactly one body variant is set. The set is closed on purpose: five
	// kinds surface missing shapes faster than an open type would, and a
	// closed set is what guarantees every frontend can render every block.
	//
	// Types that are valid to be assigned to Body:
	//
	//	*MetadataBlock_KeyValue
	//	*MetadataBlock_Progress
	//	*MetadataBlock_Status
	//	*MetadataBlock_ItemList
	//	*MetadataBlock_Timer
	Body          isMetadataBlock_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataBlock) Reset() {
	*x = MetadataBlock{}
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataBlock) ProtoMessage() {}

func (x *MetadataBlock) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataBlock.ProtoReflect.Descriptor instead.
func (*MetadataBlock) Descriptor() ([]byte, []int) {
	return file_pluggableharness_metadata_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetadataBlock) GetProducer() *v1.ProducerRef {
	if x != nil {
		return x.Producer
	}
	return nil
}

func (x *MetadataBlock) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MetadataBlock) GetTone() Tone {
	if x != nil {
		return x.Tone
	}
	return Tone_TONE_UNSPECIFIED
}

func (x *MetadataBlock) GetLiveness() Liveness {
	if x != nil {
		return x.Liveness
	}
	return Liveness_LIVENESS_UNSPECIFIED
}

func (x *MetadataBlock) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MetadataBlock) GetBody() isMetadataBlock_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *MetadataBlock) GetKeyValue() *KeyValue {
	if x != nil {
		if x, ok := x.Body.(*MetadataBlock_KeyValue); ok {
			return x.KeyValue
		}
	}
	return nil
}

func (x *MetadataBlock) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Body.(*MetadataBlock_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *MetadataBlock) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Body.(*MetadataBlock_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *MetadataBlock) GetItemList() *ItemList {
	if x != nil {
		if x, ok := x.Body.(*MetadataBlock_ItemList); ok {
			return x.ItemList
		}
	}
	return nil
}

func (x *MetadataBlock) GetTimer() *Timer {
	if x != nil {
		if x, ok := x.Body.(*MetadataBlock_Timer); ok {
			return x.Timer
		}
	}
	return nil
}

type isMetadataBlock_Body interface {
	isMetadataBlock_Body()
}

type MetadataBlock_KeyValue struct {
	KeyValue *KeyValue `protobuf:"bytes,10,opt,name=key_value,json=keyValue,proto3,oneof"`
}

type MetadataBlock_Progress struct {
	Progress *Progress `protobuf:"bytes,11,opt,name=progress,proto3,oneof"`
}

type MetadataBlock_Status struct {
	Status *Status `protobuf:"bytes,12,opt,name=status,proto3,oneof"`
}

type MetadataBlock_ItemList struct {
	ItemList *ItemList `protobuf:"bytes,13,opt,name=item_list,json=itemList,proto3,oneof"`
}

type MetadataBlock_Timer struct {
	Timer *Timer `protobuf:"bytes,14,opt,name=timer,proto3,oneof"`
}

func (*MetadataBlock_KeyValue) isMetadataBlock_Body() {}

func (*MetadataBlock_Progress) isMetadataBlock_Body() {}

func (*MetadataBlock_Status) isMetadataBlock_Body() {}

func (*MetadataBlock_ItemList) isMetadataBlock_Body() {}

func (*MetadataBlock_Timer) isMetadataBlock_Body() {}

// KeyValue is a short labeled value, e.g. "branch: main".
type KeyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The field label shown to the operator.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The field value shown to the operator.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_pluggableharness_metadata_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Progress is a determinate or indeterminate progress indicator.
type Progress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short label describing what is in progress.
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// Completed units. Meaningful when total is set and > 0.
	Completed int64 `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	// Total units. Absent or zero means indeterminate progress.
	Total         *int64 `protobuf:"varint,3,opt,name=total,proto3,oneof" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_pluggableharness_metadata_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Progress) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Progress) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *Progress) GetTotal() int64 {
	if x != nil && x.Total != nil {
		return *x.Total
	}
	return 0
}

// Status is a single status line with an optional detail.
type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The primary status text.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// Optional secondary detail.
	Detail        *string `protobuf:"bytes,2,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_pluggableharness_metadata_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Status) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Status) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

// ItemList is an ordered list of short text items.
type ItemList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional list title.
	Title *string `protobuf:"bytes,1,opt,name=title,proto3,oneof" json:"title,omitempty"`
	// The items, in display order.
	Items         []string `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemList) Reset() {
	*x = ItemList{}
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemList) ProtoMessage() {}

func (x *ItemList) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemList.ProtoReflect.Descriptor instead.
func (*ItemList) Descriptor() ([]byte, []int) {
	return file_pluggableharness_metadata_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *ItemList) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *ItemList) GetItems() []string {
	if x != nil {
		return x.Items
	}
	return nil
}

// Timer is a wall-clock duration or deadline the frontend can render as
// a ticking clock or countdown.
type Timer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional label for what the timer measures.
	Label *string `protobuf:"bytes,1,opt,name=label,proto3,oneof" json:"label,omitempty"`
	// When the timed interval started. MUST be set for elapsed display.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Optional absolute deadline; when set, frontends MAY render a
	// countdown instead of (or in addition to) elapsed time.
	Deadline *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deadline,proto3,oneof" json:"deadline,omitempty"`
	// Optional fixed duration the timer represents when no deadline is set.
	Duration      *durationpb.Duration `protobuf:"bytes,4,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timer) Reset() {
	*x = Timer{}
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timer) ProtoMessage() {}

func (x *Timer) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_metadata_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timer.ProtoReflect.Descriptor instead.
func (*Timer) Descriptor() ([]byte, []int) {
	return file_pluggableharness_metadata_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *Timer) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *Timer) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Timer) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Timer) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_pluggableharness_metadata_v1_types_proto protoreflect.FileDescriptor

const file_pluggableharness_metadata_v1_types_proto_rawDesc = "" +
	"\n" +
	"(pluggableharness/metadata/v1/types.proto\x12\x1cpluggableharness.metadata.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a&pluggableharness/common/v1/types.proto\"\xf4\x04\n" +
	"\rMetadataBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\bproducer\x18\x02 \x01(\v2'.pluggableharness.common.v1.ProducerRefR\bproducer\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x126\n" +
	"\x04tone\x18\x04 \x01(\x0e2\".pluggableharness.metadata.v1.ToneR\x04tone\x12B\n" +
	"\bliveness\x18\x05 \x01(\x0e2&.pluggableharness.metadata.v1.LivenessR\bliveness\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12E\n" +
	"\tkey_value\x18\n" +
	" \x01(\v2&.pluggableharness.metadata.v1.KeyValueH\x00R\bkeyValue\x12D\n" +
	"\bprogress\x18\v \x01(\v2&.pluggableharness.metadata.v1.ProgressH\x00R\bprogress\x12>\n" +
	"\x06status\x18\f \x01(\v2$.pluggableharness.metadata.v1.StatusH\x00R\x06status\x12E\n" +
	"\titem_list\x18\r \x01(\v2&.pluggableharness.metadata.v1.ItemListH\x00R\bitemList\x12;\n" +
	"\x05timer\x18\x0e \x01(\v2#.pluggableharness.metadata.v1.TimerH\x00R\x05timerB\x06\n" +
	"\x04body\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"c\n" +
	"\bProgress\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\x03R\tcompleted\x12\x19\n" +
	"\x05total\x18\x03 \x01(\x03H\x00R\x05total\x88\x01\x01B\b\n" +
	"\x06_total\"D\n" +
	"\x06Status\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1b\n" +
	"\x06detail\x18\x02 \x01(\tH\x00R\x06detail\x88\x01\x01B\t\n" +
	"\a_detail\"E\n" +
	"\bItemList\x12\x19\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x14\n" +
	"\x05items\x18\x02 \x03(\tR\x05itemsB\b\n" +
	"\x06_title\"\xfa\x01\n" +
	"\x05Timer\x12\x19\n" +
	"\x05label\x18\x01 \x01(\tH\x00R\x05label\x88\x01\x01\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\bdeadline\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdeadline\x88\x01\x01\x12:\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationH\x02R\bduration\x88\x01\x01B\b\n" +
	"\x06_labelB\v\n" +
	"\t_deadlineB\v\n" +
	"\t_duration*r\n" +
	"\x04Tone\x12\x14\n" +
	"\x10TONE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTONE_NEUTRAL\x10\x01\x12\r\n" +
	"\tTONE_INFO\x10\x02\x12\x10\n" +
	"\fTONE_SUCCESS\x10\x03\x12\x10\n" +
	"\fTONE_WARNING\x10\x04\x12\x0f\n" +
	"\vTONE_DANGER\x10\x05*R\n" +
	"\bLiveness\x12\x18\n" +
	"\x14LIVENESS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rLIVENESS_LIVE\x10\x01\x12\x19\n" +
	"\x15LIVENESS_DISCONNECTED\x10\x02BDZBgithub.com/pluggableharness/agent/pkg/metadata/proto/v1;metadatav1b\x06proto3"

var (
	file_pluggableharness_metadata_v1_types_proto_rawDescOnce sync.Once
	file_pluggableharness_metadata_v1_types_proto_rawDescData []byte
)

func file_pluggableharness_metadata_v1_types_proto_rawDescGZIP() []byte {
	file_pluggableharness_metadata_v1_types_proto_rawDescOnce.Do(func() {
		file_pluggableharness_metadata_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_metadata_v1_types_proto_rawDesc), len(file_pluggableharness_metadata_v1_types_proto_rawDesc)))
	})
	return file_pluggableharness_metadata_v1_types_proto_rawDescData
}

var file_pluggableharness_metadata_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pluggableharness_metadata_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pluggableharness_metadata_v1_types_proto_goTypes = []any{
	(Tone)(0),                     // 0: pluggableharness.metadata.v1.Tone
	(Liveness)(0),                 // 1: pluggableharness.metadata.v1.Liveness
	(*MetadataBlock)(nil),         // 2: pluggableharness.metadata.v1.MetadataBlock
	(*KeyValue)(nil),              // 3: pluggableharness.metadata.v1.KeyValue
	(*Progress)(nil),              // 4: pluggableharness.metadata.v1.Progress
	(*Status)(nil),                // 5: pluggableharness.metadata.v1.Status
	(*ItemList)(nil),              // 6: pluggableharness.metadata.v1.ItemList
	(*Timer)(nil),                 // 7: pluggableharness.metadata.v1.Timer
	(*v1.ProducerRef)(nil),        // 8: pluggableharness.common.v1.ProducerRef
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 10: google.protobuf.Duration
}
var file_pluggableharness_metadata_v1_types_proto_depIdxs = []int32{
	8,  // 0: pluggableharness.metadata.v1.MetadataBlock.producer:type_name -> pluggableharness.common.v1.ProducerRef
	0,  // 1: pluggableharness.metadata.v1.MetadataBlock.tone:type_name -> pluggableharness.metadata.v1.Tone
	1,  // 2: pluggableharness.metadata.v1.MetadataBlock.liveness:type_name -> pluggableharness.metadata.v1.Liveness
	3,  // 3: pluggableharness.metadata.v1.MetadataBlock.key_value:type_name -> pluggableharness.metadata.v1.KeyValue
	4,  // 4: pluggableharness.metadata.v1.MetadataBlock.progress:type_name -> pluggableharness.metadata.v1.Progress
	5,  // 5: pluggableharness.metadata.v1.MetadataBlock.status:type_name -> pluggableharness.metadata.v1.Status
	6,  // 6: pluggableharness.metadata.v1.MetadataBlock.item_list:type_name -> pluggableharness.metadata.v1.ItemList
	7,  // 7: pluggableharness.metadata.v1.MetadataBlock.timer:type_name -> pluggableharness.metadata.v1.Timer
	9,  // 8: pluggableharness.metadata.v1.Timer.started_at:type_name -> google.protobuf.Timestamp
	9,  // 9: pluggableharness.metadata.v1.Timer.deadline:type_name -> google.protobuf.Timestamp
	10, // 10: pluggableharness.metadata.v1.Timer.duration:type_name -> google.protobuf.Duration
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pluggableharness_metadata_v1_types_proto_init() }
func file_pluggableharness_metadata_v1_types_proto_init() {
	if File_pluggableharness_metadata_v1_types_proto != nil {
		return
	}
	file_pluggableharness_metadata_v1_types_proto_msgTypes[0].OneofWrappers = []any{
		(*MetadataBlock_KeyValue)(nil),
		(*MetadataBlock_Progress)(nil),
		(*MetadataBlock_Status)(nil),
		(*MetadataBlock_ItemList)(nil),
		(*MetadataBlock_Timer)(nil),
	}
	file_pluggableharness_metadata_v1_types_proto_msgTypes[2].OneofWrappers = []any{}
	file_pluggableharness_metadata_v1_types_proto_msgTypes[3].OneofWrappers = []any{}
	file_pluggableharness_metadata_v1_types_proto_msgTypes[4].OneofWrappers = []any{}
	file_pluggableharness_metadata_v1_types_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_metadata_v1_types_proto_rawDesc), len(file_pluggableharness_metadata_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_metadata_v1_types_proto_goTypes,
		DependencyIndexes: file_pluggableharness_metadata_v1_types_proto_depIdxs,
		EnumInfos:         file_pluggableharness_metadata_v1_types_proto_enumTypes,
		MessageInfos:      file_pluggableharness_metadata_v1_types_proto_msgTypes,
	}.Build()
	File_pluggableharness_metadata_v1_types_proto = out.File
	file_pluggableharness_metadata_v1_types_proto_goTypes = nil
	file_pluggableharness_metadata_v1_types_proto_depIdxs = nil
}
