// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/session/v1/types.proto

// Package pluggableharness.session.v1 defines the session lifecycle status
// enum shared by kernel-callbacks.md's RunSessionResult and
// state-backend.md's session_meta.status column, plus SessionInfo and the
// frontend-facing SessionState snapshot ("where am I") assembled by
// KernelCallbackService.GetSessionState.

package sessionv1

import (
	v1 "github.com/pluggableharness/agent/pkg/model/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionStatus is a session's lifecycle state. RUNNING is the only value
// a live (non-terminal) session can be in; every other value is terminal.
// agent-loop.md §7.1's RunSessionResult never carries RUNNING (a
// RunSession call only returns once its child session has reached a
// terminal state) — it reuses this same enum rather than defining a
// narrower terminal-only one, since the two are the same status space
// observed at different times.
type SessionStatus int32

const (
	// Zero value. Never valid on the wire; its presence means a caller
	// forgot to set the field.
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	// The session is still in progress.
	SessionStatus_SESSION_STATUS_RUNNING SessionStatus = 1
	// The session finished normally.
	SessionStatus_SESSION_STATUS_COMPLETED SessionStatus = 2
	// The session hit its configured max-turns bound (agent-loop.md §3.2).
	SessionStatus_SESSION_STATUS_ERROR_MAX_TURNS SessionStatus = 3
	// The session hit its configured max-cost-USD bound.
	SessionStatus_SESSION_STATUS_ERROR_MAX_BUDGET_USD SessionStatus = 4
	// The session hit its configured max-wall-clock bound.
	SessionStatus_SESSION_STATUS_ERROR_MAX_WALL_CLOCK SessionStatus = 5
	// The session was cancelled (user interrupt, parent cancellation
	// propagation per agent-loop.md §7.7).
	SessionStatus_SESSION_STATUS_CANCELLED SessionStatus = 6
	// The session ended due to an unrecoverable error.
	SessionStatus_SESSION_STATUS_FAILED SessionStatus = 7
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_RUNNING",
		2: "SESSION_STATUS_COMPLETED",
		3: "SESSION_STATUS_ERROR_MAX_TURNS",
		4: "SESSION_STATUS_ERROR_MAX_BUDGET_USD",
		5: "SESSION_STATUS_ERROR_MAX_WALL_CLOCK",
		6: "SESSION_STATUS_CANCELLED",
		7: "SESSION_STATUS_FAILED",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED":          0,
		"SESSION_STATUS_RUNNING":              1,
		"SESSION_STATUS_COMPLETED":            2,
		"SESSION_STATUS_ERROR_MAX_TURNS":      3,
		"SESSION_STATUS_ERROR_MAX_BUDGET_USD": 4,
		"SESSION_STATUS_ERROR_MAX_WALL_CLOCK": 5,
		"SESSION_STATUS_CANCELLED":            6,
		"SESSION_STATUS_FAILED":               7,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_session_v1_types_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_pluggableharness_session_v1_types_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_session_v1_types_proto_rawDescGZIP(), []int{0}
}

// SessionPhase is what a session is doing at this instant.
//
// Deliberately short. Every value here is one a frontend renders
// differently; a phase nothing displays differently is a log line, not
// protocol. Finer breakdowns (which tool, which turn step) are already
// available as events on the transcript.
type SessionPhase int32

const (
	// Zero value: the session has not reported a phase. A frontend SHOULD
	// treat this as IDLE rather than rendering an unknown state — a session
	// that never reports is not working.
	SessionPhase_SESSION_PHASE_UNSPECIFIED SessionPhase = 0
	// Nothing is in flight; the session is waiting on the operator.
	SessionPhase_SESSION_PHASE_IDLE SessionPhase = 1
	// A turn is in flight — the model is being called, or its tool calls
	// are running.
	SessionPhase_SESSION_PHASE_GENERATING SessionPhase = 2
)

// Enum value maps for SessionPhase.
var (
	SessionPhase_name = map[int32]string{
		0: "SESSION_PHASE_UNSPECIFIED",
		1: "SESSION_PHASE_IDLE",
		2: "SESSION_PHASE_GENERATING",
	}
	SessionPhase_value = map[string]int32{
		"SESSION_PHASE_UNSPECIFIED": 0,
		"SESSION_PHASE_IDLE":        1,
		"SESSION_PHASE_GENERATING":  2,
	}
)

func (x SessionPhase) Enum() *SessionPhase {
	p := new(SessionPhase)
	*p = x
	return p
}

func (x SessionPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_session_v1_types_proto_enumTypes[1].Descriptor()
}

func (SessionPhase) Type() protoreflect.EnumType {
	return &file_pluggableharness_session_v1_types_proto_enumTypes[1]
}

func (x SessionPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionPhase.Descriptor instead.
func (SessionPhase) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_session_v1_types_proto_rawDescGZIP(), []int{1}
}

// SessionInfo is a session's shareable summary, mirroring
// state-backend.md's session_meta row plus a cheap cost_ledger SUM. Used
// by session lifecycle RPCs (CreateSession/AttachSession/ListSessions)
// and embedded inside SessionState — the frontend protocol's read-only
// view of session lifecycle state, never mutated by a frontend directly.
type SessionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session's id. ULID, matches the session's sqlite filename stem
	// (state-backend.md §"File layout").
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// The parent session's id, when this is a sub-agent session
	// (agent-loop/subagents.md). Absent for a root session — mirrors
	// session_meta.parent_session_id.
	ParentSessionId *string `protobuf:"bytes,2,opt,name=parent_session_id,json=parentSessionId,proto3,oneof" json:"parent_session_id,omitempty"`
	// The agent.hcl profile this session was created under.
	Profile string `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	// The session's current lifecycle status.
	Status SessionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=pluggableharness.session.v1.SessionStatus" json:"status,omitempty"`
	// The session's depth in its ancestor chain — mirrors
	// session_meta.depth (agent-loop/subagents.md#depth-limits).
	Depth int32 `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	// When the session was created. Mirrors session_meta.started_at.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// When the session reached a terminal status. Absent while RUNNING.
	// Mirrors session_meta.ended_at.
	EndedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ended_at,json=endedAt,proto3,oneof" json:"ended_at,omitempty"`
	// The session's running total spend — SUM(cost_usd) over
	// state-backend.md's cost_ledger table for this session. Absent if no
	// cost has been incurred yet, rather than a meaningless zero.
	CostUsd       *float64 `protobuf:"fixed64,8,opt,name=cost_usd,json=costUsd,proto3,oneof" json:"cost_usd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_pluggableharness_session_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetParentSessionId() string {
	if x != nil && x.ParentSessionId != nil {
		return *x.ParentSessionId
	}
	return ""
}

func (x *SessionInfo) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *SessionInfo) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *SessionInfo) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *SessionInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SessionInfo) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *SessionInfo) GetCostUsd() float64 {
	if x != nil && x.CostUsd != nil {
		return *x.CostUsd
	}
	return 0
}

// VcsState is the session's version-control summary for status rendering.
// Absent fields mean "unknown / not a VCS working tree," not empty.
type VcsState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The remote tracking URL or name, when known.
	Remote *string `protobuf:"bytes,1,opt,name=remote,proto3,oneof" json:"remote,omitempty"`
	// The current branch or detached-HEAD ref name, when known.
	Branch *string `protobuf:"bytes,2,opt,name=branch,proto3,oneof" json:"branch,omitempty"`
	// True when the working tree has uncommitted changes. Absent when VCS
	// state could not be determined.
	Dirty         *bool `protobuf:"varint,3,opt,name=dirty,proto3,oneof" json:"dirty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VcsState) Reset() {
	*x = VcsState{}
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VcsState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VcsState) ProtoMessage() {}

func (x *VcsState) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VcsState.ProtoReflect.Descriptor instead.
func (*VcsState) Descriptor() ([]byte, []int) {
	return file_pluggableharness_session_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *VcsState) GetRemote() string {
	if x != nil && x.Remote != nil {
		return *x.Remote
	}
	return ""
}

func (x *VcsState) GetBranch() string {
	if x != nil && x.Branch != nil {
		return *x.Branch
	}
	return ""
}

func (x *VcsState) GetDirty() bool {
	if x != nil && x.Dirty != nil {
		return *x.Dirty
	}
	return false
}

// ModelState names the model currently driving the session.
type ModelState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The model's id within its provider (ModelSpec.id).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The declared name of the model provider plugin.
	Provider      string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelState) Reset() {
	*x = ModelState{}
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelState) ProtoMessage() {}

func (x *ModelState) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelState.ProtoReflect.Descriptor instead.
func (*ModelState) Descriptor() ([]byte, []int) {
	return file_pluggableharness_session_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *ModelState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelState) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

// ContextState is the session's context-window pressure for status bars.
type ContextState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tokens currently used against the window.
	UsedTokens int64 `protobuf:"varint,1,opt,name=used_tokens,json=usedTokens,proto3" json:"used_tokens,omitempty"`
	// The usable context window size in tokens (effective ceiling).
	WindowTokens  int64 `protobuf:"varint,2,opt,name=window_tokens,json=windowTokens,proto3" json:"window_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextState) Reset() {
	*x = ContextState{}
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextState) ProtoMessage() {}

func (x *ContextState) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextState.ProtoReflect.Descriptor instead.
func (*ContextState) Descriptor() ([]byte, []int) {
	return file_pluggableharness_session_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *ContextState) GetUsedTokens() int64 {
	if x != nil {
		return x.UsedTokens
	}
	return 0
}

func (x *ContextState) GetWindowTokens() int64 {
	if x != nil {
		return x.WindowTokens
	}
	return 0
}

// SessionState is the fixed-schema "where am I" snapshot a frontend
// renders into a status bar, HTTP header, stdout line, or spoken sentence.
// Assembled by KernelCallbackService.GetSessionState and republished on
// the event bus topic kernel.state whenever a watched field changes.
// Per-session: every snapshot names exactly one session. No extension
// point — a closed schema is what makes every frontend able to render it.
type SessionState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session's shareable lifecycle summary. MUST be set.
	Info *SessionInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	// Absolute working directory for this session. MUST be set once the
	// session has one; empty only before CreateSession finishes binding it.
	WorkingDirectory string `protobuf:"bytes,2,opt,name=working_directory,json=workingDirectory,proto3" json:"working_directory,omitempty"`
	// Version-control summary for working_directory. Absent when not a
	// VCS tree or not yet probed.
	Vcs *VcsState `protobuf:"bytes,3,opt,name=vcs,proto3,oneof" json:"vcs,omitempty"`
	// The model currently selected for this session's turns. Absent only
	// before the first model resolution.
	Model *ModelState `protobuf:"bytes,4,opt,name=model,proto3,oneof" json:"model,omitempty"`
	// The active thinking/effort level name for the current model, when
	// the model exposes an effort ladder. Absent when thinking is off or
	// the model has no effort control.
	ThinkingEffort *string `protobuf:"bytes,5,opt,name=thinking_effort,json=thinkingEffort,proto3,oneof" json:"thinking_effort,omitempty"`
	// Context-window pressure. Absent only before the first turn's usage
	// is known.
	Context *ContextState `protobuf:"bytes,6,opt,name=context,proto3,oneof" json:"context,omitempty"`
	// Number of completed turns in this session.
	TurnCount int32 `protobuf:"varint,7,opt,name=turn_count,json=turnCount,proto3" json:"turn_count,omitempty"`
	// Wall-clock time since info.started_at. MUST be set for a live
	// session; for a terminal session equals ended_at - started_at.
	Elapsed *durationpb.Duration `protobuf:"bytes,8,opt,name=elapsed,proto3" json:"elapsed,omitempty"`
	// Session-lifetime total tokens (input + output), summed from the cost
	// ledger / usage rollups. Zero when no model call has completed yet.
	TotalTokens int64 `protobuf:"varint,9,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	// The vendor budgets reported by the most recent completion, from that
	// completion's Usage or StreamMetadata.
	//
	// Distinct from account.quotas below: these are per-completion
	// readings taken from response headers as turns run, while
	// account.quotas is the account-level snapshot GetAccount returns
	// independently of any completion. A subscription product typically
	// publishes both, and they refresh on different schedules.
	//
	// MAY be empty — a vendor that publishes no budgets has nothing here,
	// and the kernel MUST NOT synthesize an entry from its own token
	// counting.
	Quotas []*v1.RateLimitSnapshot `protobuf:"bytes,10,rep,name=quotas,proto3" json:"quotas,omitempty"`
	// The account and entitlement state behind the session's model
	// provider, from GetAccount. Absent when the provider does not
	// implement that RPC, which is the common case for a bare API key.
	Account *v1.AccountSnapshot `protobuf:"bytes,11,opt,name=account,proto3,oneof" json:"account,omitempty"`
	// What the vendor said the most recent completion cost, in its own
	// denomination.
	//
	// Reported beside info.cost_usd, never instead of it: cost_usd remains
	// the kernel's computed figure and the one every rollup and budget
	// reads. This is here so a frontend can show that list price and
	// actual bill disagree — and so a subscription session, where computed
	// cost is structurally 0.00, has something truthful to display.
	VendorCost *v1.VendorCost `protobuf:"bytes,12,opt,name=vendor_cost,json=vendorCost,proto3,oneof" json:"vendor_cost,omitempty"`
	// The model that actually served the most recent completion, when the
	// vendor remapped it away from the requested id.
	//
	// Surfaced at session level because silent model substitution is
	// otherwise invisible: an operator sees only that answers got worse,
	// with nothing in the UI to attribute it to. Absent means the vendor
	// served what was asked for, or said nothing.
	ActualModel *string `protobuf:"bytes,13,opt,name=actual_model,json=actualModel,proto3,oneof" json:"actual_model,omitempty"`
	// What the session is doing right now, as opposed to info.status, which
	// is where the session sits in its lifecycle.
	//
	// The two answer different questions and a status bar needs the second
	// one: a session is `running` from creation until it ends, so a frontend
	// driven by status alone reads "running" while idle at the prompt and
	// "running" while a model call is in flight. Phase is what distinguishes
	// them.
	Phase         SessionPhase `protobuf:"varint,14,opt,name=phase,proto3,enum=pluggableharness.session.v1.SessionPhase" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionState) Reset() {
	*x = SessionState{}
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionState) ProtoMessage() {}

func (x *SessionState) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_session_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionState.ProtoReflect.Descriptor instead.
func (*SessionState) Descriptor() ([]byte, []int) {
	return file_pluggableharness_session_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *SessionState) GetInfo() *SessionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SessionState) GetWorkingDirectory() string {
	if x != nil {
		return x.WorkingDirectory
	}
	return ""
}

func (x *SessionState) GetVcs() *VcsState {
	if x != nil {
		return x.Vcs
	}
	return nil
}

func (x *SessionState) GetModel() *ModelState {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *SessionState) GetThinkingEffort() string {
	if x != nil && x.ThinkingEffort != nil {
		return *x.ThinkingEffort
	}
	return ""
}

func (x *SessionState) GetContext() *ContextState {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SessionState) GetTurnCount() int32 {
	if x != nil {
		return x.TurnCount
	}
	return 0
}

func (x *SessionState) GetElapsed() *durationpb.Duration {
	if x != nil {
		return x.Elapsed
	}
	return nil
}

func (x *SessionState) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *SessionState) GetQuotas() []*v1.RateLimitSnapshot {
	if x != nil {
		return x.Quotas
	}
	return nil
}

func (x *SessionState) GetAccount() *v1.AccountSnapshot {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *SessionState) GetVendorCost() *v1.VendorCost {
	if x != nil {
		return x.VendorCost
	}
	return nil
}

func (x *SessionState) GetActualModel() string {
	if x != nil && x.ActualModel != nil {
		return *x.ActualModel
	}
	return ""
}

func (x *SessionState) GetPhase() SessionPhase {
	if x != nil {
		return x.Phase
	}
	return SessionPhase_SESSION_PHASE_UNSPECIFIED
}

var File_pluggableharness_session_v1_types_proto protoreflect.FileDescriptor

const file_pluggableharness_session_v1_types_proto_rawDesc = "" +
	"\n" +
	"'pluggableharness/session/v1/types.proto\x12\x1bpluggableharness.session.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%pluggableharness/model/v1/types.proto\"\x98\x03\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12/\n" +
	"\x11parent_session_id\x18\x02 \x01(\tH\x00R\x0fparentSessionId\x88\x01\x01\x12\x18\n" +
	"\aprofile\x18\x03 \x01(\tR\aprofile\x12B\n" +
	"\x06status\x18\x04 \x01(\x0e2*.pluggableharness.session.v1.SessionStatusR\x06status\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\x05R\x05depth\x129\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12:\n" +
	"\bended_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x01R\aendedAt\x88\x01\x01\x12\x1e\n" +
	"\bcost_usd\x18\b \x01(\x01H\x02R\acostUsd\x88\x01\x01B\x14\n" +
	"\x12_parent_session_idB\v\n" +
	"\t_ended_atB\v\n" +
	"\t_cost_usd\"\x7f\n" +
	"\bVcsState\x12\x1b\n" +
	"\x06remote\x18\x01 \x01(\tH\x00R\x06remote\x88\x01\x01\x12\x1b\n" +
	"\x06branch\x18\x02 \x01(\tH\x01R\x06branch\x88\x01\x01\x12\x19\n" +
	"\x05dirty\x18\x03 \x01(\bH\x02R\x05dirty\x88\x01\x01B\t\n" +
	"\a_remoteB\t\n" +
	"\a_branchB\b\n" +
	"\x06_dirty\"8\n" +
	"\n" +
	"ModelState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"T\n" +
	"\fContextState\x12\x1f\n" +
	"\vused_tokens\x18\x01 \x01(\x03R\n" +
	"usedTokens\x12#\n" +
	"\rwindow_tokens\x18\x02 \x01(\x03R\fwindowTokens\"\x90\a\n" +
	"\fSessionState\x12<\n" +
	"\x04info\x18\x01 \x01(\v2(.pluggableharness.session.v1.SessionInfoR\x04info\x12+\n" +
	"\x11working_directory\x18\x02 \x01(\tR\x10workingDirectory\x12<\n" +
	"\x03vcs\x18\x03 \x01(\v2%.pluggableharness.session.v1.VcsStateH\x00R\x03vcs\x88\x01\x01\x12B\n" +
	"\x05model\x18\x04 \x01(\v2'.pluggableharness.session.v1.ModelStateH\x01R\x05model\x88\x01\x01\x12,\n" +
	"\x0fthinking_effort\x18\x05 \x01(\tH\x02R\x0ethinkingEffort\x88\x01\x01\x12H\n" +
	"\acontext\x18\x06 \x01(\v2).pluggableharness.session.v1.ContextStateH\x03R\acontext\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"turn_count\x18\a \x01(\x05R\tturnCount\x123\n" +
	"\aelapsed\x18\b \x01(\v2\x19.google.protobuf.DurationR\aelapsed\x12!\n" +
	"\ftotal_tokens\x18\t \x01(\x03R\vtotalTokens\x12D\n" +
	"\x06quotas\x18\n" +
	" \x03(\v2,.pluggableharness.model.v1.RateLimitSnapshotR\x06quotas\x12I\n" +
	"\aaccount\x18\v \x01(\v2*.pluggableharness.model.v1.AccountSnapshotH\x04R\aaccount\x88\x01\x01\x12K\n" +
	"\vvendor_cost\x18\f \x01(\v2%.pluggableharness.model.v1.VendorCostH\x05R\n" +
	"vendorCost\x88\x01\x01\x12&\n" +
	"\factual_model\x18\r \x01(\tH\x06R\vactualModel\x88\x01\x01\x12?\n" +
	"\x05phase\x18\x0e \x01(\x0e2).pluggableharness.session.v1.SessionPhaseR\x05phaseB\x06\n" +
	"\x04_vcsB\b\n" +
	"\x06_modelB\x12\n" +
	"\x10_thinking_effortB\n" +
	"\n" +
	"\b_contextB\n" +
	"\n" +
	"\b_accountB\x0e\n" +
	"\f_vendor_costB\x0f\n" +
	"\r_actual_model*\x98\x02\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATUS_RUNNING\x10\x01\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x02\x12\"\n" +
	"\x1eSESSION_STATUS_ERROR_MAX_TURNS\x10\x03\x12'\n" +
	"#SESSION_STATUS_ERROR_MAX_BUDGET_USD\x10\x04\x12'\n" +
	"#SESSION_STATUS_ERROR_MAX_WALL_CLOCK\x10\x05\x12\x1c\n" +
	"\x18SESSION_STATUS_CANCELLED\x10\x06\x12\x19\n" +
	"\x15SESSION_STATUS_FAILED\x10\a*c\n" +
	"\fSessionPhase\x12\x1d\n" +
	"\x19SESSION_PHASE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SESSION_PHASE_IDLE\x10\x01\x12\x1c\n" +
	"\x18SESSION_PHASE_GENERATING\x10\x02BBZ@github.com/pluggableharness/agent/pkg/session/proto/v1;sessionv1b\x06proto3"

var (
	file_pluggableharness_session_v1_types_proto_rawDescOnce sync.Once
	file_pluggableharness_session_v1_types_proto_rawDescData []byte
)

func file_pluggableharness_session_v1_types_proto_rawDescGZIP() []byte {
	file_pluggableharness_session_v1_types_proto_rawDescOnce.Do(func() {
		file_pluggableharness_session_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_session_v1_types_proto_rawDesc), len(file_pluggableharness_session_v1_types_proto_rawDesc)))
	})
	return file_pluggableharness_session_v1_types_proto_rawDescData
}

var file_pluggableharness_session_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pluggableharness_session_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pluggableharness_session_v1_types_proto_goTypes = []any{
	(SessionStatus)(0),            // 0: pluggableharness.session.v1.SessionStatus
	(SessionPhase)(0),             // 1: pluggableharness.session.v1.SessionPhase
	(*SessionInfo)(nil),           // 2: pluggableharness.session.v1.SessionInfo
	(*VcsState)(nil),              // 3: pluggableharness.session.v1.VcsState
	(*ModelState)(nil),            // 4: pluggableharness.session.v1.ModelState
	(*ContextState)(nil),          // 5: pluggableharness.session.v1.ContextState
	(*SessionState)(nil),          // 6: pluggableharness.session.v1.SessionState
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 8: google.protobuf.Duration
	(*v1.RateLimitSnapshot)(nil),  // 9: pluggableharness.model.v1.RateLimitSnapshot
	(*v1.AccountSnapshot)(nil),    // 10: pluggableharness.model.v1.AccountSnapshot
	(*v1.VendorCost)(nil),         // 11: pluggableharness.model.v1.VendorCost
}
var file_pluggableharness_session_v1_types_proto_depIdxs = []int32{
	0,  // 0: pluggableharness.session.v1.SessionInfo.status:type_name -> pluggableharness.session.v1.SessionStatus
	7,  // 1: pluggableharness.session.v1.SessionInfo.started_at:type_name -> google.protobuf.Timestamp
	7,  // 2: pluggableharness.session.v1.SessionInfo.ended_at:type_name -> google.protobuf.Timestamp
	2,  // 3: pluggableharness.session.v1.SessionState.info:type_name -> pluggableharness.session.v1.SessionInfo
	3,  // 4: pluggableharness.session.v1.SessionState.vcs:type_name -> pluggableharness.session.v1.VcsState
	4,  // 5: pluggableharness.session.v1.SessionState.model:type_name -> pluggableharness.session.v1.ModelState
	5,  // 6: pluggableharness.session.v1.SessionState.context:type_name -> pluggableharness.session.v1.ContextState
	8,  // 7: pluggableharness.session.v1.SessionState.elapsed:type_name -> google.protobuf.Duration
	9,  // 8: pluggableharness.session.v1.SessionState.quotas:type_name -> pluggableharness.model.v1.RateLimitSnapshot
	10, // 9: pluggableharness.session.v1.SessionState.account:type_name -> pluggableharness.model.v1.AccountSnapshot
	11, // 10: pluggableharness.session.v1.SessionState.vendor_cost:type_name -> pluggableharness.model.v1.VendorCost
	1,  // 11: pluggableharness.session.v1.SessionState.phase:type_name -> pluggableharness.session.v1.SessionPhase
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pluggableharness_session_v1_types_proto_init() }
func file_pluggableharness_session_v1_types_proto_init() {
	if File_pluggableharness_session_v1_types_proto != nil {
		return
	}
	file_pluggableharness_session_v1_types_proto_msgTypes[0].OneofWrappers = []any{}
	file_pluggableharness_session_v1_types_proto_msgTypes[1].OneofWrappers = []any{}
	file_pluggableharness_session_v1_types_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_session_v1_types_proto_rawDesc), len(file_pluggableharness_session_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_session_v1_types_proto_goTypes,
		DependencyIndexes: file_pluggableharness_session_v1_types_proto_depIdxs,
		EnumInfos:         file_pluggableharness_session_v1_types_proto_enumTypes,
		MessageInfos:      file_pluggableharness_session_v1_types_proto_msgTypes,
	}.Build()
	File_pluggableharness_session_v1_types_proto = out.File
	file_pluggableharness_session_v1_types_proto_goTypes = nil
	file_pluggableharness_session_v1_types_proto_depIdxs = nil
}
