// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/frontend/v1/errors.proto

package frontendv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FrontendErrorCategory classifies a FrontendError, per the error taxonomy
// in frontend.md §7.
type FrontendErrorCategory int32

const (
	// Zero value. Never valid for a real error; its presence on the wire
	// means a caller forgot to set the field.
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_UNSPECIFIED FrontendErrorCategory = 0
	// A RenderTree or PlacedContent could not be displayed.
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_RENDER_FAILED FrontendErrorCategory = 1
	// A ClientEvent was malformed or referenced an unknown/already-resolved
	// id (e.g. a plan_decision or interactive_response naming an item that
	// was already resolved by another attached frontend, per frontend.md
	// §3.3's first-response-wins arbitration).
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_INVALID_CLIENT_EVENT FrontendErrorCategory = 2
	// A PlacedContent named a Region this frontend cannot honor.
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_REGION_UNSUPPORTED FrontendErrorCategory = 3
	// An error that does not fit any other category.
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_UNKNOWN FrontendErrorCategory = 4
	// AttachSession, ResumeSession, DetachSession, or ListSessions'
	// parent_session_id filter named a session_id the kernel has no record
	// of.
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_SESSION_NOT_FOUND FrontendErrorCategory = 5
	// CreateSession failed — an invalid profile, or an unusable
	// working_directory.
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_SESSION_CREATE_FAILED FrontendErrorCategory = 6
	// A session-mutating control event targeted a session currently
	// SESSION_STATUS_RUNNING in a way that conflicts with that (reserved
	// for future session-mutating control events; no current variant in
	// this protocol revision triggers it, since DetachSession is always
	// safe on a running session).
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_SESSION_BUSY FrontendErrorCategory = 7
	// ResumeSession named a session file with a newer PRAGMA user_version
	// than this kernel understands (state-backend.md §"Schema migration").
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_SCHEMA_TOO_NEW FrontendErrorCategory = 8
	// A user_message (or any other new-turn-inducing event) targeted a
	// session attached replay-only per frontend.md §"Resume and re-open
	// semantics" — a bound-exhausted (error_max_*) or FAILED session
	// resumed via ResumeSession. Distinct from SESSION_BUSY: the session
	// isn't running, it's terminal and specifically barred from new turns.
	FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_SESSION_REPLAY_ONLY FrontendErrorCategory = 9
)

// Enum value maps for FrontendErrorCategory.
var (
	FrontendErrorCategory_name = map[int32]string{
		0: "FRONTEND_ERROR_CATEGORY_UNSPECIFIED",
		1: "FRONTEND_ERROR_CATEGORY_RENDER_FAILED",
		2: "FRONTEND_ERROR_CATEGORY_INVALID_CLIENT_EVENT",
		3: "FRONTEND_ERROR_CATEGORY_REGION_UNSUPPORTED",
		4: "FRONTEND_ERROR_CATEGORY_UNKNOWN",
		5: "FRONTEND_ERROR_CATEGORY_SESSION_NOT_FOUND",
		6: "FRONTEND_ERROR_CATEGORY_SESSION_CREATE_FAILED",
		7: "FRONTEND_ERROR_CATEGORY_SESSION_BUSY",
		8: "FRONTEND_ERROR_CATEGORY_SCHEMA_TOO_NEW",
		9: "FRONTEND_ERROR_CATEGORY_SESSION_REPLAY_ONLY",
	}
	FrontendErrorCategory_value = map[string]int32{
		"FRONTEND_ERROR_CATEGORY_UNSPECIFIED":           0,
		"FRONTEND_ERROR_CATEGORY_RENDER_FAILED":         1,
		"FRONTEND_ERROR_CATEGORY_INVALID_CLIENT_EVENT":  2,
		"FRONTEND_ERROR_CATEGORY_REGION_UNSUPPORTED":    3,
		"FRONTEND_ERROR_CATEGORY_UNKNOWN":               4,
		"FRONTEND_ERROR_CATEGORY_SESSION_NOT_FOUND":     5,
		"FRONTEND_ERROR_CATEGORY_SESSION_CREATE_FAILED": 6,
		"FRONTEND_ERROR_CATEGORY_SESSION_BUSY":          7,
		"FRONTEND_ERROR_CATEGORY_SCHEMA_TOO_NEW":        8,
		"FRONTEND_ERROR_CATEGORY_SESSION_REPLAY_ONLY":   9,
	}
)

func (x FrontendErrorCategory) Enum() *FrontendErrorCategory {
	p := new(FrontendErrorCategory)
	*p = x
	return p
}

func (x FrontendErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrontendErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_frontend_v1_errors_proto_enumTypes[0].Descriptor()
}

func (FrontendErrorCategory) Type() protoreflect.EnumType {
	return &file_pluggableharness_frontend_v1_errors_proto_enumTypes[0]
}

func (x FrontendErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrontendErrorCategory.Descriptor instead.
func (FrontendErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_errors_proto_rawDescGZIP(), []int{0}
}

// FrontendError is the structured error type for this category, per
// frontend.md §7. Carried in ServerEvent.Error and in the structured detail
// of a gRPC status returned from Configure.
type FrontendError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The error's category.
	Category FrontendErrorCategory `protobuf:"varint,1,opt,name=category,proto3,enum=pluggableharness.frontend.v1.FrontendErrorCategory" json:"category,omitempty"`
	// A human-readable message.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrontendError) Reset() {
	*x = FrontendError{}
	mi := &file_pluggableharness_frontend_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrontendError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrontendError) ProtoMessage() {}

func (x *FrontendError) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrontendError.ProtoReflect.Descriptor instead.
func (*FrontendError) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *FrontendError) GetCategory() FrontendErrorCategory {
	if x != nil {
		return x.Category
	}
	return FrontendErrorCategory_FRONTEND_ERROR_CATEGORY_UNSPECIFIED
}

func (x *FrontendError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pluggableharness_frontend_v1_errors_proto protoreflect.FileDescriptor

const file_pluggableharness_frontend_v1_errors_proto_rawDesc = "" +
	"\n" +
	")pluggableharness/frontend/v1/errors.proto\x12\x1cpluggableharness.frontend.v1\"z\n" +
	"\rFrontendError\x12O\n" +
	"\bcategory\x18\x01 \x01(\x0e23.pluggableharness.frontend.v1.FrontendErrorCategoryR\bcategory\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xdb\x03\n" +
	"\x15FrontendErrorCategory\x12'\n" +
	"#FRONTEND_ERROR_CATEGORY_UNSPECIFIED\x10\x00\x12)\n" +
	"%FRONTEND_ERROR_CATEGORY_RENDER_FAILED\x10\x01\x120\n" +
	",FRONTEND_ERROR_CATEGORY_INVALID_CLIENT_EVENT\x10\x02\x12.\n" +
	"*FRONTEND_ERROR_CATEGORY_REGION_UNSUPPORTED\x10\x03\x12#\n" +
	"\x1fFRONTEND_ERROR_CATEGORY_UNKNOWN\x10\x04\x12-\n" +
	")FRONTEND_ERROR_CATEGORY_SESSION_NOT_FOUND\x10\x05\x121\n" +
	"-FRONTEND_ERROR_CATEGORY_SESSION_CREATE_FAILED\x10\x06\x12(\n" +
	"$FRONTEND_ERROR_CATEGORY_SESSION_BUSY\x10\a\x12*\n" +
	"&FRONTEND_ERROR_CATEGORY_SCHEMA_TOO_NEW\x10\b\x12/\n" +
	"+FRONTEND_ERROR_CATEGORY_SESSION_REPLAY_ONLY\x10\tBDZBgithub.com/pluggableharness/agent/pkg/frontend/proto/v1;frontendv1b\x06proto3"

var (
	file_pluggableharness_frontend_v1_errors_proto_rawDescOnce sync.Once
	file_pluggableharness_frontend_v1_errors_proto_rawDescData []byte
)

func file_pluggableharness_frontend_v1_errors_proto_rawDescGZIP() []byte {
	file_pluggableharness_frontend_v1_errors_proto_rawDescOnce.Do(func() {
		file_pluggableharness_frontend_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_frontend_v1_errors_proto_rawDesc), len(file_pluggableharness_frontend_v1_errors_proto_rawDesc)))
	})
	return file_pluggableharness_frontend_v1_errors_proto_rawDescData
}

var file_pluggableharness_frontend_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pluggableharness_frontend_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pluggableharness_frontend_v1_errors_proto_goTypes = []any{
	(FrontendErrorCategory)(0), // 0: pluggableharness.frontend.v1.FrontendErrorCategory
	(*FrontendError)(nil),      // 1: pluggableharness.frontend.v1.FrontendError
}
var file_pluggableharness_frontend_v1_errors_proto_depIdxs = []int32{
	0, // 0: pluggableharness.frontend.v1.FrontendError.category:type_name -> pluggableharness.frontend.v1.FrontendErrorCategory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pluggableharness_frontend_v1_errors_proto_init() }
func file_pluggableharness_frontend_v1_errors_proto_init() {
	if File_pluggableharness_frontend_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_frontend_v1_errors_proto_rawDesc), len(file_pluggableharness_frontend_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_frontend_v1_errors_proto_goTypes,
		DependencyIndexes: file_pluggableharness_frontend_v1_errors_proto_depIdxs,
		EnumInfos:         file_pluggableharness_frontend_v1_errors_proto_enumTypes,
		MessageInfos:      file_pluggableharness_frontend_v1_errors_proto_msgTypes,
	}.Build()
	File_pluggableharness_frontend_v1_errors_proto = out.File
	file_pluggableharness_frontend_v1_errors_proto_goTypes = nil
	file_pluggableharness_frontend_v1_errors_proto_depIdxs = nil
}
