// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/frontend/v1/events.proto

package frontendv1

import (
	v15 "github.com/pluggableharness/agent/pkg/content/proto/v1"
	v14 "github.com/pluggableharness/agent/pkg/model/proto/v1"
	v11 "github.com/pluggableharness/agent/pkg/plan/proto/v1"
	v1 "github.com/pluggableharness/agent/pkg/render/proto/v1"
	v12 "github.com/pluggableharness/agent/pkg/session/proto/v1"
	v13 "github.com/pluggableharness/agent/pkg/slashcommand/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientDecision is the user's resolution of a pending PermissionRequest,
// per agent-loop.md §5.2's `ask` decision.
type ClientDecision int32

const (
	// Zero value. Never valid for a real decision; its presence on the wire
	// means a caller forgot to set the field.
	ClientDecision_CLIENT_DECISION_UNSPECIFIED ClientDecision = 0
	// The user approved the plan item as proposed (or as corrected, see
	// ClientEvent.PlanDecision.corrected_input).
	ClientDecision_CLIENT_DECISION_ALLOW ClientDecision = 1
	// The user rejected the plan item.
	ClientDecision_CLIENT_DECISION_DENY ClientDecision = 2
)

// Enum value maps for ClientDecision.
var (
	ClientDecision_name = map[int32]string{
		0: "CLIENT_DECISION_UNSPECIFIED",
		1: "CLIENT_DECISION_ALLOW",
		2: "CLIENT_DECISION_DENY",
	}
	ClientDecision_value = map[string]int32{
		"CLIENT_DECISION_UNSPECIFIED": 0,
		"CLIENT_DECISION_ALLOW":       1,
		"CLIENT_DECISION_DENY":        2,
	}
)

func (x ClientDecision) Enum() *ClientDecision {
	p := new(ClientDecision)
	*p = x
	return p
}

func (x ClientDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_frontend_v1_events_proto_enumTypes[0].Descriptor()
}

func (ClientDecision) Type() protoreflect.EnumType {
	return &file_pluggableharness_frontend_v1_events_proto_enumTypes[0]
}

func (x ClientDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientDecision.Descriptor instead.
func (ClientDecision) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0}
}

// PlanDecisionScope is how durably a ClientEvent.PlanDecision applies,
// beyond just the one PlanItem it names. Orthogonal to ClientDecision:
// decision says allow/deny, scope says how long that verdict is
// remembered. agent-loop/plan-apply-gate.md's "PlanDecisionScope
// semantics" documents evaluation order and the ALWAYS persistence
// obligation.
type PlanDecisionScope int32

const (
	// Zero value. Never valid for a real decision; its presence on the wire
	// means a caller forgot to set the field.
	PlanDecisionScope_PLAN_DECISION_SCOPE_UNSPECIFIED PlanDecisionScope = 0
	// Applies to this PlanItem only. The default a frontend SHOULD send
	// when the user hasn't explicitly asked for a broader scope.
	PlanDecisionScope_PLAN_DECISION_SCOPE_ONCE PlanDecisionScope = 1
	// Applies to the rest of this session, for calls matching the same
	// provider/tool_name (and, where policy's match schema supports it,
	// narrower criteria) — an in-memory, session-lifetime rule, not
	// written to agent.hcl or any persisted policy store.
	PlanDecisionScope_PLAN_DECISION_SCOPE_SESSION PlanDecisionScope = 2
	// The kernel persists this as policy, applying beyond this session to
	// future sessions under the same profile. Requires kernel-side policy
	// persistence (agent-loop/plan-apply-gate.md#plandecisionscope-semantics)
	// — a frontend MUST NOT assume ALWAYS is honored merely because it was
	// sent; a kernel that cannot persist policy MUST reject it as a
	// distinct error rather than silently downgrading to SESSION or ONCE.
	PlanDecisionScope_PLAN_DECISION_SCOPE_ALWAYS PlanDecisionScope = 3
)

// Enum value maps for PlanDecisionScope.
var (
	PlanDecisionScope_name = map[int32]string{
		0: "PLAN_DECISION_SCOPE_UNSPECIFIED",
		1: "PLAN_DECISION_SCOPE_ONCE",
		2: "PLAN_DECISION_SCOPE_SESSION",
		3: "PLAN_DECISION_SCOPE_ALWAYS",
	}
	PlanDecisionScope_value = map[string]int32{
		"PLAN_DECISION_SCOPE_UNSPECIFIED": 0,
		"PLAN_DECISION_SCOPE_ONCE":        1,
		"PLAN_DECISION_SCOPE_SESSION":     2,
		"PLAN_DECISION_SCOPE_ALWAYS":      3,
	}
)

func (x PlanDecisionScope) Enum() *PlanDecisionScope {
	p := new(PlanDecisionScope)
	*p = x
	return p
}

func (x PlanDecisionScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlanDecisionScope) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_frontend_v1_events_proto_enumTypes[1].Descriptor()
}

func (PlanDecisionScope) Type() protoreflect.EnumType {
	return &file_pluggableharness_frontend_v1_events_proto_enumTypes[1]
}

func (x PlanDecisionScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlanDecisionScope.Descriptor instead.
func (PlanDecisionScope) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1}
}

// ServerEvent is one message the kernel sends to an attached frontend over
// the single multiplexed Attach stream, described in frontend.md §3.2.
// Exactly one variant is set.
type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session this event is scoped to. Set for every session-scoped
	// variant (stream_delta .. session_status_update); empty for the one
	// connection-level variant, session_list.
	SessionId string `protobuf:"bytes,100,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Correlates a response to the ClientEvent control message that
	// triggered it, echoing that message's own request_id
	// (hello/create_session/attach_session/resume_session/detach_session/
	// list_sessions all carry one). Set on session_created, session_attached,
	// backfill_complete, session_detached, session_list, and on error when
	// it answers one of those control requests. Unset for ordinary live
	// session events that were not triggered by a specific client request
	// (stream_delta, render, plan_ready, ...).
	RequestId *string `protobuf:"bytes,101,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_StreamDelta_
	//	*ServerEvent_Render_
	//	*ServerEvent_PermissionRequest_
	//	*ServerEvent_PlanReady_
	//	*ServerEvent_InteractiveRequest_
	//	*ServerEvent_SessionTreeUpdate_
	//	*ServerEvent_Error_
	//	*ServerEvent_SessionCreated_
	//	*ServerEvent_SessionAttached_
	//	*ServerEvent_BackfillComplete_
	//	*ServerEvent_SessionDetached_
	//	*ServerEvent_SessionList_
	//	*ServerEvent_SlashCommandRegistry_
	//	*ServerEvent_UsageUpdate_
	//	*ServerEvent_SessionStatusUpdate_
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *ServerEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ServerEvent) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetStreamDelta() *ServerEvent_StreamDelta {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_StreamDelta_); ok {
			return x.StreamDelta
		}
	}
	return nil
}

func (x *ServerEvent) GetRender() *ServerEvent_Render {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Render_); ok {
			return x.Render
		}
	}
	return nil
}

func (x *ServerEvent) GetPermissionRequest() *ServerEvent_PermissionRequest {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_PermissionRequest_); ok {
			return x.PermissionRequest
		}
	}
	return nil
}

func (x *ServerEvent) GetPlanReady() *ServerEvent_PlanReady {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_PlanReady_); ok {
			return x.PlanReady
		}
	}
	return nil
}

func (x *ServerEvent) GetInteractiveRequest() *ServerEvent_InteractiveRequest {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_InteractiveRequest_); ok {
			return x.InteractiveRequest
		}
	}
	return nil
}

func (x *ServerEvent) GetSessionTreeUpdate() *ServerEvent_SessionTreeUpdate {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_SessionTreeUpdate_); ok {
			return x.SessionTreeUpdate
		}
	}
	return nil
}

func (x *ServerEvent) GetError() *ServerEvent_Error {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Error_); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerEvent) GetSessionCreated() *ServerEvent_SessionCreated {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_SessionCreated_); ok {
			return x.SessionCreated
		}
	}
	return nil
}

func (x *ServerEvent) GetSessionAttached() *ServerEvent_SessionAttached {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_SessionAttached_); ok {
			return x.SessionAttached
		}
	}
	return nil
}

func (x *ServerEvent) GetBackfillComplete() *ServerEvent_BackfillComplete {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_BackfillComplete_); ok {
			return x.BackfillComplete
		}
	}
	return nil
}

func (x *ServerEvent) GetSessionDetached() *ServerEvent_SessionDetached {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_SessionDetached_); ok {
			return x.SessionDetached
		}
	}
	return nil
}

func (x *ServerEvent) GetSessionList() *ServerEvent_SessionList {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_SessionList_); ok {
			return x.SessionList
		}
	}
	return nil
}

func (x *ServerEvent) GetSlashCommandRegistry() *ServerEvent_SlashCommandRegistry {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_SlashCommandRegistry_); ok {
			return x.SlashCommandRegistry
		}
	}
	return nil
}

func (x *ServerEvent) GetUsageUpdate() *ServerEvent_UsageUpdate {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_UsageUpdate_); ok {
			return x.UsageUpdate
		}
	}
	return nil
}

func (x *ServerEvent) GetSessionStatusUpdate() *ServerEvent_SessionStatusUpdate {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_SessionStatusUpdate_); ok {
			return x.SessionStatusUpdate
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_StreamDelta_ struct {
	StreamDelta *ServerEvent_StreamDelta `protobuf:"bytes,1,opt,name=stream_delta,json=streamDelta,proto3,oneof"`
}

type ServerEvent_Render_ struct {
	Render *ServerEvent_Render `protobuf:"bytes,2,opt,name=render,proto3,oneof"`
}

type ServerEvent_PermissionRequest_ struct {
	PermissionRequest *ServerEvent_PermissionRequest `protobuf:"bytes,3,opt,name=permission_request,json=permissionRequest,proto3,oneof"`
}

type ServerEvent_PlanReady_ struct {
	PlanReady *ServerEvent_PlanReady `protobuf:"bytes,4,opt,name=plan_ready,json=planReady,proto3,oneof"`
}

type ServerEvent_InteractiveRequest_ struct {
	InteractiveRequest *ServerEvent_InteractiveRequest `protobuf:"bytes,5,opt,name=interactive_request,json=interactiveRequest,proto3,oneof"`
}

type ServerEvent_SessionTreeUpdate_ struct {
	SessionTreeUpdate *ServerEvent_SessionTreeUpdate `protobuf:"bytes,6,opt,name=session_tree_update,json=sessionTreeUpdate,proto3,oneof"`
}

type ServerEvent_Error_ struct {
	Error *ServerEvent_Error `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

type ServerEvent_SessionCreated_ struct {
	// Acknowledges a ClientEvent.CreateSession, carrying the new
	// session's info. The kernel auto-attaches the creating stream to
	// this session (frontend.md §"Session lifecycle").
	SessionCreated *ServerEvent_SessionCreated `protobuf:"bytes,8,opt,name=session_created,json=sessionCreated,proto3,oneof"`
}

type ServerEvent_SessionAttached_ struct {
	// Acknowledges a ClientEvent.AttachSession or ResumeSession, carrying
	// the session's current info. Opens the backfill batch: the
	// replayed `render` events that follow, bracketed by the eventual
	// backfill_complete (frontend.md §"Backfill").
	SessionAttached *ServerEvent_SessionAttached `protobuf:"bytes,9,opt,name=session_attached,json=sessionAttached,proto3,oneof"`
}

type ServerEvent_BackfillComplete_ struct {
	// The done-marker closing a backfill batch opened by session_attached
	// above. Live events with sequence > last_sequence follow this.
	// Unicast to the attaching stream only, never broadcast.
	BackfillComplete *ServerEvent_BackfillComplete `protobuf:"bytes,10,opt,name=backfill_complete,json=backfillComplete,proto3,oneof"`
}

type ServerEvent_SessionDetached_ struct {
	// Acknowledges a ClientEvent.DetachSession.
	SessionDetached *ServerEvent_SessionDetached `protobuf:"bytes,11,opt,name=session_detached,json=sessionDetached,proto3,oneof"`
}

type ServerEvent_SessionList_ struct {
	// Answers a ClientEvent.ListSessions. Connection-scoped — session_id
	// above is empty for this variant.
	SessionList *ServerEvent_SessionList `protobuf:"bytes,12,opt,name=session_list,json=sessionList,proto3,oneof"`
}

type ServerEvent_SlashCommandRegistry_ struct {
	// The profile-scoped aggregate slash-command registry across every
	// provider loaded for this session, sent on session_attached and
	// again whenever the registry changes.
	SlashCommandRegistry *ServerEvent_SlashCommandRegistry `protobuf:"bytes,14,opt,name=slash_command_registry,json=slashCommandRegistry,proto3,oneof"`
}

type ServerEvent_UsageUpdate_ struct {
	// Per-turn token/cost accounting and context-budget pressure.
	UsageUpdate *ServerEvent_UsageUpdate `protobuf:"bytes,15,opt,name=usage_update,json=usageUpdate,proto3,oneof"`
}

type ServerEvent_SessionStatusUpdate_ struct {
	// This session's OWN lifecycle status. Deliberately distinct from
	// session_tree_update above, which reports a CHILD session's status
	// — this variant is the attached session's own transition (e.g.
	// RUNNING -> COMPLETED, or a bound-exhausted re-open per
	// frontend.md §"Resume and re-open semantics").
	SessionStatusUpdate *ServerEvent_SessionStatusUpdate `protobuf:"bytes,16,opt,name=session_status_update,json=sessionStatusUpdate,proto3,oneof"`
}

func (*ServerEvent_StreamDelta_) isServerEvent_Event() {}

func (*ServerEvent_Render_) isServerEvent_Event() {}

func (*ServerEvent_PermissionRequest_) isServerEvent_Event() {}

func (*ServerEvent_PlanReady_) isServerEvent_Event() {}

func (*ServerEvent_InteractiveRequest_) isServerEvent_Event() {}

func (*ServerEvent_SessionTreeUpdate_) isServerEvent_Event() {}

func (*ServerEvent_Error_) isServerEvent_Event() {}

func (*ServerEvent_SessionCreated_) isServerEvent_Event() {}

func (*ServerEvent_SessionAttached_) isServerEvent_Event() {}

func (*ServerEvent_BackfillComplete_) isServerEvent_Event() {}

func (*ServerEvent_SessionDetached_) isServerEvent_Event() {}

func (*ServerEvent_SessionList_) isServerEvent_Event() {}

func (*ServerEvent_SlashCommandRegistry_) isServerEvent_Event() {}

func (*ServerEvent_UsageUpdate_) isServerEvent_Event() {}

func (*ServerEvent_SessionStatusUpdate_) isServerEvent_Event() {}

// ClientEvent is one message a frontend sends to the kernel over the
// single multiplexed Attach stream, described in frontend.md §3.2.
// Exactly one variant is set.
type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session this event is scoped to. REQUIRED for every
	// session-scoped variant (user_message, slash_command, plan_decision,
	// interactive_response, action_trigger, interrupt) — the kernel MUST
	// reject one of these arriving with an empty session_id as
	// FRONTEND_ERROR_CATEGORY_INVALID_CLIENT_EVENT. Empty for the
	// connection-level control variants (hello, create_session,
	// attach_session, resume_session, detach_session, list_sessions), which
	// either don't yet have a bound session or operate across sessions —
	// attach_session/resume_session instead name the target session inside
	// their own nested message.
	SessionId string `protobuf:"bytes,100,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_UserMessage_
	//	*ClientEvent_SlashCommand_
	//	*ClientEvent_PlanDecision_
	//	*ClientEvent_InteractiveResponse_
	//	*ClientEvent_ActionTrigger_
	//	*ClientEvent_Interrupt_
	//	*ClientEvent_Hello_
	//	*ClientEvent_CreateSession_
	//	*ClientEvent_AttachSession_
	//	*ClientEvent_ResumeSession_
	//	*ClientEvent_DetachSession_
	//	*ClientEvent_ListSessions_
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *ClientEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetUserMessage() *ClientEvent_UserMessage {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_UserMessage_); ok {
			return x.UserMessage
		}
	}
	return nil
}

func (x *ClientEvent) GetSlashCommand() *ClientEvent_SlashCommand {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_SlashCommand_); ok {
			return x.SlashCommand
		}
	}
	return nil
}

func (x *ClientEvent) GetPlanDecision() *ClientEvent_PlanDecision {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_PlanDecision_); ok {
			return x.PlanDecision
		}
	}
	return nil
}

func (x *ClientEvent) GetInteractiveResponse() *ClientEvent_InteractiveResponse {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_InteractiveResponse_); ok {
			return x.InteractiveResponse
		}
	}
	return nil
}

func (x *ClientEvent) GetActionTrigger() *ClientEvent_ActionTrigger {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_ActionTrigger_); ok {
			return x.ActionTrigger
		}
	}
	return nil
}

func (x *ClientEvent) GetInterrupt() *ClientEvent_Interrupt {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Interrupt_); ok {
			return x.Interrupt
		}
	}
	return nil
}

func (x *ClientEvent) GetHello() *ClientEvent_Hello {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Hello_); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientEvent) GetCreateSession() *ClientEvent_CreateSession {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_CreateSession_); ok {
			return x.CreateSession
		}
	}
	return nil
}

func (x *ClientEvent) GetAttachSession() *ClientEvent_AttachSession {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_AttachSession_); ok {
			return x.AttachSession
		}
	}
	return nil
}

func (x *ClientEvent) GetResumeSession() *ClientEvent_ResumeSession {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_ResumeSession_); ok {
			return x.ResumeSession
		}
	}
	return nil
}

func (x *ClientEvent) GetDetachSession() *ClientEvent_DetachSession {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_DetachSession_); ok {
			return x.DetachSession
		}
	}
	return nil
}

func (x *ClientEvent) GetListSessions() *ClientEvent_ListSessions {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_ListSessions_); ok {
			return x.ListSessions
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_UserMessage_ struct {
	UserMessage *ClientEvent_UserMessage `protobuf:"bytes,1,opt,name=user_message,json=userMessage,proto3,oneof"`
}

type ClientEvent_SlashCommand_ struct {
	SlashCommand *ClientEvent_SlashCommand `protobuf:"bytes,2,opt,name=slash_command,json=slashCommand,proto3,oneof"`
}

type ClientEvent_PlanDecision_ struct {
	PlanDecision *ClientEvent_PlanDecision `protobuf:"bytes,3,opt,name=plan_decision,json=planDecision,proto3,oneof"`
}

type ClientEvent_InteractiveResponse_ struct {
	InteractiveResponse *ClientEvent_InteractiveResponse `protobuf:"bytes,4,opt,name=interactive_response,json=interactiveResponse,proto3,oneof"`
}

type ClientEvent_ActionTrigger_ struct {
	ActionTrigger *ClientEvent_ActionTrigger `protobuf:"bytes,5,opt,name=action_trigger,json=actionTrigger,proto3,oneof"`
}

type ClientEvent_Interrupt_ struct {
	Interrupt *ClientEvent_Interrupt `protobuf:"bytes,6,opt,name=interrupt,proto3,oneof"`
}

type ClientEvent_Hello_ struct {
	// MAY be sent as the first message on a newly opened Attach stream;
	// asserts the protocol version only. Not required to bind any
	// session — that happens via the variants below.
	Hello *ClientEvent_Hello `protobuf:"bytes,7,opt,name=hello,proto3,oneof"`
}

type ClientEvent_CreateSession_ struct {
	// Creates a new session and auto-attaches this stream to it.
	CreateSession *ClientEvent_CreateSession `protobuf:"bytes,8,opt,name=create_session,json=createSession,proto3,oneof"`
}

type ClientEvent_AttachSession_ struct {
	// Subscribes an existing (possibly live) session onto this stream,
	// triggering a backfill replay (frontend.md §"Backfill").
	AttachSession *ClientEvent_AttachSession `protobuf:"bytes,9,opt,name=attach_session,json=attachSession,proto3,oneof"`
}

type ClientEvent_ResumeSession_ struct {
	// Attaches a historical session for continuation or replay, per
	// frontend.md §"Resume and re-open semantics" — a COMPLETED or
	// CANCELLED session MAY be re-opened to RUNNING for new turns; a
	// bound-exhausted (error_max_*) or FAILED session attaches
	// replay-only and rejects any subsequent user_message for it.
	ResumeSession *ClientEvent_ResumeSession `protobuf:"bytes,10,opt,name=resume_session,json=resumeSession,proto3,oneof"`
}

type ClientEvent_DetachSession_ struct {
	// Unsubscribes a session from this stream without affecting the
	// session itself.
	DetachSession *ClientEvent_DetachSession `protobuf:"bytes,11,opt,name=detach_session,json=detachSession,proto3,oneof"`
}

type ClientEvent_ListSessions_ struct {
	// Requests the connection-scoped session summary list.
	ListSessions *ClientEvent_ListSessions `protobuf:"bytes,12,opt,name=list_sessions,json=listSessions,proto3,oneof"`
}

func (*ClientEvent_UserMessage_) isClientEvent_Event() {}

func (*ClientEvent_SlashCommand_) isClientEvent_Event() {}

func (*ClientEvent_PlanDecision_) isClientEvent_Event() {}

func (*ClientEvent_InteractiveResponse_) isClientEvent_Event() {}

func (*ClientEvent_ActionTrigger_) isClientEvent_Event() {}

func (*ClientEvent_Interrupt_) isClientEvent_Event() {}

func (*ClientEvent_Hello_) isClientEvent_Event() {}

func (*ClientEvent_CreateSession_) isClientEvent_Event() {}

func (*ClientEvent_AttachSession_) isClientEvent_Event() {}

func (*ClientEvent_ResumeSession_) isClientEvent_Event() {}

func (*ClientEvent_DetachSession_) isClientEvent_Event() {}

func (*ClientEvent_ListSessions_) isClientEvent_Event() {}

// StreamDelta is the fast path for incremental text display, skipping a
// full Render() round trip. frontend.md §3.2.
type ServerEvent_StreamDelta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies which displayed element this delta appends to (e.g. a
	// RenderNode id from a prior Render), for correlating consecutive
	// deltas into one growing piece of text.
	TargetId string `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	// The incremental text to append.
	Text          string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_StreamDelta) Reset() {
	*x = ServerEvent_StreamDelta{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_StreamDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_StreamDelta) ProtoMessage() {}

func (x *ServerEvent_StreamDelta) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_StreamDelta.ProtoReflect.Descriptor instead.
func (*ServerEvent_StreamDelta) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServerEvent_StreamDelta) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ServerEvent_StreamDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Render carries one placed RenderTree to Paint. frontend.md §3.2.
type ServerEvent_Render struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The content, its target region, and its replace/append behavior.
	Content       *v1.PlacedContent `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_Render) Reset() {
	*x = ServerEvent_Render{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_Render) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_Render) ProtoMessage() {}

func (x *ServerEvent_Render) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_Render.ProtoReflect.Descriptor instead.
func (*ServerEvent_Render) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ServerEvent_Render) GetContent() *v1.PlacedContent {
	if x != nil {
		return x.Content
	}
	return nil
}

// PermissionRequest asks the user to resolve an agent-loop.md §5.2 `ask`
// decision: the kernel blocks this plan item's apply until a
// ClientEvent.plan_decision resolves it.
type ServerEvent_PermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plan item awaiting a decision.
	PlanItem      *v11.PlanItem `protobuf:"bytes,1,opt,name=plan_item,json=planItem,proto3" json:"plan_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_PermissionRequest) Reset() {
	*x = ServerEvent_PermissionRequest{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_PermissionRequest) ProtoMessage() {}

func (x *ServerEvent_PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_PermissionRequest.ProtoReflect.Descriptor instead.
func (*ServerEvent_PermissionRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ServerEvent_PermissionRequest) GetPlanItem() *v11.PlanItem {
	if x != nil {
		return x.PlanItem
	}
	return nil
}

// PlanReady announces a complete plan for display, e.g. before execution
// begins or after a replan.
type ServerEvent_PlanReady struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plan to display.
	Plan          *v11.Plan `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_PlanReady) Reset() {
	*x = ServerEvent_PlanReady{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_PlanReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_PlanReady) ProtoMessage() {}

func (x *ServerEvent_PlanReady) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_PlanReady.ProtoReflect.Descriptor instead.
func (*ServerEvent_PlanReady) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ServerEvent_PlanReady) GetPlan() *v11.Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

// InteractiveRequest corresponds to a tool.md §2.1
// TOOL_KIND_INTERACTIVE call. A frontend MUST render this in the
// REGION_OVERLAY region (frontend.md §2), the same visual treatment as an
// ordinary `ask` prompt.
type ServerEvent_InteractiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies the pending interactive tool call, echoed back in the
	// resolving ClientEvent.interactive_response.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// The tool being invoked (tool.md §2.1 ToolSchema.name).
	ToolName string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// The prompt to render.
	Prompt        *v1.RenderTree `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_InteractiveRequest) Reset() {
	*x = ServerEvent_InteractiveRequest{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_InteractiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_InteractiveRequest) ProtoMessage() {}

func (x *ServerEvent_InteractiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_InteractiveRequest.ProtoReflect.Descriptor instead.
func (*ServerEvent_InteractiveRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 4}
}

func (x *ServerEvent_InteractiveRequest) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ServerEvent_InteractiveRequest) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ServerEvent_InteractiveRequest) GetPrompt() *v1.RenderTree {
	if x != nil {
		return x.Prompt
	}
	return nil
}

// SessionTreeUpdate reports a change in a nested sub-session's lifecycle
// (e.g. a RunSession-spawned child), so a frontend can keep a
// SubSessionNode's displayed status current. Reports a CHILD session's
// status — for the attached session's OWN status, see
// SessionStatusUpdate below, a deliberately distinct variant.
type ServerEvent_SessionTreeUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The parent session's id.
	ParentSessionId string `protobuf:"bytes,1,opt,name=parent_session_id,json=parentSessionId,proto3" json:"parent_session_id,omitempty"`
	// The child session's id.
	ChildSessionId string `protobuf:"bytes,2,opt,name=child_session_id,json=childSessionId,proto3" json:"child_session_id,omitempty"`
	// The child session's current status.
	Status        v12.SessionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pluggableharness.session.v1.SessionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_SessionTreeUpdate) Reset() {
	*x = ServerEvent_SessionTreeUpdate{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_SessionTreeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_SessionTreeUpdate) ProtoMessage() {}

func (x *ServerEvent_SessionTreeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_SessionTreeUpdate.ProtoReflect.Descriptor instead.
func (*ServerEvent_SessionTreeUpdate) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 5}
}

func (x *ServerEvent_SessionTreeUpdate) GetParentSessionId() string {
	if x != nil {
		return x.ParentSessionId
	}
	return ""
}

func (x *ServerEvent_SessionTreeUpdate) GetChildSessionId() string {
	if x != nil {
		return x.ChildSessionId
	}
	return ""
}

func (x *ServerEvent_SessionTreeUpdate) GetStatus() v12.SessionStatus {
	if x != nil {
		return x.Status
	}
	return v12.SessionStatus(0)
}

// Error carries a structured, non-fatal frontend error for display.
type ServerEvent_Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The error's category and message.
	Error         *FrontendError `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_Error) Reset() {
	*x = ServerEvent_Error{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_Error) ProtoMessage() {}

func (x *ServerEvent_Error) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_Error.ProtoReflect.Descriptor instead.
func (*ServerEvent_Error) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 6}
}

func (x *ServerEvent_Error) GetError() *FrontendError {
	if x != nil {
		return x.Error
	}
	return nil
}

// SessionCreated acknowledges a successful ClientEvent.CreateSession.
type ServerEvent_SessionCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created session's info.
	Info          *v12.SessionInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_SessionCreated) Reset() {
	*x = ServerEvent_SessionCreated{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_SessionCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_SessionCreated) ProtoMessage() {}

func (x *ServerEvent_SessionCreated) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_SessionCreated.ProtoReflect.Descriptor instead.
func (*ServerEvent_SessionCreated) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 7}
}

func (x *ServerEvent_SessionCreated) GetInfo() *v12.SessionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// SessionAttached acknowledges a successful ClientEvent.AttachSession or
// ResumeSession, and opens that session's backfill batch.
type ServerEvent_SessionAttached struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The attached session's current info.
	Info          *v12.SessionInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_SessionAttached) Reset() {
	*x = ServerEvent_SessionAttached{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_SessionAttached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_SessionAttached) ProtoMessage() {}

func (x *ServerEvent_SessionAttached) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_SessionAttached.ProtoReflect.Descriptor instead.
func (*ServerEvent_SessionAttached) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 8}
}

func (x *ServerEvent_SessionAttached) GetInfo() *v12.SessionInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// BackfillComplete is the done-marker closing a backfill batch, per
// frontend.md §"Backfill". Unicast to the attaching stream only.
type ServerEvent_BackfillComplete struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The persisted sequence number of the last event replayed in this
	// batch. Live events with sequence > last_sequence follow.
	LastSequence  int64 `protobuf:"varint,1,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_BackfillComplete) Reset() {
	*x = ServerEvent_BackfillComplete{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_BackfillComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_BackfillComplete) ProtoMessage() {}

func (x *ServerEvent_BackfillComplete) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_BackfillComplete.ProtoReflect.Descriptor instead.
func (*ServerEvent_BackfillComplete) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 9}
}

func (x *ServerEvent_BackfillComplete) GetLastSequence() int64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

// SessionDetached acknowledges a successful ClientEvent.DetachSession.
type ServerEvent_SessionDetached struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_SessionDetached) Reset() {
	*x = ServerEvent_SessionDetached{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_SessionDetached) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_SessionDetached) ProtoMessage() {}

func (x *ServerEvent_SessionDetached) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_SessionDetached.ProtoReflect.Descriptor instead.
func (*ServerEvent_SessionDetached) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 10}
}

// SessionList answers a ClientEvent.ListSessions.
type ServerEvent_SessionList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The matching sessions, most-recently-started first.
	Sessions      []*v12.SessionInfo `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_SessionList) Reset() {
	*x = ServerEvent_SessionList{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_SessionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_SessionList) ProtoMessage() {}

func (x *ServerEvent_SessionList) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_SessionList.ProtoReflect.Descriptor instead.
func (*ServerEvent_SessionList) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 11}
}

func (x *ServerEvent_SessionList) GetSessions() []*v12.SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

// SlashCommandRegistry is the profile-scoped aggregate of every loaded
// provider's declared slash commands for this session, per
// frontend.md §"Slash commands".
type ServerEvent_SlashCommandRegistry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Every registered command, name-collision-checked at config-load
	// time (frontend.md §"Slash commands").
	Commands      []*v13.SlashCommandSpec `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_SlashCommandRegistry) Reset() {
	*x = ServerEvent_SlashCommandRegistry{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_SlashCommandRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_SlashCommandRegistry) ProtoMessage() {}

func (x *ServerEvent_SlashCommandRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_SlashCommandRegistry.ProtoReflect.Descriptor instead.
func (*ServerEvent_SlashCommandRegistry) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 12}
}

func (x *ServerEvent_SlashCommandRegistry) GetCommands() []*v13.SlashCommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

// UsageUpdate carries one turn's token/cost accounting and the
// session's running totals, for a context-budget indicator or similar.
type ServerEvent_UsageUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This turn's token accounting.
	Turn *v14.Usage `protobuf:"bytes,1,opt,name=turn,proto3" json:"turn,omitempty"`
	// The session's running total spend in USD, mirroring
	// session.v1.SessionInfo.cost_usd.
	CumulativeCostUsd float64 `protobuf:"fixed64,2,opt,name=cumulative_cost_usd,json=cumulativeCostUsd,proto3" json:"cumulative_cost_usd,omitempty"`
	// The session's running total token count against `effective_ceiling`
	// below — the pair a context-budget indicator divides to get
	// pressure (e.g. "51,204 / 200,000").
	UsedTokens int64 `protobuf:"varint,3,opt,name=used_tokens,json=usedTokens,proto3" json:"used_tokens,omitempty"`
	// The usable context budget this session's turns are measured
	// against (model.v1.ModelTarget.effective_ceiling).
	EffectiveCeiling int64 `protobuf:"varint,4,opt,name=effective_ceiling,json=effectiveCeiling,proto3" json:"effective_ceiling,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerEvent_UsageUpdate) Reset() {
	*x = ServerEvent_UsageUpdate{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_UsageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_UsageUpdate) ProtoMessage() {}

func (x *ServerEvent_UsageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_UsageUpdate.ProtoReflect.Descriptor instead.
func (*ServerEvent_UsageUpdate) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 13}
}

func (x *ServerEvent_UsageUpdate) GetTurn() *v14.Usage {
	if x != nil {
		return x.Turn
	}
	return nil
}

func (x *ServerEvent_UsageUpdate) GetCumulativeCostUsd() float64 {
	if x != nil {
		return x.CumulativeCostUsd
	}
	return 0
}

func (x *ServerEvent_UsageUpdate) GetUsedTokens() int64 {
	if x != nil {
		return x.UsedTokens
	}
	return 0
}

func (x *ServerEvent_UsageUpdate) GetEffectiveCeiling() int64 {
	if x != nil {
		return x.EffectiveCeiling
	}
	return 0
}

// SessionStatusUpdate reports the attached session's OWN lifecycle
// status transition. Distinct from SessionTreeUpdate above, which
// reports a CHILD session's status.
type ServerEvent_SessionStatusUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The session's new status.
	Status        v12.SessionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=pluggableharness.session.v1.SessionStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent_SessionStatusUpdate) Reset() {
	*x = ServerEvent_SessionStatusUpdate{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent_SessionStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent_SessionStatusUpdate) ProtoMessage() {}

func (x *ServerEvent_SessionStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent_SessionStatusUpdate.ProtoReflect.Descriptor instead.
func (*ServerEvent_SessionStatusUpdate) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{0, 14}
}

func (x *ServerEvent_SessionStatusUpdate) GetStatus() v12.SessionStatus {
	if x != nil {
		return x.Status
	}
	return v12.SessionStatus(0)
}

// UserMessage is ordinary chat input from the user.
type ClientEvent_UserMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message content, in emission order. MUST contain at least one
	// block.
	Content       []*v15.ContentBlock `protobuf:"bytes,2,rep,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_UserMessage) Reset() {
	*x = ClientEvent_UserMessage{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_UserMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_UserMessage) ProtoMessage() {}

func (x *ClientEvent_UserMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_UserMessage.ProtoReflect.Descriptor instead.
func (*ClientEvent_UserMessage) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ClientEvent_UserMessage) GetContent() []*v15.ContentBlock {
	if x != nil {
		return x.Content
	}
	return nil
}

// SlashCommand is a dispatched slash command invocation (frontend.md §5).
type ClientEvent_SlashCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The command name, without its leading slash.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The raw argument string following the command name.
	Args          string `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_SlashCommand) Reset() {
	*x = ClientEvent_SlashCommand{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_SlashCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_SlashCommand) ProtoMessage() {}

func (x *ClientEvent_SlashCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_SlashCommand.ProtoReflect.Descriptor instead.
func (*ClientEvent_SlashCommand) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ClientEvent_SlashCommand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientEvent_SlashCommand) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

// PlanDecision resolves a pending ServerEvent.PermissionRequest.
type ClientEvent_PlanDecision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The plan item being resolved, matching
	// ServerEvent.PermissionRequest.plan_item's id.
	PlanItemId string `protobuf:"bytes,1,opt,name=plan_item_id,json=planItemId,proto3" json:"plan_item_id,omitempty"`
	// The user's decision.
	Decision ClientDecision `protobuf:"varint,2,opt,name=decision,proto3,enum=pluggableharness.frontend.v1.ClientDecision" json:"decision,omitempty"`
	// When present, a user-edited replacement for the plan item's tool
	// input. The kernel MUST re-validate this against the tool's
	// input_schema (tool.md §6); an invalid correction is rejected as a
	// distinct error, not silently coerced.
	CorrectedInput *structpb.Struct `protobuf:"bytes,3,opt,name=corrected_input,json=correctedInput,proto3,oneof" json:"corrected_input,omitempty"`
	// How durably this decision applies beyond this one item — see
	// PlanDecisionScope.
	Scope         PlanDecisionScope `protobuf:"varint,4,opt,name=scope,proto3,enum=pluggableharness.frontend.v1.PlanDecisionScope" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_PlanDecision) Reset() {
	*x = ClientEvent_PlanDecision{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_PlanDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_PlanDecision) ProtoMessage() {}

func (x *ClientEvent_PlanDecision) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_PlanDecision.ProtoReflect.Descriptor instead.
func (*ClientEvent_PlanDecision) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ClientEvent_PlanDecision) GetPlanItemId() string {
	if x != nil {
		return x.PlanItemId
	}
	return ""
}

func (x *ClientEvent_PlanDecision) GetDecision() ClientDecision {
	if x != nil {
		return x.Decision
	}
	return ClientDecision_CLIENT_DECISION_UNSPECIFIED
}

func (x *ClientEvent_PlanDecision) GetCorrectedInput() *structpb.Struct {
	if x != nil {
		return x.CorrectedInput
	}
	return nil
}

func (x *ClientEvent_PlanDecision) GetScope() PlanDecisionScope {
	if x != nil {
		return x.Scope
	}
	return PlanDecisionScope_PLAN_DECISION_SCOPE_UNSPECIFIED
}

// InteractiveResponse resolves a pending ServerEvent.InteractiveRequest.
type ClientEvent_InteractiveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates to ServerEvent.InteractiveRequest.call_id.
	CallId string `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	// The user's response, becoming the interactive call's
	// ToolResult.payload.
	Response      *structpb.Struct `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_InteractiveResponse) Reset() {
	*x = ClientEvent_InteractiveResponse{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_InteractiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_InteractiveResponse) ProtoMessage() {}

func (x *ClientEvent_InteractiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_InteractiveResponse.ProtoReflect.Descriptor instead.
func (*ClientEvent_InteractiveResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 3}
}

func (x *ClientEvent_InteractiveResponse) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ClientEvent_InteractiveResponse) GetResponse() *structpb.Struct {
	if x != nil {
		return x.Response
	}
	return nil
}

// ActionTrigger is dispatched when a user activates a RenderNode's
// ActionNode (render/v1/types.proto's ActionNode, frontend.md §5.1). The kernel
// handles this identically to a direct_invoke slash command: the normal
// Invoke/plan-apply pipeline including policy evaluation, with no model
// turn.
type ClientEvent_ActionTrigger struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The originating ActionNode's id (render/v1/types.proto's ActionNode.id).
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The tool operation to invoke (tool.md §2 ToolSchema.name), echoed
	// unchanged from the originating ActionNode.tool_name.
	ToolName string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// The arguments to invoke it with, echoed unchanged from the
	// originating ActionNode.args.
	Args *structpb.Struct `protobuf:"bytes,3,opt,name=args,proto3" json:"args,omitempty"`
	// The declared name of the tool provider plugin `tool_name` belongs
	// to, echoed unchanged from the originating ActionNode.provider
	// (render/v1/types.proto) — tool_name is only unique per provider.
	Provider      string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_ActionTrigger) Reset() {
	*x = ClientEvent_ActionTrigger{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_ActionTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_ActionTrigger) ProtoMessage() {}

func (x *ClientEvent_ActionTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_ActionTrigger.ProtoReflect.Descriptor instead.
func (*ClientEvent_ActionTrigger) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 4}
}

func (x *ClientEvent_ActionTrigger) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClientEvent_ActionTrigger) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ClientEvent_ActionTrigger) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ClientEvent_ActionTrigger) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

// Interrupt carries no fields; it signals that the user wants to
// interrupt the current turn.
type ClientEvent_Interrupt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_Interrupt) Reset() {
	*x = ClientEvent_Interrupt{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_Interrupt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_Interrupt) ProtoMessage() {}

func (x *ClientEvent_Interrupt) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_Interrupt.ProtoReflect.Descriptor instead.
func (*ClientEvent_Interrupt) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 5}
}

// Hello MAY be sent as the first ClientEvent on a newly opened Attach
// stream, to assert the protocol version. Binding a session happens via
// the session-control variants, not via Hello.
type ClientEvent_Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The protocol version this frontend was built against.
	ProtocolVersion uint32 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientEvent_Hello) Reset() {
	*x = ClientEvent_Hello{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_Hello) ProtoMessage() {}

func (x *ClientEvent_Hello) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_Hello.ProtoReflect.Descriptor instead.
func (*ClientEvent_Hello) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 6}
}

func (x *ClientEvent_Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

// CreateSession creates a new session and auto-attaches this stream to
// it, per frontend.md §"Session lifecycle". Answered by
// ServerEvent.SessionCreated.
type ClientEvent_CreateSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-generated, echoed back on ServerEvent.request_id.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The agent.hcl profile to create the session under. Absent means
	// the kernel's configured default profile.
	Profile *string `protobuf:"bytes,2,opt,name=profile,proto3,oneof" json:"profile,omitempty"`
	// An initial user message to seed the session with, submitted as the
	// first turn once the session is created. Absent creates an empty
	// session awaiting the first ordinary user_message.
	InitialPrompt *string `protobuf:"bytes,3,opt,name=initial_prompt,json=initialPrompt,proto3,oneof" json:"initial_prompt,omitempty"`
	// The session's working directory. Absent means the kernel's own
	// working directory at creation time.
	WorkingDirectory *string `protobuf:"bytes,4,opt,name=working_directory,json=workingDirectory,proto3,oneof" json:"working_directory,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClientEvent_CreateSession) Reset() {
	*x = ClientEvent_CreateSession{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_CreateSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_CreateSession) ProtoMessage() {}

func (x *ClientEvent_CreateSession) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_CreateSession.ProtoReflect.Descriptor instead.
func (*ClientEvent_CreateSession) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 7}
}

func (x *ClientEvent_CreateSession) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientEvent_CreateSession) GetProfile() string {
	if x != nil && x.Profile != nil {
		return *x.Profile
	}
	return ""
}

func (x *ClientEvent_CreateSession) GetInitialPrompt() string {
	if x != nil && x.InitialPrompt != nil {
		return *x.InitialPrompt
	}
	return ""
}

func (x *ClientEvent_CreateSession) GetWorkingDirectory() string {
	if x != nil && x.WorkingDirectory != nil {
		return *x.WorkingDirectory
	}
	return ""
}

// AttachSession subscribes an existing session (live or terminal) onto
// this stream, triggering a backfill replay. Answered by
// ServerEvent.SessionAttached, bracketing a replay batch closed by
// ServerEvent.BackfillComplete.
type ClientEvent_AttachSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-generated, echoed back on ServerEvent.request_id.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The session to attach.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_AttachSession) Reset() {
	*x = ClientEvent_AttachSession{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_AttachSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_AttachSession) ProtoMessage() {}

func (x *ClientEvent_AttachSession) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_AttachSession.ProtoReflect.Descriptor instead.
func (*ClientEvent_AttachSession) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 8}
}

func (x *ClientEvent_AttachSession) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientEvent_AttachSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ResumeSession attaches a historical (possibly terminal) session, per
// frontend.md §"Resume and re-open semantics". A COMPLETED or
// CANCELLED session MAY be re-opened to SESSION_STATUS_RUNNING for new
// turns; a bound-exhausted (error_max_*) or FAILED session attaches
// replay-only — the kernel MUST reject a subsequent user_message
// against it with FRONTEND_ERROR_CATEGORY_SESSION_REPLAY_ONLY. Answered
// identically to AttachSession: SessionAttached bracketing a backfill
// batch.
type ClientEvent_ResumeSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-generated, echoed back on ServerEvent.request_id.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The session to resume.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_ResumeSession) Reset() {
	*x = ClientEvent_ResumeSession{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_ResumeSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_ResumeSession) ProtoMessage() {}

func (x *ClientEvent_ResumeSession) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_ResumeSession.ProtoReflect.Descriptor instead.
func (*ClientEvent_ResumeSession) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 9}
}

func (x *ClientEvent_ResumeSession) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientEvent_ResumeSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// DetachSession unsubscribes a session from this stream without
// affecting the session itself — other streams attached to the same
// session, and the session's own execution, are unaffected. Answered
// by ServerEvent.SessionDetached.
type ClientEvent_DetachSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-generated, echoed back on ServerEvent.request_id.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The session to detach.
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_DetachSession) Reset() {
	*x = ClientEvent_DetachSession{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_DetachSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_DetachSession) ProtoMessage() {}

func (x *ClientEvent_DetachSession) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_DetachSession.ProtoReflect.Descriptor instead.
func (*ClientEvent_DetachSession) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 10}
}

func (x *ClientEvent_DetachSession) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientEvent_DetachSession) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ListSessions requests the connection-scoped session summary list.
// Answered by ServerEvent.SessionList.
type ClientEvent_ListSessions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client-generated, echoed back on ServerEvent.request_id.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Restricts the result to sessions in this status. Absent means no
	// status filter.
	Status *v12.SessionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=pluggableharness.session.v1.SessionStatus,oneof" json:"status,omitempty"`
	// Restricts the result to children of this session. Absent means no
	// parent filter.
	ParentSessionId *string `protobuf:"bytes,3,opt,name=parent_session_id,json=parentSessionId,proto3,oneof" json:"parent_session_id,omitempty"`
	// True: only root sessions (no parent_session_id). False: all
	// sessions matching the other filters, at any depth.
	RootsOnly     bool `protobuf:"varint,4,opt,name=roots_only,json=rootsOnly,proto3" json:"roots_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent_ListSessions) Reset() {
	*x = ClientEvent_ListSessions{}
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent_ListSessions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent_ListSessions) ProtoMessage() {}

func (x *ClientEvent_ListSessions) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_events_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent_ListSessions.ProtoReflect.Descriptor instead.
func (*ClientEvent_ListSessions) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_events_proto_rawDescGZIP(), []int{1, 11}
}

func (x *ClientEvent_ListSessions) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ClientEvent_ListSessions) GetStatus() v12.SessionStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return v12.SessionStatus(0)
}

func (x *ClientEvent_ListSessions) GetParentSessionId() string {
	if x != nil && x.ParentSessionId != nil {
		return *x.ParentSessionId
	}
	return ""
}

func (x *ClientEvent_ListSessions) GetRootsOnly() bool {
	if x != nil {
		return x.RootsOnly
	}
	return false
}

var File_pluggableharness_frontend_v1_events_proto protoreflect.FileDescriptor

const file_pluggableharness_frontend_v1_events_proto_rawDesc = "" +
	"\n" +
	")pluggableharness/frontend/v1/events.proto\x12\x1cpluggableharness.frontend.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a'pluggableharness/content/v1/types.proto\x1a)pluggableharness/frontend/v1/errors.proto\x1a%pluggableharness/model/v1/types.proto\x1a$pluggableharness/plan/v1/types.proto\x1a&pluggableharness/render/v1/types.proto\x1a'pluggableharness/session/v1/types.proto\x1a,pluggableharness/slashcommand/v1/types.proto\"\xd1\x17\n" +
	"\vServerEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18d \x01(\tR\tsessionId\x12\"\n" +
	"\n" +
	"request_id\x18e \x01(\tH\x01R\trequestId\x88\x01\x01\x12Z\n" +
	"\fstream_delta\x18\x01 \x01(\v25.pluggableharness.frontend.v1.ServerEvent.StreamDeltaH\x00R\vstreamDelta\x12J\n" +
	"\x06render\x18\x02 \x01(\v20.pluggableharness.frontend.v1.ServerEvent.RenderH\x00R\x06render\x12l\n" +
	"\x12permission_request\x18\x03 \x01(\v2;.pluggableharness.frontend.v1.ServerEvent.PermissionRequestH\x00R\x11permissionRequest\x12T\n" +
	"\n" +
	"plan_ready\x18\x04 \x01(\v23.pluggableharness.frontend.v1.ServerEvent.PlanReadyH\x00R\tplanReady\x12o\n" +
	"\x13interactive_request\x18\x05 \x01(\v2<.pluggableharness.frontend.v1.ServerEvent.InteractiveRequestH\x00R\x12interactiveRequest\x12m\n" +
	"\x13session_tree_update\x18\x06 \x01(\v2;.pluggableharness.frontend.v1.ServerEvent.SessionTreeUpdateH\x00R\x11sessionTreeUpdate\x12G\n" +
	"\x05error\x18\a \x01(\v2/.pluggableharness.frontend.v1.ServerEvent.ErrorH\x00R\x05error\x12c\n" +
	"\x0fsession_created\x18\b \x01(\v28.pluggableharness.frontend.v1.ServerEvent.SessionCreatedH\x00R\x0esessionCreated\x12f\n" +
	"\x10session_attached\x18\t \x01(\v29.pluggableharness.frontend.v1.ServerEvent.SessionAttachedH\x00R\x0fsessionAttached\x12i\n" +
	"\x11backfill_complete\x18\n" +
	" \x01(\v2:.pluggableharness.frontend.v1.ServerEvent.BackfillCompleteH\x00R\x10backfillComplete\x12f\n" +
	"\x10session_detached\x18\v \x01(\v29.pluggableharness.frontend.v1.ServerEvent.SessionDetachedH\x00R\x0fsessionDetached\x12Z\n" +
	"\fsession_list\x18\f \x01(\v25.pluggableharness.frontend.v1.ServerEvent.SessionListH\x00R\vsessionList\x12v\n" +
	"\x16slash_command_registry\x18\x0e \x01(\v2>.pluggableharness.frontend.v1.ServerEvent.SlashCommandRegistryH\x00R\x14slashCommandRegistry\x12Z\n" +
	"\fusage_update\x18\x0f \x01(\v25.pluggableharness.frontend.v1.ServerEvent.UsageUpdateH\x00R\vusageUpdate\x12s\n" +
	"\x15session_status_update\x18\x10 \x01(\v2=.pluggableharness.frontend.v1.ServerEvent.SessionStatusUpdateH\x00R\x13sessionStatusUpdate\x1a>\n" +
	"\vStreamDelta\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x1aM\n" +
	"\x06Render\x12C\n" +
	"\acontent\x18\x01 \x01(\v2).pluggableharness.render.v1.PlacedContentR\acontent\x1aT\n" +
	"\x11PermissionRequest\x12?\n" +
	"\tplan_item\x18\x01 \x01(\v2\".pluggableharness.plan.v1.PlanItemR\bplanItem\x1a?\n" +
	"\tPlanReady\x122\n" +
	"\x04plan\x18\x01 \x01(\v2\x1e.pluggableharness.plan.v1.PlanR\x04plan\x1a\x8a\x01\n" +
	"\x12InteractiveRequest\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12>\n" +
	"\x06prompt\x18\x03 \x01(\v2&.pluggableharness.render.v1.RenderTreeR\x06prompt\x1a\xad\x01\n" +
	"\x11SessionTreeUpdate\x12*\n" +
	"\x11parent_session_id\x18\x01 \x01(\tR\x0fparentSessionId\x12(\n" +
	"\x10child_session_id\x18\x02 \x01(\tR\x0echildSessionId\x12B\n" +
	"\x06status\x18\x03 \x01(\x0e2*.pluggableharness.session.v1.SessionStatusR\x06status\x1aJ\n" +
	"\x05Error\x12A\n" +
	"\x05error\x18\x01 \x01(\v2+.pluggableharness.frontend.v1.FrontendErrorR\x05error\x1aN\n" +
	"\x0eSessionCreated\x12<\n" +
	"\x04info\x18\x01 \x01(\v2(.pluggableharness.session.v1.SessionInfoR\x04info\x1aO\n" +
	"\x0fSessionAttached\x12<\n" +
	"\x04info\x18\x01 \x01(\v2(.pluggableharness.session.v1.SessionInfoR\x04info\x1a7\n" +
	"\x10BackfillComplete\x12#\n" +
	"\rlast_sequence\x18\x01 \x01(\x03R\flastSequence\x1a\x11\n" +
	"\x0fSessionDetached\x1aS\n" +
	"\vSessionList\x12D\n" +
	"\bsessions\x18\x01 \x03(\v2(.pluggableharness.session.v1.SessionInfoR\bsessions\x1af\n" +
	"\x14SlashCommandRegistry\x12N\n" +
	"\bcommands\x18\x01 \x03(\v22.pluggableharness.slashcommand.v1.SlashCommandSpecR\bcommands\x1a\xc1\x01\n" +
	"\vUsageUpdate\x124\n" +
	"\x04turn\x18\x01 \x01(\v2 .pluggableharness.model.v1.UsageR\x04turn\x12.\n" +
	"\x13cumulative_cost_usd\x18\x02 \x01(\x01R\x11cumulativeCostUsd\x12\x1f\n" +
	"\vused_tokens\x18\x03 \x01(\x03R\n" +
	"usedTokens\x12+\n" +
	"\x11effective_ceiling\x18\x04 \x01(\x03R\x10effectiveCeiling\x1aY\n" +
	"\x13SessionStatusUpdate\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.pluggableharness.session.v1.SessionStatusR\x06statusB\a\n" +
	"\x05eventB\r\n" +
	"\v_request_idJ\x04\b\r\x10\x0eR\x0fsession_deleted\"\xd2\x14\n" +
	"\vClientEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18d \x01(\tR\tsessionId\x12Z\n" +
	"\fuser_message\x18\x01 \x01(\v25.pluggableharness.frontend.v1.ClientEvent.UserMessageH\x00R\vuserMessage\x12]\n" +
	"\rslash_command\x18\x02 \x01(\v26.pluggableharness.frontend.v1.ClientEvent.SlashCommandH\x00R\fslashCommand\x12]\n" +
	"\rplan_decision\x18\x03 \x01(\v26.pluggableharness.frontend.v1.ClientEvent.PlanDecisionH\x00R\fplanDecision\x12r\n" +
	"\x14interactive_response\x18\x04 \x01(\v2=.pluggableharness.frontend.v1.ClientEvent.InteractiveResponseH\x00R\x13interactiveResponse\x12`\n" +
	"\x0eaction_trigger\x18\x05 \x01(\v27.pluggableharness.frontend.v1.ClientEvent.ActionTriggerH\x00R\ractionTrigger\x12S\n" +
	"\tinterrupt\x18\x06 \x01(\v23.pluggableharness.frontend.v1.ClientEvent.InterruptH\x00R\tinterrupt\x12G\n" +
	"\x05hello\x18\a \x01(\v2/.pluggableharness.frontend.v1.ClientEvent.HelloH\x00R\x05hello\x12`\n" +
	"\x0ecreate_session\x18\b \x01(\v27.pluggableharness.frontend.v1.ClientEvent.CreateSessionH\x00R\rcreateSession\x12`\n" +
	"\x0eattach_session\x18\t \x01(\v27.pluggableharness.frontend.v1.ClientEvent.AttachSessionH\x00R\rattachSession\x12`\n" +
	"\x0eresume_session\x18\n" +
	" \x01(\v27.pluggableharness.frontend.v1.ClientEvent.ResumeSessionH\x00R\rresumeSession\x12`\n" +
	"\x0edetach_session\x18\v \x01(\v27.pluggableharness.frontend.v1.ClientEvent.DetachSessionH\x00R\rdetachSession\x12]\n" +
	"\rlist_sessions\x18\f \x01(\v26.pluggableharness.frontend.v1.ClientEvent.ListSessionsH\x00R\flistSessions\x1a^\n" +
	"\vUserMessage\x12C\n" +
	"\acontent\x18\x02 \x03(\v2).pluggableharness.content.v1.ContentBlockR\acontentJ\x04\b\x01\x10\x02R\x04text\x1a6\n" +
	"\fSlashCommand\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x01(\tR\x04args\x1a\x9c\x02\n" +
	"\fPlanDecision\x12 \n" +
	"\fplan_item_id\x18\x01 \x01(\tR\n" +
	"planItemId\x12H\n" +
	"\bdecision\x18\x02 \x01(\x0e2,.pluggableharness.frontend.v1.ClientDecisionR\bdecision\x12E\n" +
	"\x0fcorrected_input\x18\x03 \x01(\v2\x17.google.protobuf.StructH\x00R\x0ecorrectedInput\x88\x01\x01\x12E\n" +
	"\x05scope\x18\x04 \x01(\x0e2/.pluggableharness.frontend.v1.PlanDecisionScopeR\x05scopeB\x12\n" +
	"\x10_corrected_input\x1ac\n" +
	"\x13InteractiveResponse\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x123\n" +
	"\bresponse\x18\x02 \x01(\v2\x17.google.protobuf.StructR\bresponse\x1a\x8e\x01\n" +
	"\rActionTrigger\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12+\n" +
	"\x04args\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04args\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x1a\v\n" +
	"\tInterrupt\x1a2\n" +
	"\x05Hello\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x1a\xe0\x01\n" +
	"\rCreateSession\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\aprofile\x18\x02 \x01(\tH\x00R\aprofile\x88\x01\x01\x12*\n" +
	"\x0einitial_prompt\x18\x03 \x01(\tH\x01R\rinitialPrompt\x88\x01\x01\x120\n" +
	"\x11working_directory\x18\x04 \x01(\tH\x02R\x10workingDirectory\x88\x01\x01B\n" +
	"\n" +
	"\b_profileB\x11\n" +
	"\x0f_initial_promptB\x14\n" +
	"\x12_working_directory\x1aM\n" +
	"\rAttachSession\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x1aM\n" +
	"\rResumeSession\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x1aM\n" +
	"\rDetachSession\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x1a\xe7\x01\n" +
	"\fListSessions\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12G\n" +
	"\x06status\x18\x02 \x01(\x0e2*.pluggableharness.session.v1.SessionStatusH\x00R\x06status\x88\x01\x01\x12/\n" +
	"\x11parent_session_id\x18\x03 \x01(\tH\x01R\x0fparentSessionId\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"roots_only\x18\x04 \x01(\bR\trootsOnlyB\t\n" +
	"\a_statusB\x14\n" +
	"\x12_parent_session_idB\a\n" +
	"\x05event*f\n" +
	"\x0eClientDecision\x12\x1f\n" +
	"\x1bCLIENT_DECISION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CLIENT_DECISION_ALLOW\x10\x01\x12\x18\n" +
	"\x14CLIENT_DECISION_DENY\x10\x02*\x97\x01\n" +
	"\x11PlanDecisionScope\x12#\n" +
	"\x1fPLAN_DECISION_SCOPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18PLAN_DECISION_SCOPE_ONCE\x10\x01\x12\x1f\n" +
	"\x1bPLAN_DECISION_SCOPE_SESSION\x10\x02\x12\x1e\n" +
	"\x1aPLAN_DECISION_SCOPE_ALWAYS\x10\x03BDZBgithub.com/pluggableharness/agent/pkg/frontend/proto/v1;frontendv1b\x06proto3"

var (
	file_pluggableharness_frontend_v1_events_proto_rawDescOnce sync.Once
	file_pluggableharness_frontend_v1_events_proto_rawDescData []byte
)

func file_pluggableharness_frontend_v1_events_proto_rawDescGZIP() []byte {
	file_pluggableharness_frontend_v1_events_proto_rawDescOnce.Do(func() {
		file_pluggableharness_frontend_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_frontend_v1_events_proto_rawDesc), len(file_pluggableharness_frontend_v1_events_proto_rawDesc)))
	})
	return file_pluggableharness_frontend_v1_events_proto_rawDescData
}

var file_pluggableharness_frontend_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pluggableharness_frontend_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_pluggableharness_frontend_v1_events_proto_goTypes = []any{
	(ClientDecision)(0),                      // 0: pluggableharness.frontend.v1.ClientDecision
	(PlanDecisionScope)(0),                   // 1: pluggableharness.frontend.v1.PlanDecisionScope
	(*ServerEvent)(nil),                      // 2: pluggableharness.frontend.v1.ServerEvent
	(*ClientEvent)(nil),                      // 3: pluggableharness.frontend.v1.ClientEvent
	(*ServerEvent_StreamDelta)(nil),          // 4: pluggableharness.frontend.v1.ServerEvent.StreamDelta
	(*ServerEvent_Render)(nil),               // 5: pluggableharness.frontend.v1.ServerEvent.Render
	(*ServerEvent_PermissionRequest)(nil),    // 6: pluggableharness.frontend.v1.ServerEvent.PermissionRequest
	(*ServerEvent_PlanReady)(nil),            // 7: pluggableharness.frontend.v1.ServerEvent.PlanReady
	(*ServerEvent_InteractiveRequest)(nil),   // 8: pluggableharness.frontend.v1.ServerEvent.InteractiveRequest
	(*ServerEvent_SessionTreeUpdate)(nil),    // 9: pluggableharness.frontend.v1.ServerEvent.SessionTreeUpdate
	(*ServerEvent_Error)(nil),                // 10: pluggableharness.frontend.v1.ServerEvent.Error
	(*ServerEvent_SessionCreated)(nil),       // 11: pluggableharness.frontend.v1.ServerEvent.SessionCreated
	(*ServerEvent_SessionAttached)(nil),      // 12: pluggableharness.frontend.v1.ServerEvent.SessionAttached
	(*ServerEvent_BackfillComplete)(nil),     // 13: pluggableharness.frontend.v1.ServerEvent.BackfillComplete
	(*ServerEvent_SessionDetached)(nil),      // 14: pluggableharness.frontend.v1.ServerEvent.SessionDetached
	(*ServerEvent_SessionList)(nil),          // 15: pluggableharness.frontend.v1.ServerEvent.SessionList
	(*ServerEvent_SlashCommandRegistry)(nil), // 16: pluggableharness.frontend.v1.ServerEvent.SlashCommandRegistry
	(*ServerEvent_UsageUpdate)(nil),          // 17: pluggableharness.frontend.v1.ServerEvent.UsageUpdate
	(*ServerEvent_SessionStatusUpdate)(nil),  // 18: pluggableharness.frontend.v1.ServerEvent.SessionStatusUpdate
	(*ClientEvent_UserMessage)(nil),          // 19: pluggableharness.frontend.v1.ClientEvent.UserMessage
	(*ClientEvent_SlashCommand)(nil),         // 20: pluggableharness.frontend.v1.ClientEvent.SlashCommand
	(*ClientEvent_PlanDecision)(nil),         // 21: pluggableharness.frontend.v1.ClientEvent.PlanDecision
	(*ClientEvent_InteractiveResponse)(nil),  // 22: pluggableharness.frontend.v1.ClientEvent.InteractiveResponse
	(*ClientEvent_ActionTrigger)(nil),        // 23: pluggableharness.frontend.v1.ClientEvent.ActionTrigger
	(*ClientEvent_Interrupt)(nil),            // 24: pluggableharness.frontend.v1.ClientEvent.Interrupt
	(*ClientEvent_Hello)(nil),                // 25: pluggableharness.frontend.v1.ClientEvent.Hello
	(*ClientEvent_CreateSession)(nil),        // 26: pluggableharness.frontend.v1.ClientEvent.CreateSession
	(*ClientEvent_AttachSession)(nil),        // 27: pluggableharness.frontend.v1.ClientEvent.AttachSession
	(*ClientEvent_ResumeSession)(nil),        // 28: pluggableharness.frontend.v1.ClientEvent.ResumeSession
	(*ClientEvent_DetachSession)(nil),        // 29: pluggableharness.frontend.v1.ClientEvent.DetachSession
	(*ClientEvent_ListSessions)(nil),         // 30: pluggableharness.frontend.v1.ClientEvent.ListSessions
	(*v1.PlacedContent)(nil),                 // 31: pluggableharness.render.v1.PlacedContent
	(*v11.PlanItem)(nil),                     // 32: pluggableharness.plan.v1.PlanItem
	(*v11.Plan)(nil),                         // 33: pluggableharness.plan.v1.Plan
	(*v1.RenderTree)(nil),                    // 34: pluggableharness.render.v1.RenderTree
	(v12.SessionStatus)(0),                   // 35: pluggableharness.session.v1.SessionStatus
	(*FrontendError)(nil),                    // 36: pluggableharness.frontend.v1.FrontendError
	(*v12.SessionInfo)(nil),                  // 37: pluggableharness.session.v1.SessionInfo
	(*v13.SlashCommandSpec)(nil),             // 38: pluggableharness.slashcommand.v1.SlashCommandSpec
	(*v14.Usage)(nil),                        // 39: pluggableharness.model.v1.Usage
	(*v15.ContentBlock)(nil),                 // 40: pluggableharness.content.v1.ContentBlock
	(*structpb.Struct)(nil),                  // 41: google.protobuf.Struct
}
var file_pluggableharness_frontend_v1_events_proto_depIdxs = []int32{
	4,  // 0: pluggableharness.frontend.v1.ServerEvent.stream_delta:type_name -> pluggableharness.frontend.v1.ServerEvent.StreamDelta
	5,  // 1: pluggableharness.frontend.v1.ServerEvent.render:type_name -> pluggableharness.frontend.v1.ServerEvent.Render
	6,  // 2: pluggableharness.frontend.v1.ServerEvent.permission_request:type_name -> pluggableharness.frontend.v1.ServerEvent.PermissionRequest
	7,  // 3: pluggableharness.frontend.v1.ServerEvent.plan_ready:type_name -> pluggableharness.frontend.v1.ServerEvent.PlanReady
	8,  // 4: pluggableharness.frontend.v1.ServerEvent.interactive_request:type_name -> pluggableharness.frontend.v1.ServerEvent.InteractiveRequest
	9,  // 5: pluggableharness.frontend.v1.ServerEvent.session_tree_update:type_name -> pluggableharness.frontend.v1.ServerEvent.SessionTreeUpdate
	10, // 6: pluggableharness.frontend.v1.ServerEvent.error:type_name -> pluggableharness.frontend.v1.ServerEvent.Error
	11, // 7: pluggableharness.frontend.v1.ServerEvent.session_created:type_name -> pluggableharness.frontend.v1.ServerEvent.SessionCreated
	12, // 8: pluggableharness.frontend.v1.ServerEvent.session_attached:type_name -> pluggableharness.frontend.v1.ServerEvent.SessionAttached
	13, // 9: pluggableharness.frontend.v1.ServerEvent.backfill_complete:type_name -> pluggableharness.frontend.v1.ServerEvent.BackfillComplete
	14, // 10: pluggableharness.frontend.v1.ServerEvent.session_detached:type_name -> pluggableharness.frontend.v1.ServerEvent.SessionDetached
	15, // 11: pluggableharness.frontend.v1.ServerEvent.session_list:type_name -> pluggableharness.frontend.v1.ServerEvent.SessionList
	16, // 12: pluggableharness.frontend.v1.ServerEvent.slash_command_registry:type_name -> pluggableharness.frontend.v1.ServerEvent.SlashCommandRegistry
	17, // 13: pluggableharness.frontend.v1.ServerEvent.usage_update:type_name -> pluggableharness.frontend.v1.ServerEvent.UsageUpdate
	18, // 14: pluggableharness.frontend.v1.ServerEvent.session_status_update:type_name -> pluggableharness.frontend.v1.ServerEvent.SessionStatusUpdate
	19, // 15: pluggableharness.frontend.v1.ClientEvent.user_message:type_name -> pluggableharness.frontend.v1.ClientEvent.UserMessage
	20, // 16: pluggableharness.frontend.v1.ClientEvent.slash_command:type_name -> pluggableharness.frontend.v1.ClientEvent.SlashCommand
	21, // 17: pluggableharness.frontend.v1.ClientEvent.plan_decision:type_name -> pluggableharness.frontend.v1.ClientEvent.PlanDecision
	22, // 18: pluggableharness.frontend.v1.ClientEvent.interactive_response:type_name -> pluggableharness.frontend.v1.ClientEvent.InteractiveResponse
	23, // 19: pluggableharness.frontend.v1.ClientEvent.action_trigger:type_name -> pluggableharness.frontend.v1.ClientEvent.ActionTrigger
	24, // 20: pluggableharness.frontend.v1.ClientEvent.interrupt:type_name -> pluggableharness.frontend.v1.ClientEvent.Interrupt
	25, // 21: pluggableharness.frontend.v1.ClientEvent.hello:type_name -> pluggableharness.frontend.v1.ClientEvent.Hello
	26, // 22: pluggableharness.frontend.v1.ClientEvent.create_session:type_name -> pluggableharness.frontend.v1.ClientEvent.CreateSession
	27, // 23: pluggableharness.frontend.v1.ClientEvent.attach_session:type_name -> pluggableharness.frontend.v1.ClientEvent.AttachSession
	28, // 24: pluggableharness.frontend.v1.ClientEvent.resume_session:type_name -> pluggableharness.frontend.v1.ClientEvent.ResumeSession
	29, // 25: pluggableharness.frontend.v1.ClientEvent.detach_session:type_name -> pluggableharness.frontend.v1.ClientEvent.DetachSession
	30, // 26: pluggableharness.frontend.v1.ClientEvent.list_sessions:type_name -> pluggableharness.frontend.v1.ClientEvent.ListSessions
	31, // 27: pluggableharness.frontend.v1.ServerEvent.Render.content:type_name -> pluggableharness.render.v1.PlacedContent
	32, // 28: pluggableharness.frontend.v1.ServerEvent.PermissionRequest.plan_item:type_name -> pluggableharness.plan.v1.PlanItem
	33, // 29: pluggableharness.frontend.v1.ServerEvent.PlanReady.plan:type_name -> pluggableharness.plan.v1.Plan
	34, // 30: pluggableharness.frontend.v1.ServerEvent.InteractiveRequest.prompt:type_name -> pluggableharness.render.v1.RenderTree
	35, // 31: pluggableharness.frontend.v1.ServerEvent.SessionTreeUpdate.status:type_name -> pluggableharness.session.v1.SessionStatus
	36, // 32: pluggableharness.frontend.v1.ServerEvent.Error.error:type_name -> pluggableharness.frontend.v1.FrontendError
	37, // 33: pluggableharness.frontend.v1.ServerEvent.SessionCreated.info:type_name -> pluggableharness.session.v1.SessionInfo
	37, // 34: pluggableharness.frontend.v1.ServerEvent.SessionAttached.info:type_name -> pluggableharness.session.v1.SessionInfo
	37, // 35: pluggableharness.frontend.v1.ServerEvent.SessionList.sessions:type_name -> pluggableharness.session.v1.SessionInfo
	38, // 36: pluggableharness.frontend.v1.ServerEvent.SlashCommandRegistry.commands:type_name -> pluggableharness.slashcommand.v1.SlashCommandSpec
	39, // 37: pluggableharness.frontend.v1.ServerEvent.UsageUpdate.turn:type_name -> pluggableharness.model.v1.Usage
	35, // 38: pluggableharness.frontend.v1.ServerEvent.SessionStatusUpdate.status:type_name -> pluggableharness.session.v1.SessionStatus
	40, // 39: pluggableharness.frontend.v1.ClientEvent.UserMessage.content:type_name -> pluggableharness.content.v1.ContentBlock
	0,  // 40: pluggableharness.frontend.v1.ClientEvent.PlanDecision.decision:type_name -> pluggableharness.frontend.v1.ClientDecision
	41, // 41: pluggableharness.frontend.v1.ClientEvent.PlanDecision.corrected_input:type_name -> google.protobuf.Struct
	1,  // 42: pluggableharness.frontend.v1.ClientEvent.PlanDecision.scope:type_name -> pluggableharness.frontend.v1.PlanDecisionScope
	41, // 43: pluggableharness.frontend.v1.ClientEvent.InteractiveResponse.response:type_name -> google.protobuf.Struct
	41, // 44: pluggableharness.frontend.v1.ClientEvent.ActionTrigger.args:type_name -> google.protobuf.Struct
	35, // 45: pluggableharness.frontend.v1.ClientEvent.ListSessions.status:type_name -> pluggableharness.session.v1.SessionStatus
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_pluggableharness_frontend_v1_events_proto_init() }
func file_pluggableharness_frontend_v1_events_proto_init() {
	if File_pluggableharness_frontend_v1_events_proto != nil {
		return
	}
	file_pluggableharness_frontend_v1_errors_proto_init()
	file_pluggableharness_frontend_v1_events_proto_msgTypes[0].OneofWrappers = []any{
		(*ServerEvent_StreamDelta_)(nil),
		(*ServerEvent_Render_)(nil),
		(*ServerEvent_PermissionRequest_)(nil),
		(*ServerEvent_PlanReady_)(nil),
		(*ServerEvent_InteractiveRequest_)(nil),
		(*ServerEvent_SessionTreeUpdate_)(nil),
		(*ServerEvent_Error_)(nil),
		(*ServerEvent_SessionCreated_)(nil),
		(*ServerEvent_SessionAttached_)(nil),
		(*ServerEvent_BackfillComplete_)(nil),
		(*ServerEvent_SessionDetached_)(nil),
		(*ServerEvent_SessionList_)(nil),
		(*ServerEvent_SlashCommandRegistry_)(nil),
		(*ServerEvent_UsageUpdate_)(nil),
		(*ServerEvent_SessionStatusUpdate_)(nil),
	}
	file_pluggableharness_frontend_v1_events_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientEvent_UserMessage_)(nil),
		(*ClientEvent_SlashCommand_)(nil),
		(*ClientEvent_PlanDecision_)(nil),
		(*ClientEvent_InteractiveResponse_)(nil),
		(*ClientEvent_ActionTrigger_)(nil),
		(*ClientEvent_Interrupt_)(nil),
		(*ClientEvent_Hello_)(nil),
		(*ClientEvent_CreateSession_)(nil),
		(*ClientEvent_AttachSession_)(nil),
		(*ClientEvent_ResumeSession_)(nil),
		(*ClientEvent_DetachSession_)(nil),
		(*ClientEvent_ListSessions_)(nil),
	}
	file_pluggableharness_frontend_v1_events_proto_msgTypes[19].OneofWrappers = []any{}
	file_pluggableharness_frontend_v1_events_proto_msgTypes[24].OneofWrappers = []any{}
	file_pluggableharness_frontend_v1_events_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_frontend_v1_events_proto_rawDesc), len(file_pluggableharness_frontend_v1_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_frontend_v1_events_proto_goTypes,
		DependencyIndexes: file_pluggableharness_frontend_v1_events_proto_depIdxs,
		EnumInfos:         file_pluggableharness_frontend_v1_events_proto_enumTypes,
		MessageInfos:      file_pluggableharness_frontend_v1_events_proto_msgTypes,
	}.Build()
	File_pluggableharness_frontend_v1_events_proto = out.File
	file_pluggableharness_frontend_v1_events_proto_goTypes = nil
	file_pluggableharness_frontend_v1_events_proto_depIdxs = nil
}
