// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/frontend/v1/rpc_response.proto

package frontendv1

import (
	v1 "github.com/pluggableharness/agent/pkg/common/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCapabilitiesResponse wraps FrontendCapabilities for the RPC signature,
// per this repo's per-RPC envelope convention (.claude/rules/proto.md).
type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *FrontendCapabilities  `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_pluggableharness_frontend_v1_rpc_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_rpc_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_rpc_response_proto_rawDescGZIP(), []int{0}
}

func (x *GetCapabilitiesResponse) GetCapabilities() *FrontendCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// ConfigureResponse is empty on success. Configuration errors surface as a
// gRPC status carrying a FrontendError in its structured detail
// (.claude/rules/grpc.md), not as an in-band field on this message.
type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_pluggableharness_frontend_v1_rpc_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_rpc_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_rpc_response_proto_rawDescGZIP(), []int{1}
}

// DescribeResponse reports this plugin build's own identity, obtained
// directly from the running process rather than a lock-file row —
// configuration/lock-file.md's "dev_overrides and identity without a lock
// entry".
type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Producer      *v1.ProducerRef        `protobuf:"bytes,1,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_pluggableharness_frontend_v1_rpc_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_frontend_v1_rpc_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_frontend_v1_rpc_response_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeResponse) GetProducer() *v1.ProducerRef {
	if x != nil {
		return x.Producer
	}
	return nil
}

var File_pluggableharness_frontend_v1_rpc_response_proto protoreflect.FileDescriptor

const file_pluggableharness_frontend_v1_rpc_response_proto_rawDesc = "" +
	"\n" +
	"/pluggableharness/frontend/v1/rpc_response.proto\x12\x1cpluggableharness.frontend.v1\x1a&pluggableharness/common/v1/types.proto\x1a(pluggableharness/frontend/v1/types.proto\"q\n" +
	"\x17GetCapabilitiesResponse\x12V\n" +
	"\fcapabilities\x18\x01 \x01(\v22.pluggableharness.frontend.v1.FrontendCapabilitiesR\fcapabilities\"\x13\n" +
	"\x11ConfigureResponse\"W\n" +
	"\x10DescribeResponse\x12C\n" +
	"\bproducer\x18\x01 \x01(\v2'.pluggableharness.common.v1.ProducerRefR\bproducerBDZBgithub.com/pluggableharness/agent/pkg/frontend/proto/v1;frontendv1b\x06proto3"

var (
	file_pluggableharness_frontend_v1_rpc_response_proto_rawDescOnce sync.Once
	file_pluggableharness_frontend_v1_rpc_response_proto_rawDescData []byte
)

func file_pluggableharness_frontend_v1_rpc_response_proto_rawDescGZIP() []byte {
	file_pluggableharness_frontend_v1_rpc_response_proto_rawDescOnce.Do(func() {
		file_pluggableharness_frontend_v1_rpc_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_frontend_v1_rpc_response_proto_rawDesc), len(file_pluggableharness_frontend_v1_rpc_response_proto_rawDesc)))
	})
	return file_pluggableharness_frontend_v1_rpc_response_proto_rawDescData
}

var file_pluggableharness_frontend_v1_rpc_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pluggableharness_frontend_v1_rpc_response_proto_goTypes = []any{
	(*GetCapabilitiesResponse)(nil), // 0: pluggableharness.frontend.v1.GetCapabilitiesResponse
	(*ConfigureResponse)(nil),       // 1: pluggableharness.frontend.v1.ConfigureResponse
	(*DescribeResponse)(nil),        // 2: pluggableharness.frontend.v1.DescribeResponse
	(*FrontendCapabilities)(nil),    // 3: pluggableharness.frontend.v1.FrontendCapabilities
	(*v1.ProducerRef)(nil),          // 4: pluggableharness.common.v1.ProducerRef
}
var file_pluggableharness_frontend_v1_rpc_response_proto_depIdxs = []int32{
	3, // 0: pluggableharness.frontend.v1.GetCapabilitiesResponse.capabilities:type_name -> pluggableharness.frontend.v1.FrontendCapabilities
	4, // 1: pluggableharness.frontend.v1.DescribeResponse.producer:type_name -> pluggableharness.common.v1.ProducerRef
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pluggableharness_frontend_v1_rpc_response_proto_init() }
func file_pluggableharness_frontend_v1_rpc_response_proto_init() {
	if File_pluggableharness_frontend_v1_rpc_response_proto != nil {
		return
	}
	file_pluggableharness_frontend_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_frontend_v1_rpc_response_proto_rawDesc), len(file_pluggableharness_frontend_v1_rpc_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_frontend_v1_rpc_response_proto_goTypes,
		DependencyIndexes: file_pluggableharness_frontend_v1_rpc_response_proto_depIdxs,
		MessageInfos:      file_pluggableharness_frontend_v1_rpc_response_proto_msgTypes,
	}.Build()
	File_pluggableharness_frontend_v1_rpc_response_proto = out.File
	file_pluggableharness_frontend_v1_rpc_response_proto_goTypes = nil
	file_pluggableharness_frontend_v1_rpc_response_proto_depIdxs = nil
}
