// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/slashcommand/v1/rpc_request.proto

package slashcommandv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCapabilitiesRequest carries no fields — GetCapabilities takes no
// parameters.
type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescGZIP(), []int{0}
}

// ConfigureRequest wraps this provider's already-decoded agent.hcl
// config.
type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The provider-specific config, decoded from agent.hcl via the
	// schema-to-cty bridge before crossing the wire.
	Config        *structpb.Struct `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// InvokeRequest wraps the call to execute. A thin per-RPC envelope
// around SlashCommandCall, which keeps its own rich structure
// independent of the RPC signature.
type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The call to execute.
	Call          *SlashCommandCall `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeRequest) GetCall() *SlashCommandCall {
	if x != nil {
		return x.Call
	}
	return nil
}

// RenderRequest carries the opaque payload to render. See grpc.md's
// Emit->Render->Paint carve-out for why this field stays `bytes` rather
// than a strongly-typed message.
type RenderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The opaque emitted payload to render.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// The schema version the payload was emitted under, per
	// ../frontend/render-tree.md#schema-versioning. Lets a Render
	// implementation decode a payload emitted by an older build of this
	// same plugin.
	SchemaVersion string `protobuf:"bytes,2,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescGZIP(), []int{3}
}

func (x *RenderRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RenderRequest) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

// PreviewRequest wraps the call to describe, per
// slashcommand/protocol.md#preview.
type PreviewRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The call Preview describes a dry run of. Same shape as an Invoke
	// request; Preview MUST NOT execute it.
	Call          *SlashCommandCall `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRequest) Reset() {
	*x = PreviewRequest{}
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRequest) ProtoMessage() {}

func (x *PreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRequest.ProtoReflect.Descriptor instead.
func (*PreviewRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescGZIP(), []int{4}
}

func (x *PreviewRequest) GetCall() *SlashCommandCall {
	if x != nil {
		return x.Call
	}
	return nil
}

// DescribeRequest carries no fields — Describe takes no parameters.
type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescGZIP(), []int{5}
}

var File_pluggableharness_slashcommand_v1_rpc_request_proto protoreflect.FileDescriptor

const file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDesc = "" +
	"\n" +
	"2pluggableharness/slashcommand/v1/rpc_request.proto\x12 pluggableharness.slashcommand.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a,pluggableharness/slashcommand/v1/types.proto\"\x18\n" +
	"\x16GetCapabilitiesRequest\"C\n" +
	"\x10ConfigureRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\"W\n" +
	"\rInvokeRequest\x12F\n" +
	"\x04call\x18\x01 \x01(\v22.pluggableharness.slashcommand.v1.SlashCommandCallR\x04call\"P\n" +
	"\rRenderRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12%\n" +
	"\x0eschema_version\x18\x02 \x01(\tR\rschemaVersion\"X\n" +
	"\x0ePreviewRequest\x12F\n" +
	"\x04call\x18\x01 \x01(\v22.pluggableharness.slashcommand.v1.SlashCommandCallR\x04call\"\x11\n" +
	"\x0fDescribeRequestBLZJgithub.com/pluggableharness/agent/pkg/slashcommand/proto/v1;slashcommandv1b\x06proto3"

var (
	file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescOnce sync.Once
	file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescData []byte
)

func file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescGZIP() []byte {
	file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescOnce.Do(func() {
		file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDesc), len(file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDesc)))
	})
	return file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDescData
}

var file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pluggableharness_slashcommand_v1_rpc_request_proto_goTypes = []any{
	(*GetCapabilitiesRequest)(nil), // 0: pluggableharness.slashcommand.v1.GetCapabilitiesRequest
	(*ConfigureRequest)(nil),       // 1: pluggableharness.slashcommand.v1.ConfigureRequest
	(*InvokeRequest)(nil),          // 2: pluggableharness.slashcommand.v1.InvokeRequest
	(*RenderRequest)(nil),          // 3: pluggableharness.slashcommand.v1.RenderRequest
	(*PreviewRequest)(nil),         // 4: pluggableharness.slashcommand.v1.PreviewRequest
	(*DescribeRequest)(nil),        // 5: pluggableharness.slashcommand.v1.DescribeRequest
	(*structpb.Struct)(nil),        // 6: google.protobuf.Struct
	(*SlashCommandCall)(nil),       // 7: pluggableharness.slashcommand.v1.SlashCommandCall
}
var file_pluggableharness_slashcommand_v1_rpc_request_proto_depIdxs = []int32{
	6, // 0: pluggableharness.slashcommand.v1.ConfigureRequest.config:type_name -> google.protobuf.Struct
	7, // 1: pluggableharness.slashcommand.v1.InvokeRequest.call:type_name -> pluggableharness.slashcommand.v1.SlashCommandCall
	7, // 2: pluggableharness.slashcommand.v1.PreviewRequest.call:type_name -> pluggableharness.slashcommand.v1.SlashCommandCall
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pluggableharness_slashcommand_v1_rpc_request_proto_init() }
func file_pluggableharness_slashcommand_v1_rpc_request_proto_init() {
	if File_pluggableharness_slashcommand_v1_rpc_request_proto != nil {
		return
	}
	file_pluggableharness_slashcommand_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDesc), len(file_pluggableharness_slashcommand_v1_rpc_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_slashcommand_v1_rpc_request_proto_goTypes,
		DependencyIndexes: file_pluggableharness_slashcommand_v1_rpc_request_proto_depIdxs,
		MessageInfos:      file_pluggableharness_slashcommand_v1_rpc_request_proto_msgTypes,
	}.Build()
	File_pluggableharness_slashcommand_v1_rpc_request_proto = out.File
	file_pluggableharness_slashcommand_v1_rpc_request_proto_goTypes = nil
	file_pluggableharness_slashcommand_v1_rpc_request_proto_depIdxs = nil
}
