// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/tool/v1/events.proto

package toolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OutputStream distinguishes which underlying stream an OutputChunk came
// from.
type OutputStream int32

const (
	// Zero value. Never valid for a real chunk; its presence on the wire
	// means a caller forgot to set the field.
	OutputStream_OUTPUT_STREAM_UNSPECIFIED OutputStream = 0
	// Standard output.
	OutputStream_OUTPUT_STREAM_STDOUT OutputStream = 1
	// Standard error.
	OutputStream_OUTPUT_STREAM_STDERR OutputStream = 2
)

// Enum value maps for OutputStream.
var (
	OutputStream_name = map[int32]string{
		0: "OUTPUT_STREAM_UNSPECIFIED",
		1: "OUTPUT_STREAM_STDOUT",
		2: "OUTPUT_STREAM_STDERR",
	}
	OutputStream_value = map[string]int32{
		"OUTPUT_STREAM_UNSPECIFIED": 0,
		"OUTPUT_STREAM_STDOUT":      1,
		"OUTPUT_STREAM_STDERR":      2,
	}
)

func (x OutputStream) Enum() *OutputStream {
	p := new(OutputStream)
	*p = x
	return p
}

func (x OutputStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputStream) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_tool_v1_events_proto_enumTypes[0].Descriptor()
}

func (OutputStream) Type() protoreflect.EnumType {
	return &file_pluggableharness_tool_v1_events_proto_enumTypes[0]
}

func (x OutputStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputStream.Descriptor instead.
func (OutputStream) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_events_proto_rawDescGZIP(), []int{0}
}

// InvokeResponse wraps one message in the stream Invoke returns. A thin
// per-RPC envelope around ToolEvent, which keeps its own rich structure
// independent of the RPC signature.
type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event.
	Event         *ToolEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeResponse) GetEvent() *ToolEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// ToolEvent is one message in the stream Invoke returns, per tool.md §4.
// Exactly one of `result`/`error` closes the stream; `output_chunk`,
// `progress`, and `partial_result` MAY each appear zero or more times
// before it; `exit_status` MAY appear at most once. The relative order of
// `output_chunk` events MUST be preserved by the transport.
type ToolEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ToolEvent_OutputChunk_
	//	*ToolEvent_Progress_
	//	*ToolEvent_PartialResult_
	//	*ToolEvent_ExitStatus_
	//	*ToolEvent_Result
	//	*ToolEvent_Error
	Event         isToolEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent) Reset() {
	*x = ToolEvent{}
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent) ProtoMessage() {}

func (x *ToolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent.ProtoReflect.Descriptor instead.
func (*ToolEvent) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *ToolEvent) GetEvent() isToolEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ToolEvent) GetOutputChunk() *ToolEvent_OutputChunk {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_OutputChunk_); ok {
			return x.OutputChunk
		}
	}
	return nil
}

func (x *ToolEvent) GetProgress() *ToolEvent_Progress {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Progress_); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ToolEvent) GetPartialResult() *ToolEvent_PartialResult {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_PartialResult_); ok {
			return x.PartialResult
		}
	}
	return nil
}

func (x *ToolEvent) GetExitStatus() *ToolEvent_ExitStatus {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_ExitStatus_); ok {
			return x.ExitStatus
		}
	}
	return nil
}

func (x *ToolEvent) GetResult() *ToolResult {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ToolEvent) GetError() *ToolError {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isToolEvent_Event interface {
	isToolEvent_Event()
}

type ToolEvent_OutputChunk_ struct {
	// Incremental raw output from a process-backed operation.
	OutputChunk *ToolEvent_OutputChunk `protobuf:"bytes,1,opt,name=output_chunk,json=outputChunk,proto3,oneof"`
}

type ToolEvent_Progress_ struct {
	// A human-readable progress update.
	Progress *ToolEvent_Progress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type ToolEvent_PartialResult_ struct {
	// Incremental structured output, e.g. search hits as they're found.
	PartialResult *ToolEvent_PartialResult `protobuf:"bytes,3,opt,name=partial_result,json=partialResult,proto3,oneof"`
}

type ToolEvent_ExitStatus_ struct {
	// The exit status of a process-backed operation's child process.
	ExitStatus *ToolEvent_ExitStatus `protobuf:"bytes,4,opt,name=exit_status,json=exitStatus,proto3,oneof"`
}

type ToolEvent_Result struct {
	// The terminal, successful result of this call.
	Result *ToolResult `protobuf:"bytes,5,opt,name=result,proto3,oneof"`
}

type ToolEvent_Error struct {
	// The terminal, failed result of this call.
	Error *ToolError `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*ToolEvent_OutputChunk_) isToolEvent_Event() {}

func (*ToolEvent_Progress_) isToolEvent_Event() {}

func (*ToolEvent_PartialResult_) isToolEvent_Event() {}

func (*ToolEvent_ExitStatus_) isToolEvent_Event() {}

func (*ToolEvent_Result) isToolEvent_Event() {}

func (*ToolEvent_Error) isToolEvent_Event() {}

// OutputChunk carries one slice of raw stdout/stderr-shaped output from a
// process-backed operation.
type ToolEvent_OutputChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which stream this chunk came from.
	Stream OutputStream `protobuf:"varint,1,opt,name=stream,proto3,enum=pluggableharness.tool.v1.OutputStream" json:"stream,omitempty"`
	// The chunk's raw bytes.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent_OutputChunk) Reset() {
	*x = ToolEvent_OutputChunk{}
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent_OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent_OutputChunk) ProtoMessage() {}

func (x *ToolEvent_OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent_OutputChunk.ProtoReflect.Descriptor instead.
func (*ToolEvent_OutputChunk) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_events_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ToolEvent_OutputChunk) GetStream() OutputStream {
	if x != nil {
		return x.Stream
	}
	return OutputStream_OUTPUT_STREAM_UNSPECIFIED
}

func (x *ToolEvent_OutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Progress carries a human-readable status update for a long-running
// call.
type ToolEvent_Progress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A human-readable description of the current step.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// How far through the operation this call is, in [0.0, 1.0]. Absent
	// means the provider cannot estimate completion fraction.
	FractionComplete *float64 `protobuf:"fixed64,2,opt,name=fraction_complete,json=fractionComplete,proto3,oneof" json:"fraction_complete,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolEvent_Progress) Reset() {
	*x = ToolEvent_Progress{}
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent_Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent_Progress) ProtoMessage() {}

func (x *ToolEvent_Progress) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent_Progress.ProtoReflect.Descriptor instead.
func (*ToolEvent_Progress) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_events_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ToolEvent_Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ToolEvent_Progress) GetFractionComplete() float64 {
	if x != nil && x.FractionComplete != nil {
		return *x.FractionComplete
	}
	return 0
}

// PartialResult carries incremental structured output before the
// terminal result, e.g. search hits as they're found.
type ToolEvent_PartialResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The incremental structured payload.
	Payload       *structpb.Struct `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent_PartialResult) Reset() {
	*x = ToolEvent_PartialResult{}
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent_PartialResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent_PartialResult) ProtoMessage() {}

func (x *ToolEvent_PartialResult) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent_PartialResult.ProtoReflect.Descriptor instead.
func (*ToolEvent_PartialResult) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_events_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ToolEvent_PartialResult) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ExitStatus carries a process-backed operation's child process exit
// information. exec-family tools only — a provider for a non-process-
// backed tool (file read, grep, web fetch) MUST NOT emit this. Appears
// at most once per Invoke stream.
type ToolEvent_ExitStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The child process's exit code.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// The signal that terminated the child process, if any. Absent means
	// the process exited normally (exit_code is meaningful on its own).
	Signal        *string `protobuf:"bytes,2,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent_ExitStatus) Reset() {
	*x = ToolEvent_ExitStatus{}
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent_ExitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent_ExitStatus) ProtoMessage() {}

func (x *ToolEvent_ExitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent_ExitStatus.ProtoReflect.Descriptor instead.
func (*ToolEvent_ExitStatus) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_events_proto_rawDescGZIP(), []int{1, 3}
}

func (x *ToolEvent_ExitStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ToolEvent_ExitStatus) GetSignal() string {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return ""
}

var File_pluggableharness_tool_v1_events_proto protoreflect.FileDescriptor

const file_pluggableharness_tool_v1_events_proto_rawDesc = "" +
	"\n" +
	"%pluggableharness/tool/v1/events.proto\x12\x18pluggableharness.tool.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a%pluggableharness/tool/v1/errors.proto\x1a$pluggableharness/tool/v1/types.proto\"K\n" +
	"\x0eInvokeResponse\x129\n" +
	"\x05event\x18\x01 \x01(\v2#.pluggableharness.tool.v1.ToolEventR\x05event\"\xca\x06\n" +
	"\tToolEvent\x12T\n" +
	"\foutput_chunk\x18\x01 \x01(\v2/.pluggableharness.tool.v1.ToolEvent.OutputChunkH\x00R\voutputChunk\x12J\n" +
	"\bprogress\x18\x02 \x01(\v2,.pluggableharness.tool.v1.ToolEvent.ProgressH\x00R\bprogress\x12Z\n" +
	"\x0epartial_result\x18\x03 \x01(\v21.pluggableharness.tool.v1.ToolEvent.PartialResultH\x00R\rpartialResult\x12Q\n" +
	"\vexit_status\x18\x04 \x01(\v2..pluggableharness.tool.v1.ToolEvent.ExitStatusH\x00R\n" +
	"exitStatus\x12>\n" +
	"\x06result\x18\x05 \x01(\v2$.pluggableharness.tool.v1.ToolResultH\x00R\x06result\x12;\n" +
	"\x05error\x18\x06 \x01(\v2#.pluggableharness.tool.v1.ToolErrorH\x00R\x05error\x1aa\n" +
	"\vOutputChunk\x12>\n" +
	"\x06stream\x18\x01 \x01(\x0e2&.pluggableharness.tool.v1.OutputStreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x1al\n" +
	"\bProgress\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x120\n" +
	"\x11fraction_complete\x18\x02 \x01(\x01H\x00R\x10fractionComplete\x88\x01\x01B\x14\n" +
	"\x12_fraction_complete\x1aB\n" +
	"\rPartialResult\x121\n" +
	"\apayload\x18\x01 \x01(\v2\x17.google.protobuf.StructR\apayload\x1aQ\n" +
	"\n" +
	"ExitStatus\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1b\n" +
	"\x06signal\x18\x02 \x01(\tH\x00R\x06signal\x88\x01\x01B\t\n" +
	"\a_signalB\a\n" +
	"\x05event*a\n" +
	"\fOutputStream\x12\x1d\n" +
	"\x19OUTPUT_STREAM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OUTPUT_STREAM_STDOUT\x10\x01\x12\x18\n" +
	"\x14OUTPUT_STREAM_STDERR\x10\x02B<Z:github.com/pluggableharness/agent/pkg/tool/proto/v1;toolv1b\x06proto3"

var (
	file_pluggableharness_tool_v1_events_proto_rawDescOnce sync.Once
	file_pluggableharness_tool_v1_events_proto_rawDescData []byte
)

func file_pluggableharness_tool_v1_events_proto_rawDescGZIP() []byte {
	file_pluggableharness_tool_v1_events_proto_rawDescOnce.Do(func() {
		file_pluggableharness_tool_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_tool_v1_events_proto_rawDesc), len(file_pluggableharness_tool_v1_events_proto_rawDesc)))
	})
	return file_pluggableharness_tool_v1_events_proto_rawDescData
}

var file_pluggableharness_tool_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pluggableharness_tool_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pluggableharness_tool_v1_events_proto_goTypes = []any{
	(OutputStream)(0),               // 0: pluggableharness.tool.v1.OutputStream
	(*InvokeResponse)(nil),          // 1: pluggableharness.tool.v1.InvokeResponse
	(*ToolEvent)(nil),               // 2: pluggableharness.tool.v1.ToolEvent
	(*ToolEvent_OutputChunk)(nil),   // 3: pluggableharness.tool.v1.ToolEvent.OutputChunk
	(*ToolEvent_Progress)(nil),      // 4: pluggableharness.tool.v1.ToolEvent.Progress
	(*ToolEvent_PartialResult)(nil), // 5: pluggableharness.tool.v1.ToolEvent.PartialResult
	(*ToolEvent_ExitStatus)(nil),    // 6: pluggableharness.tool.v1.ToolEvent.ExitStatus
	(*ToolResult)(nil),              // 7: pluggableharness.tool.v1.ToolResult
	(*ToolError)(nil),               // 8: pluggableharness.tool.v1.ToolError
	(*structpb.Struct)(nil),         // 9: google.protobuf.Struct
}
var file_pluggableharness_tool_v1_events_proto_depIdxs = []int32{
	2, // 0: pluggableharness.tool.v1.InvokeResponse.event:type_name -> pluggableharness.tool.v1.ToolEvent
	3, // 1: pluggableharness.tool.v1.ToolEvent.output_chunk:type_name -> pluggableharness.tool.v1.ToolEvent.OutputChunk
	4, // 2: pluggableharness.tool.v1.ToolEvent.progress:type_name -> pluggableharness.tool.v1.ToolEvent.Progress
	5, // 3: pluggableharness.tool.v1.ToolEvent.partial_result:type_name -> pluggableharness.tool.v1.ToolEvent.PartialResult
	6, // 4: pluggableharness.tool.v1.ToolEvent.exit_status:type_name -> pluggableharness.tool.v1.ToolEvent.ExitStatus
	7, // 5: pluggableharness.tool.v1.ToolEvent.result:type_name -> pluggableharness.tool.v1.ToolResult
	8, // 6: pluggableharness.tool.v1.ToolEvent.error:type_name -> pluggableharness.tool.v1.ToolError
	0, // 7: pluggableharness.tool.v1.ToolEvent.OutputChunk.stream:type_name -> pluggableharness.tool.v1.OutputStream
	9, // 8: pluggableharness.tool.v1.ToolEvent.PartialResult.payload:type_name -> google.protobuf.Struct
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pluggableharness_tool_v1_events_proto_init() }
func file_pluggableharness_tool_v1_events_proto_init() {
	if File_pluggableharness_tool_v1_events_proto != nil {
		return
	}
	file_pluggableharness_tool_v1_errors_proto_init()
	file_pluggableharness_tool_v1_types_proto_init()
	file_pluggableharness_tool_v1_events_proto_msgTypes[1].OneofWrappers = []any{
		(*ToolEvent_OutputChunk_)(nil),
		(*ToolEvent_Progress_)(nil),
		(*ToolEvent_PartialResult_)(nil),
		(*ToolEvent_ExitStatus_)(nil),
		(*ToolEvent_Result)(nil),
		(*ToolEvent_Error)(nil),
	}
	file_pluggableharness_tool_v1_events_proto_msgTypes[3].OneofWrappers = []any{}
	file_pluggableharness_tool_v1_events_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_tool_v1_events_proto_rawDesc), len(file_pluggableharness_tool_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_tool_v1_events_proto_goTypes,
		DependencyIndexes: file_pluggableharness_tool_v1_events_proto_depIdxs,
		EnumInfos:         file_pluggableharness_tool_v1_events_proto_enumTypes,
		MessageInfos:      file_pluggableharness_tool_v1_events_proto_msgTypes,
	}.Build()
	File_pluggableharness_tool_v1_events_proto = out.File
	file_pluggableharness_tool_v1_events_proto_goTypes = nil
	file_pluggableharness_tool_v1_events_proto_depIdxs = nil
}
