// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/tool/v1/rpc_response.proto

package toolv1

import (
	v1 "github.com/pluggableharness/agent/pkg/common/proto/v1"
	v11 "github.com/pluggableharness/agent/pkg/config/proto/v1"
	v12 "github.com/pluggableharness/agent/pkg/render/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetSchemaResponse is this provider's complete capability advertisement.
type GetSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One entry per operation this plugin exposes.
	Tools []*ToolSchema `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	// Prompt-expansion slash commands this provider contributes, per
	// tool.md §2.1. MAY be empty. A direct-invoke command — one that
	// actually executes something — is declared by a slashcommand.v1
	// provider instead (specifications/slashcommand/), never here; a
	// tool provider wanting a direct-invoke shortcut into one of its own
	// operations implements SlashCommandService alongside ToolService in
	// the same process (go-plugin muxes multiple services per connection,
	// per hook.v1's precedent).
	SlashCommands []*v1.PromptExpansionSpec `protobuf:"bytes,2,rep,name=slash_commands,json=slashCommands,proto3" json:"slash_commands,omitempty"`
	// This provider's agent.hcl config schema, per configuration.md §4 —
	// what fields Configure's request may be decoded from.
	ConfigSchema *v11.ConfigSchema `protobuf:"bytes,3,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	// Which of the eight dispatchable hook points (hook/v1.HookPoint) this
	// provider subscribes a HookSubscriberService to, per this provider's own
	// agent.hcl hook{} blocks. Lets the kernel validate a hook{} declaration
	// at config-load time instead of discovering an unsupported subscription
	// only when that hook point first fires.
	SupportedHookPoints []v1.HookPoint `protobuf:"varint,4,rep,packed,name=supported_hook_points,json=supportedHookPoints,proto3,enum=pluggableharness.common.v1.HookPoint" json:"supported_hook_points,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_rpc_response_proto_rawDescGZIP(), []int{0}
}

func (x *GetSchemaResponse) GetTools() []*ToolSchema {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GetSchemaResponse) GetSlashCommands() []*v1.PromptExpansionSpec {
	if x != nil {
		return x.SlashCommands
	}
	return nil
}

func (x *GetSchemaResponse) GetConfigSchema() *v11.ConfigSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

func (x *GetSchemaResponse) GetSupportedHookPoints() []v1.HookPoint {
	if x != nil {
		return x.SupportedHookPoints
	}
	return nil
}

// ConfigureResponse is empty on success. Errors surface as a gRPC status
// carrying a ToolError in its detail, per grpc.md — not an in-band field
// here.
type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_rpc_response_proto_rawDescGZIP(), []int{1}
}

// RenderResponse wraps the rendered tree. A thin per-RPC envelope around
// RenderTree, which keeps its own rich structure independent of the RPC
// signature.
type RenderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rendered tree.
	Tree          *v12.RenderTree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_rpc_response_proto_rawDescGZIP(), []int{2}
}

func (x *RenderResponse) GetTree() *v12.RenderTree {
	if x != nil {
		return x.Tree
	}
	return nil
}

// PreviewResponse carries a dry-run, human-readable description of what
// Invoke(call) would do, per protocol.md#preview — e.g. an edit tool
// returns the diff it would apply. Rendered into the plan/apply gate's
// permission UI via PlanItem.preview (pluggableharness.plan.v1,
// a sibling protocol revision) — that field and this response share the
// same pluggableharness.render.v1.RenderTree type by design, so a
// Preview call's output and a plan item's stored preview are
// interchangeable.
type PreviewResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The dry-run preview, rendered as a RenderTree. Producing this MUST NOT
	// mutate anything and MUST be side-effect-free — the same guarantee
	// TOOL_KIND_DATA_SOURCE operations make, but unconditionally, regardless
	// of the call's actual ToolKind.
	Preview       *v12.RenderTree `protobuf:"bytes,1,opt,name=preview,proto3" json:"preview,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewResponse) Reset() {
	*x = PreviewResponse{}
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewResponse) ProtoMessage() {}

func (x *PreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewResponse.ProtoReflect.Descriptor instead.
func (*PreviewResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_rpc_response_proto_rawDescGZIP(), []int{3}
}

func (x *PreviewResponse) GetPreview() *v12.RenderTree {
	if x != nil {
		return x.Preview
	}
	return nil
}

// DescribeResponse reports this plugin build's own identity, per
// configuration/lock-file.md's dev_overrides note: a dev_overrides-resolved
// plugin has no lock-file entry for the kernel to read {name, version,
// source, category, protocol_version} from, so the kernel obtains it
// directly from the running process via this RPC instead.
type DescribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// This plugin build's identity.
	Producer      *v1.ProducerRef `protobuf:"bytes,1,opt,name=producer,proto3" json:"producer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_rpc_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_rpc_response_proto_rawDescGZIP(), []int{4}
}

func (x *DescribeResponse) GetProducer() *v1.ProducerRef {
	if x != nil {
		return x.Producer
	}
	return nil
}

var File_pluggableharness_tool_v1_rpc_response_proto protoreflect.FileDescriptor

const file_pluggableharness_tool_v1_rpc_response_proto_rawDesc = "" +
	"\n" +
	"+pluggableharness/tool/v1/rpc_response.proto\x12\x18pluggableharness.tool.v1\x1a&pluggableharness/common/v1/types.proto\x1a&pluggableharness/config/v1/types.proto\x1a&pluggableharness/render/v1/types.proto\x1a$pluggableharness/tool/v1/types.proto\"\xd1\x02\n" +
	"\x11GetSchemaResponse\x12:\n" +
	"\x05tools\x18\x01 \x03(\v2$.pluggableharness.tool.v1.ToolSchemaR\x05tools\x12V\n" +
	"\x0eslash_commands\x18\x02 \x03(\v2/.pluggableharness.common.v1.PromptExpansionSpecR\rslashCommands\x12M\n" +
	"\rconfig_schema\x18\x03 \x01(\v2(.pluggableharness.config.v1.ConfigSchemaR\fconfigSchema\x12Y\n" +
	"\x15supported_hook_points\x18\x04 \x03(\x0e2%.pluggableharness.common.v1.HookPointR\x13supportedHookPoints\"\x13\n" +
	"\x11ConfigureResponse\"L\n" +
	"\x0eRenderResponse\x12:\n" +
	"\x04tree\x18\x01 \x01(\v2&.pluggableharness.render.v1.RenderTreeR\x04tree\"S\n" +
	"\x0fPreviewResponse\x12@\n" +
	"\apreview\x18\x01 \x01(\v2&.pluggableharness.render.v1.RenderTreeR\apreview\"W\n" +
	"\x10DescribeResponse\x12C\n" +
	"\bproducer\x18\x01 \x01(\v2'.pluggableharness.common.v1.ProducerRefR\bproducerB<Z:github.com/pluggableharness/agent/pkg/tool/proto/v1;toolv1b\x06proto3"

var (
	file_pluggableharness_tool_v1_rpc_response_proto_rawDescOnce sync.Once
	file_pluggableharness_tool_v1_rpc_response_proto_rawDescData []byte
)

func file_pluggableharness_tool_v1_rpc_response_proto_rawDescGZIP() []byte {
	file_pluggableharness_tool_v1_rpc_response_proto_rawDescOnce.Do(func() {
		file_pluggableharness_tool_v1_rpc_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_tool_v1_rpc_response_proto_rawDesc), len(file_pluggableharness_tool_v1_rpc_response_proto_rawDesc)))
	})
	return file_pluggableharness_tool_v1_rpc_response_proto_rawDescData
}

var file_pluggableharness_tool_v1_rpc_response_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pluggableharness_tool_v1_rpc_response_proto_goTypes = []any{
	(*GetSchemaResponse)(nil),      // 0: pluggableharness.tool.v1.GetSchemaResponse
	(*ConfigureResponse)(nil),      // 1: pluggableharness.tool.v1.ConfigureResponse
	(*RenderResponse)(nil),         // 2: pluggableharness.tool.v1.RenderResponse
	(*PreviewResponse)(nil),        // 3: pluggableharness.tool.v1.PreviewResponse
	(*DescribeResponse)(nil),       // 4: pluggableharness.tool.v1.DescribeResponse
	(*ToolSchema)(nil),             // 5: pluggableharness.tool.v1.ToolSchema
	(*v1.PromptExpansionSpec)(nil), // 6: pluggableharness.common.v1.PromptExpansionSpec
	(*v11.ConfigSchema)(nil),       // 7: pluggableharness.config.v1.ConfigSchema
	(v1.HookPoint)(0),              // 8: pluggableharness.common.v1.HookPoint
	(*v12.RenderTree)(nil),         // 9: pluggableharness.render.v1.RenderTree
	(*v1.ProducerRef)(nil),         // 10: pluggableharness.common.v1.ProducerRef
}
var file_pluggableharness_tool_v1_rpc_response_proto_depIdxs = []int32{
	5,  // 0: pluggableharness.tool.v1.GetSchemaResponse.tools:type_name -> pluggableharness.tool.v1.ToolSchema
	6,  // 1: pluggableharness.tool.v1.GetSchemaResponse.slash_commands:type_name -> pluggableharness.common.v1.PromptExpansionSpec
	7,  // 2: pluggableharness.tool.v1.GetSchemaResponse.config_schema:type_name -> pluggableharness.config.v1.ConfigSchema
	8,  // 3: pluggableharness.tool.v1.GetSchemaResponse.supported_hook_points:type_name -> pluggableharness.common.v1.HookPoint
	9,  // 4: pluggableharness.tool.v1.RenderResponse.tree:type_name -> pluggableharness.render.v1.RenderTree
	9,  // 5: pluggableharness.tool.v1.PreviewResponse.preview:type_name -> pluggableharness.render.v1.RenderTree
	10, // 6: pluggableharness.tool.v1.DescribeResponse.producer:type_name -> pluggableharness.common.v1.ProducerRef
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pluggableharness_tool_v1_rpc_response_proto_init() }
func file_pluggableharness_tool_v1_rpc_response_proto_init() {
	if File_pluggableharness_tool_v1_rpc_response_proto != nil {
		return
	}
	file_pluggableharness_tool_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_tool_v1_rpc_response_proto_rawDesc), len(file_pluggableharness_tool_v1_rpc_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_tool_v1_rpc_response_proto_goTypes,
		DependencyIndexes: file_pluggableharness_tool_v1_rpc_response_proto_depIdxs,
		MessageInfos:      file_pluggableharness_tool_v1_rpc_response_proto_msgTypes,
	}.Build()
	File_pluggableharness_tool_v1_rpc_response_proto = out.File
	file_pluggableharness_tool_v1_rpc_response_proto_goTypes = nil
	file_pluggableharness_tool_v1_rpc_response_proto_depIdxs = nil
}
