// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/agent/tool/v1/tool.proto

// Package pluggableharness.agent.tool.v1 defines the tool provider plugin protocol
// described in specifications/tool.md — the wire contract for file I/O,
// shell execution, search, web access, task tracking, sub-agent spawning,
// and similar operations.

package toolv1

import (
	v11 "github.com/pluggableharness/agent/pkg/config/proto/v1"
	v13 "github.com/pluggableharness/agent/pkg/render/proto/v1"
	v12 "github.com/pluggableharness/agent/pkg/schema/proto/v1"
	v1 "github.com/pluggableharness/agent/pkg/slashcommand/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolKind is the axis that drives the plan/apply gate, per tool.md §2.
// Deliberately separate from RiskClass: kind is the binary the gate
// mechanically needs, risk is a finer-grained classification within it.
type ToolKind int32

const (
	// Zero value. Never valid for a real operation; its presence on the wire
	// means a caller forgot to set the field.
	ToolKind_TOOL_KIND_UNSPECIFIED ToolKind = 0
	// Mutating. Gated behind the plan/apply approval gate.
	ToolKind_TOOL_KIND_RESOURCE ToolKind = 1
	// Read-only. Executes freely, subject only to the policy precheck
	// (agent-loop.md §5.4).
	ToolKind_TOOL_KIND_DATA_SOURCE ToolKind = 2
	// Blocks the current turn for human input, per tool.md §2.1. Produces no
	// state mutation of its own — the human's answer becomes the result.
	ToolKind_TOOL_KIND_INTERACTIVE ToolKind = 3
)

// Enum value maps for ToolKind.
var (
	ToolKind_name = map[int32]string{
		0: "TOOL_KIND_UNSPECIFIED",
		1: "TOOL_KIND_RESOURCE",
		2: "TOOL_KIND_DATA_SOURCE",
		3: "TOOL_KIND_INTERACTIVE",
	}
	ToolKind_value = map[string]int32{
		"TOOL_KIND_UNSPECIFIED": 0,
		"TOOL_KIND_RESOURCE":    1,
		"TOOL_KIND_DATA_SOURCE": 2,
		"TOOL_KIND_INTERACTIVE": 3,
	}
)

func (x ToolKind) Enum() *ToolKind {
	p := new(ToolKind)
	*p = x
	return p
}

func (x ToolKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_agent_tool_v1_tool_proto_enumTypes[0].Descriptor()
}

func (ToolKind) Type() protoreflect.EnumType {
	return &file_pluggableharness_agent_tool_v1_tool_proto_enumTypes[0]
}

func (x ToolKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolKind.Descriptor instead.
func (ToolKind) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{0}
}

// RiskClass classifies an operation's blast radius, per tool.md §2. Orthogonal
// to ToolKind: kind determines whether the plan/apply gate applies at all,
// risk determines how significant the gated (or inherently ungated) action is.
type RiskClass int32

const (
	// Zero value. Never valid for a real operation; its presence on the wire
	// means a caller forgot to set the field.
	RiskClass_RISK_CLASS_UNSPECIFIED RiskClass = 0
	// Inherently unable to mutate anything the plugin controls. MUST be used
	// for TOOL_KIND_DATA_SOURCE and TOOL_KIND_INTERACTIVE alike — neither
	// mutates nor reads anything external, so neither has a blast radius to
	// classify.
	RiskClass_RISK_CLASS_READ_ONLY RiskClass = 1
	// A resource operation with narrow, easily-reversible blast radius, e.g.
	// a write to a scratch path.
	RiskClass_RISK_CLASS_LOW RiskClass = 2
	// A resource operation with real but bounded blast radius, e.g. editing
	// a tracked source file.
	RiskClass_RISK_CLASS_MODERATE RiskClass = 3
	// A resource operation with broad or hard-to-predict blast radius, e.g.
	// arbitrary shell execution.
	RiskClass_RISK_CLASS_HIGH RiskClass = 4
	// A resource operation capable of irreversible or wide-blast-radius
	// action, e.g. `rm -rf`, a force-push, or spawning a sub-agent with
	// further unattended write access.
	//
	// A TOOL_KIND_RESOURCE operation MUST declare one of LOW/MODERATE/HIGH/
	// CRITICAL — never READ_ONLY. There is no resource with read_only risk.
	RiskClass_RISK_CLASS_CRITICAL RiskClass = 5
)

// Enum value maps for RiskClass.
var (
	RiskClass_name = map[int32]string{
		0: "RISK_CLASS_UNSPECIFIED",
		1: "RISK_CLASS_READ_ONLY",
		2: "RISK_CLASS_LOW",
		3: "RISK_CLASS_MODERATE",
		4: "RISK_CLASS_HIGH",
		5: "RISK_CLASS_CRITICAL",
	}
	RiskClass_value = map[string]int32{
		"RISK_CLASS_UNSPECIFIED": 0,
		"RISK_CLASS_READ_ONLY":   1,
		"RISK_CLASS_LOW":         2,
		"RISK_CLASS_MODERATE":    3,
		"RISK_CLASS_HIGH":        4,
		"RISK_CLASS_CRITICAL":    5,
	}
)

func (x RiskClass) Enum() *RiskClass {
	p := new(RiskClass)
	*p = x
	return p
}

func (x RiskClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskClass) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_agent_tool_v1_tool_proto_enumTypes[1].Descriptor()
}

func (RiskClass) Type() protoreflect.EnumType {
	return &file_pluggableharness_agent_tool_v1_tool_proto_enumTypes[1]
}

func (x RiskClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskClass.Descriptor instead.
func (RiskClass) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{1}
}

// OutputStream distinguishes which underlying stream an OutputChunk came
// from.
type OutputStream int32

const (
	// Zero value. Never valid for a real chunk; its presence on the wire
	// means a caller forgot to set the field.
	OutputStream_OUTPUT_STREAM_UNSPECIFIED OutputStream = 0
	// Standard output.
	OutputStream_OUTPUT_STREAM_STDOUT OutputStream = 1
	// Standard error.
	OutputStream_OUTPUT_STREAM_STDERR OutputStream = 2
)

// Enum value maps for OutputStream.
var (
	OutputStream_name = map[int32]string{
		0: "OUTPUT_STREAM_UNSPECIFIED",
		1: "OUTPUT_STREAM_STDOUT",
		2: "OUTPUT_STREAM_STDERR",
	}
	OutputStream_value = map[string]int32{
		"OUTPUT_STREAM_UNSPECIFIED": 0,
		"OUTPUT_STREAM_STDOUT":      1,
		"OUTPUT_STREAM_STDERR":      2,
	}
)

func (x OutputStream) Enum() *OutputStream {
	p := new(OutputStream)
	*p = x
	return p
}

func (x OutputStream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputStream) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_agent_tool_v1_tool_proto_enumTypes[2].Descriptor()
}

func (OutputStream) Type() protoreflect.EnumType {
	return &file_pluggableharness_agent_tool_v1_tool_proto_enumTypes[2]
}

func (x OutputStream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutputStream.Descriptor instead.
func (OutputStream) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{2}
}

// ToolErrorCategory classifies why an Invoke call failed, per tool.md §8.
// Deliberately distinct from provider.md §8's ProviderErrorCategory — there
// is no RATE_LIMITED or CONTEXT_LENGTH_EXCEEDED here, those are
// model-vendor concepts. The two enums MUST NOT be merged even though the
// surrounding error-envelope shape (category/message/retryable) is
// parallel.
type ToolErrorCategory int32

const (
	// Zero value. Never valid for a real error; its presence on the wire
	// means a caller forgot to set the field.
	ToolErrorCategory_TOOL_ERROR_CATEGORY_UNSPECIFIED ToolErrorCategory = 0
	// Input failed input_schema validation.
	ToolErrorCategory_TOOL_ERROR_CATEGORY_INVALID_ARGUMENTS ToolErrorCategory = 1
	// The target of the operation doesn't exist (path, URL, symbol, ...).
	ToolErrorCategory_TOOL_ERROR_CATEGORY_NOT_FOUND ToolErrorCategory = 2
	// OS/policy denied the underlying operation.
	ToolErrorCategory_TOOL_ERROR_CATEGORY_PERMISSION_DENIED ToolErrorCategory = 3
	// The operation ran but failed on its own terms (non-zero exit, compiler
	// error, HTTP 4xx/5xx) — not a plugin bug.
	ToolErrorCategory_TOOL_ERROR_CATEGORY_EXECUTION_FAILED ToolErrorCategory = 4
	// Exceeded a plugin- or kernel-enforced deadline.
	ToolErrorCategory_TOOL_ERROR_CATEGORY_TIMEOUT ToolErrorCategory = 5
	// The provider detected a conflicting concurrent call it could not
	// serialize itself (see ConcurrencySpec) — signals the kernel to retry
	// serialized.
	ToolErrorCategory_TOOL_ERROR_CATEGORY_CONCURRENCY_CONFLICT ToolErrorCategory = 6
	// The stream was cancelled per tool.md §1 — not "an error" in the
	// failure sense; kept distinct so the kernel doesn't surface it to the
	// model as a tool failure when the whole turn is being aborted anyway.
	ToolErrorCategory_TOOL_ERROR_CATEGORY_CANCELLED ToolErrorCategory = 7
	// The plugin subprocess itself died mid-Invoke (transport error, not a
	// graceful error event the plugin chose to emit). MUST be
	// kernel-synthesized only — a plugin process that crashes obviously
	// cannot emit this itself; the kernel detects the crash and synthesizes
	// this category.
	ToolErrorCategory_TOOL_ERROR_CATEGORY_PROCESS_CRASHED ToolErrorCategory = 8
	// Anything else. MUST include the raw underlying error in
	// ToolError.details.
	ToolErrorCategory_TOOL_ERROR_CATEGORY_UNKNOWN ToolErrorCategory = 9
)

// Enum value maps for ToolErrorCategory.
var (
	ToolErrorCategory_name = map[int32]string{
		0: "TOOL_ERROR_CATEGORY_UNSPECIFIED",
		1: "TOOL_ERROR_CATEGORY_INVALID_ARGUMENTS",
		2: "TOOL_ERROR_CATEGORY_NOT_FOUND",
		3: "TOOL_ERROR_CATEGORY_PERMISSION_DENIED",
		4: "TOOL_ERROR_CATEGORY_EXECUTION_FAILED",
		5: "TOOL_ERROR_CATEGORY_TIMEOUT",
		6: "TOOL_ERROR_CATEGORY_CONCURRENCY_CONFLICT",
		7: "TOOL_ERROR_CATEGORY_CANCELLED",
		8: "TOOL_ERROR_CATEGORY_PROCESS_CRASHED",
		9: "TOOL_ERROR_CATEGORY_UNKNOWN",
	}
	ToolErrorCategory_value = map[string]int32{
		"TOOL_ERROR_CATEGORY_UNSPECIFIED":          0,
		"TOOL_ERROR_CATEGORY_INVALID_ARGUMENTS":    1,
		"TOOL_ERROR_CATEGORY_NOT_FOUND":            2,
		"TOOL_ERROR_CATEGORY_PERMISSION_DENIED":    3,
		"TOOL_ERROR_CATEGORY_EXECUTION_FAILED":     4,
		"TOOL_ERROR_CATEGORY_TIMEOUT":              5,
		"TOOL_ERROR_CATEGORY_CONCURRENCY_CONFLICT": 6,
		"TOOL_ERROR_CATEGORY_CANCELLED":            7,
		"TOOL_ERROR_CATEGORY_PROCESS_CRASHED":      8,
		"TOOL_ERROR_CATEGORY_UNKNOWN":              9,
	}
)

func (x ToolErrorCategory) Enum() *ToolErrorCategory {
	p := new(ToolErrorCategory)
	*p = x
	return p
}

func (x ToolErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_agent_tool_v1_tool_proto_enumTypes[3].Descriptor()
}

func (ToolErrorCategory) Type() protoreflect.EnumType {
	return &file_pluggableharness_agent_tool_v1_tool_proto_enumTypes[3]
}

func (x ToolErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolErrorCategory.Descriptor instead.
func (ToolErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{3}
}

// GetSchemaRequest carries no fields — GetSchema takes no parameters.
type GetSchemaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaRequest) Reset() {
	*x = GetSchemaRequest{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaRequest) ProtoMessage() {}

func (x *GetSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaRequest.ProtoReflect.Descriptor instead.
func (*GetSchemaRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{0}
}

// GetSchemaResponse is this provider's complete capability advertisement.
type GetSchemaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One entry per operation this plugin exposes.
	Tools []*ToolSchema `protobuf:"bytes,1,rep,name=tools,proto3" json:"tools,omitempty"`
	// Slash commands this provider contributes, per tool.md §2.1. MAY be
	// empty. Each entry's tool_name MUST reference one of this same
	// provider's own operations declared in `tools` above — a provider
	// cannot declare a slash command that invokes another provider's tool.
	SlashCommands []*v1.SlashCommandSpec `protobuf:"bytes,2,rep,name=slash_commands,json=slashCommands,proto3" json:"slash_commands,omitempty"`
	// This provider's agent.hcl config schema, per configuration.md §4 —
	// what fields Configure's request may be decoded from.
	ConfigSchema  *v11.ConfigSchema `protobuf:"bytes,3,opt,name=config_schema,json=configSchema,proto3" json:"config_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemaResponse) Reset() {
	*x = GetSchemaResponse{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemaResponse) ProtoMessage() {}

func (x *GetSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemaResponse.ProtoReflect.Descriptor instead.
func (*GetSchemaResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{1}
}

func (x *GetSchemaResponse) GetTools() []*ToolSchema {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *GetSchemaResponse) GetSlashCommands() []*v1.SlashCommandSpec {
	if x != nil {
		return x.SlashCommands
	}
	return nil
}

func (x *GetSchemaResponse) GetConfigSchema() *v11.ConfigSchema {
	if x != nil {
		return x.ConfigSchema
	}
	return nil
}

// ConfigureRequest wraps this provider's already-decoded agent.hcl config.
type ConfigureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The provider-specific config, decoded from agent.hcl via the
	// schema-to-cty bridge before crossing the wire.
	Config        *structpb.Struct `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureRequest.ProtoReflect.Descriptor instead.
func (*ConfigureRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigureRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

// ConfigureResponse is empty on success. Errors surface as a gRPC status
// carrying a ToolError in its detail, per grpc.md — not an in-band field
// here.
type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureResponse.ProtoReflect.Descriptor instead.
func (*ConfigureResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{3}
}

// ConcurrencySpec declares whether this operation's Invoke calls may run
// concurrently against the same provider process, per tool.md §5.
type ConcurrencySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MUST be set, per operation, except for TOOL_KIND_INTERACTIVE. false (or
	// an absent/unset default) means the kernel MUST NOT run any other Invoke
	// call against this provider process concurrently with this one — a
	// coarse, provider-wide lock. true means concurrent Invoke calls against
	// this provider are generally safe. A provider that does not populate
	// this field at all MUST be treated by the kernel as false — the
	// conservative default.
	Safe bool `protobuf:"varint,1,opt,name=safe,proto3" json:"safe,omitempty"`
	// Only meaningful when safe == true. Names of this operation's
	// input_schema fields whose value(s) form a serialization key. The
	// kernel computes key = (provider_name, tool_name, value(key_fields)) and
	// MUST serialize calls sharing an identical key, while still freely
	// parallelizing calls with distinct keys. Omitting key_fields under
	// safe == true asserts that no two calls to this operation can ever
	// conflict — a strong claim, true for e.g. web_search, false for e.g.
	// write_file.
	KeyFields     []string `protobuf:"bytes,2,rep,name=key_fields,json=keyFields,proto3" json:"key_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcurrencySpec) Reset() {
	*x = ConcurrencySpec{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcurrencySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcurrencySpec) ProtoMessage() {}

func (x *ConcurrencySpec) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcurrencySpec.ProtoReflect.Descriptor instead.
func (*ConcurrencySpec) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{4}
}

func (x *ConcurrencySpec) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *ConcurrencySpec) GetKeyFields() []string {
	if x != nil {
		return x.KeyFields
	}
	return nil
}

// ToolSchema declares one operation this provider exposes, per tool.md §2.
type ToolSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MUST — unique within this provider's namespace, e.g. "read_file".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// MUST — drives the plan/apply gate.
	Kind ToolKind `protobuf:"varint,2,opt,name=kind,proto3,enum=pluggableharness.agent.tool.v1.ToolKind" json:"kind,omitempty"`
	// MUST — see RiskClass.
	Risk RiskClass `protobuf:"varint,3,opt,name=risk,proto3,enum=pluggableharness.agent.tool.v1.RiskClass" json:"risk,omitempty"`
	// MUST — shown to the model for tool selection and in plan diffs.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// MUST — the common JSON-Schema subset per provider.md §6, describing the
	// shape of ToolCall.arguments for this operation.
	InputSchema *v12.Schema `protobuf:"bytes,5,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	// MUST — the common JSON-Schema subset per provider.md §6, describing the
	// shape of ToolResult.payload for this operation.
	OutputSchema *v12.Schema `protobuf:"bytes,6,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	// MUST — true if Invoke may emit intermediate ToolEvents (output_chunk,
	// progress, partial_result) before the terminal event; false if Invoke
	// always emits exactly one terminal event with no lead-up.
	Streaming bool `protobuf:"varint,7,opt,name=streaming,proto3" json:"streaming,omitempty"`
	// MUST, except MUST NOT be meaningfully set for TOOL_KIND_INTERACTIVE.
	Concurrency   *ConcurrencySpec `protobuf:"bytes,8,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolSchema) Reset() {
	*x = ToolSchema{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSchema) ProtoMessage() {}

func (x *ToolSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSchema.ProtoReflect.Descriptor instead.
func (*ToolSchema) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{5}
}

func (x *ToolSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSchema) GetKind() ToolKind {
	if x != nil {
		return x.Kind
	}
	return ToolKind_TOOL_KIND_UNSPECIFIED
}

func (x *ToolSchema) GetRisk() RiskClass {
	if x != nil {
		return x.Risk
	}
	return RiskClass_RISK_CLASS_UNSPECIFIED
}

func (x *ToolSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSchema) GetInputSchema() *v12.Schema {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *ToolSchema) GetOutputSchema() *v12.Schema {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *ToolSchema) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *ToolSchema) GetConcurrency() *ConcurrencySpec {
	if x != nil {
		return x.Concurrency
	}
	return nil
}

// InvokeRequest wraps the call to execute. A thin per-RPC envelope around
// ToolCall, which keeps its own rich structure independent of the RPC
// signature.
type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The call to execute.
	Call          *ToolCall `protobuf:"bytes,1,opt,name=call,proto3" json:"call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{6}
}

func (x *InvokeRequest) GetCall() *ToolCall {
	if x != nil {
		return x.Call
	}
	return nil
}

// InvokeResponse wraps one message in the stream Invoke returns. A thin
// per-RPC envelope around ToolEvent, which keeps its own rich structure
// independent of the RPC signature.
type InvokeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event.
	Event         *ToolEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{7}
}

func (x *InvokeResponse) GetEvent() *ToolEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

// ToolCall is one request to execute an operation, per tool.md §4.
type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MUST — kernel-assigned. Echoed in every ToolEvent for this call, for
	// correlation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// MUST — matches a ToolSchema.name from this provider's GetSchema
	// response.
	ToolName string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// MUST — already-parsed JSON conforming to that ToolSchema's
	// input_schema.
	Arguments     *structpb.Struct `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{8}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

// ToolEvent is one message in the stream Invoke returns, per tool.md §4.
// Exactly one of `result`/`error` closes the stream; `output_chunk`,
// `progress`, and `partial_result` MAY each appear zero or more times
// before it; `exit_status` MAY appear at most once. The relative order of
// `output_chunk` events MUST be preserved by the transport.
type ToolEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ToolEvent_OutputChunk_
	//	*ToolEvent_Progress_
	//	*ToolEvent_PartialResult_
	//	*ToolEvent_ExitStatus_
	//	*ToolEvent_Result
	//	*ToolEvent_Error
	Event         isToolEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent) Reset() {
	*x = ToolEvent{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent) ProtoMessage() {}

func (x *ToolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent.ProtoReflect.Descriptor instead.
func (*ToolEvent) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{9}
}

func (x *ToolEvent) GetEvent() isToolEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ToolEvent) GetOutputChunk() *ToolEvent_OutputChunk {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_OutputChunk_); ok {
			return x.OutputChunk
		}
	}
	return nil
}

func (x *ToolEvent) GetProgress() *ToolEvent_Progress {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Progress_); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *ToolEvent) GetPartialResult() *ToolEvent_PartialResult {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_PartialResult_); ok {
			return x.PartialResult
		}
	}
	return nil
}

func (x *ToolEvent) GetExitStatus() *ToolEvent_ExitStatus {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_ExitStatus_); ok {
			return x.ExitStatus
		}
	}
	return nil
}

func (x *ToolEvent) GetResult() *ToolResult {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *ToolEvent) GetError() *ToolError {
	if x != nil {
		if x, ok := x.Event.(*ToolEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isToolEvent_Event interface {
	isToolEvent_Event()
}

type ToolEvent_OutputChunk_ struct {
	// Incremental raw output from a process-backed operation.
	OutputChunk *ToolEvent_OutputChunk `protobuf:"bytes,1,opt,name=output_chunk,json=outputChunk,proto3,oneof"`
}

type ToolEvent_Progress_ struct {
	// A human-readable progress update.
	Progress *ToolEvent_Progress `protobuf:"bytes,2,opt,name=progress,proto3,oneof"`
}

type ToolEvent_PartialResult_ struct {
	// Incremental structured output, e.g. search hits as they're found.
	PartialResult *ToolEvent_PartialResult `protobuf:"bytes,3,opt,name=partial_result,json=partialResult,proto3,oneof"`
}

type ToolEvent_ExitStatus_ struct {
	// The exit status of a process-backed operation's child process.
	ExitStatus *ToolEvent_ExitStatus `protobuf:"bytes,4,opt,name=exit_status,json=exitStatus,proto3,oneof"`
}

type ToolEvent_Result struct {
	// The terminal, successful result of this call.
	Result *ToolResult `protobuf:"bytes,5,opt,name=result,proto3,oneof"`
}

type ToolEvent_Error struct {
	// The terminal, failed result of this call.
	Error *ToolError `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

func (*ToolEvent_OutputChunk_) isToolEvent_Event() {}

func (*ToolEvent_Progress_) isToolEvent_Event() {}

func (*ToolEvent_PartialResult_) isToolEvent_Event() {}

func (*ToolEvent_ExitStatus_) isToolEvent_Event() {}

func (*ToolEvent_Result) isToolEvent_Event() {}

func (*ToolEvent_Error) isToolEvent_Event() {}

// ToolResult is the terminal, successful outcome of an Invoke call.
type ToolResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MUST conform to the ToolSchema.output_schema declared for this call's
	// tool_name; the kernel strictly validates this — a non-conforming
	// payload becomes a ToolError with category TOOL_ERROR_CATEGORY_UNKNOWN
	// rather than being passed through to history.
	Payload       *structpb.Struct `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{10}
}

func (x *ToolResult) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ToolError is the terminal, failed outcome of an Invoke call.
type ToolError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MUST.
	Category ToolErrorCategory `protobuf:"varint,1,opt,name=category,proto3,enum=pluggableharness.agent.tool.v1.ToolErrorCategory" json:"category,omitempty"`
	// MUST — human-readable.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// MUST.
	Retryable bool `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// MAY — provider-specific structured detail. MUST include the raw
	// underlying error for category TOOL_ERROR_CATEGORY_UNKNOWN.
	Details       *structpb.Struct `protobuf:"bytes,4,opt,name=details,proto3,oneof" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolError) Reset() {
	*x = ToolError{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolError) ProtoMessage() {}

func (x *ToolError) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolError.ProtoReflect.Descriptor instead.
func (*ToolError) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{11}
}

func (x *ToolError) GetCategory() ToolErrorCategory {
	if x != nil {
		return x.Category
	}
	return ToolErrorCategory_TOOL_ERROR_CATEGORY_UNSPECIFIED
}

func (x *ToolError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ToolError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ToolError) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

// RenderRequest carries the opaque payload to render, per tool.md §7. See
// grpc.md's Emit->Render->Paint carve-out for why this field stays `bytes`
// rather than a strongly-typed message.
type RenderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The opaque emitted payload to render.
	Payload       []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderRequest) Reset() {
	*x = RenderRequest{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderRequest) ProtoMessage() {}

func (x *RenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderRequest.ProtoReflect.Descriptor instead.
func (*RenderRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{12}
}

func (x *RenderRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RenderResponse wraps the rendered tree. A thin per-RPC envelope around
// RenderTree, which keeps its own rich structure independent of the RPC
// signature.
type RenderResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The rendered tree.
	Tree          *v13.RenderTree `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderResponse) Reset() {
	*x = RenderResponse{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderResponse) ProtoMessage() {}

func (x *RenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderResponse.ProtoReflect.Descriptor instead.
func (*RenderResponse) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{13}
}

func (x *RenderResponse) GetTree() *v13.RenderTree {
	if x != nil {
		return x.Tree
	}
	return nil
}

// OutputChunk carries one slice of raw stdout/stderr-shaped output from a
// process-backed operation.
type ToolEvent_OutputChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which stream this chunk came from.
	Stream OutputStream `protobuf:"varint,1,opt,name=stream,proto3,enum=pluggableharness.agent.tool.v1.OutputStream" json:"stream,omitempty"`
	// The chunk's raw bytes.
	Data          []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent_OutputChunk) Reset() {
	*x = ToolEvent_OutputChunk{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent_OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent_OutputChunk) ProtoMessage() {}

func (x *ToolEvent_OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent_OutputChunk.ProtoReflect.Descriptor instead.
func (*ToolEvent_OutputChunk) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ToolEvent_OutputChunk) GetStream() OutputStream {
	if x != nil {
		return x.Stream
	}
	return OutputStream_OUTPUT_STREAM_UNSPECIFIED
}

func (x *ToolEvent_OutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Progress carries a human-readable status update for a long-running
// call.
type ToolEvent_Progress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A human-readable description of the current step.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// How far through the operation this call is, in [0.0, 1.0]. Absent
	// means the provider cannot estimate completion fraction.
	FractionComplete *float64 `protobuf:"fixed64,2,opt,name=fraction_complete,json=fractionComplete,proto3,oneof" json:"fraction_complete,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolEvent_Progress) Reset() {
	*x = ToolEvent_Progress{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent_Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent_Progress) ProtoMessage() {}

func (x *ToolEvent_Progress) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent_Progress.ProtoReflect.Descriptor instead.
func (*ToolEvent_Progress) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{9, 1}
}

func (x *ToolEvent_Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ToolEvent_Progress) GetFractionComplete() float64 {
	if x != nil && x.FractionComplete != nil {
		return *x.FractionComplete
	}
	return 0
}

// PartialResult carries incremental structured output before the
// terminal result, e.g. search hits as they're found.
type ToolEvent_PartialResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The incremental structured payload.
	Payload       *structpb.Struct `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent_PartialResult) Reset() {
	*x = ToolEvent_PartialResult{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent_PartialResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent_PartialResult) ProtoMessage() {}

func (x *ToolEvent_PartialResult) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent_PartialResult.ProtoReflect.Descriptor instead.
func (*ToolEvent_PartialResult) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{9, 2}
}

func (x *ToolEvent_PartialResult) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ExitStatus carries a process-backed operation's child process exit
// information. exec-family tools only — a provider for a non-process-
// backed tool (file read, grep, web fetch) MUST NOT emit this. Appears
// at most once per Invoke stream.
type ToolEvent_ExitStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The child process's exit code.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// The signal that terminated the child process, if any. Absent means
	// the process exited normally (exit_code is meaningful on its own).
	Signal        *string `protobuf:"bytes,2,opt,name=signal,proto3,oneof" json:"signal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent_ExitStatus) Reset() {
	*x = ToolEvent_ExitStatus{}
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent_ExitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent_ExitStatus) ProtoMessage() {}

func (x *ToolEvent_ExitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent_ExitStatus.ProtoReflect.Descriptor instead.
func (*ToolEvent_ExitStatus) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP(), []int{9, 3}
}

func (x *ToolEvent_ExitStatus) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ToolEvent_ExitStatus) GetSignal() string {
	if x != nil && x.Signal != nil {
		return *x.Signal
	}
	return ""
}

var File_pluggableharness_agent_tool_v1_tool_proto protoreflect.FileDescriptor

const file_pluggableharness_agent_tool_v1_tool_proto_rawDesc = "" +
	"\n" +
	")pluggableharness/agent/tool/v1/tool.proto\x12\x1epluggableharness.agent.tool.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a-pluggableharness/agent/config/v1/config.proto\x1a-pluggableharness/agent/render/v1/render.proto\x1a-pluggableharness/agent/schema/v1/schema.proto\x1a9pluggableharness/agent/slashcommand/v1/slashcommand.proto\"\x12\n" +
	"\x10GetSchemaRequest\"\x8b\x02\n" +
	"\x11GetSchemaResponse\x12@\n" +
	"\x05tools\x18\x01 \x03(\v2*.pluggableharness.agent.tool.v1.ToolSchemaR\x05tools\x12_\n" +
	"\x0eslash_commands\x18\x02 \x03(\v28.pluggableharness.agent.slashcommand.v1.SlashCommandSpecR\rslashCommands\x12S\n" +
	"\rconfig_schema\x18\x03 \x01(\v2..pluggableharness.agent.config.v1.ConfigSchemaR\fconfigSchema\"C\n" +
	"\x10ConfigureRequest\x12/\n" +
	"\x06config\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06config\"\x13\n" +
	"\x11ConfigureResponse\"D\n" +
	"\x0fConcurrencySpec\x12\x12\n" +
	"\x04safe\x18\x01 \x01(\bR\x04safe\x12\x1d\n" +
	"\n" +
	"key_fields\x18\x02 \x03(\tR\tkeyFields\"\xcc\x03\n" +
	"\n" +
	"ToolSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12<\n" +
	"\x04kind\x18\x02 \x01(\x0e2(.pluggableharness.agent.tool.v1.ToolKindR\x04kind\x12=\n" +
	"\x04risk\x18\x03 \x01(\x0e2).pluggableharness.agent.tool.v1.RiskClassR\x04risk\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12K\n" +
	"\finput_schema\x18\x05 \x01(\v2(.pluggableharness.agent.schema.v1.SchemaR\vinputSchema\x12M\n" +
	"\routput_schema\x18\x06 \x01(\v2(.pluggableharness.agent.schema.v1.SchemaR\foutputSchema\x12\x1c\n" +
	"\tstreaming\x18\a \x01(\bR\tstreaming\x12Q\n" +
	"\vconcurrency\x18\b \x01(\v2/.pluggableharness.agent.tool.v1.ConcurrencySpecR\vconcurrency\"M\n" +
	"\rInvokeRequest\x12<\n" +
	"\x04call\x18\x01 \x01(\v2(.pluggableharness.agent.tool.v1.ToolCallR\x04call\"Q\n" +
	"\x0eInvokeResponse\x12?\n" +
	"\x05event\x18\x01 \x01(\v2).pluggableharness.agent.tool.v1.ToolEventR\x05event\"n\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\"\xf4\x06\n" +
	"\tToolEvent\x12Z\n" +
	"\foutput_chunk\x18\x01 \x01(\v25.pluggableharness.agent.tool.v1.ToolEvent.OutputChunkH\x00R\voutputChunk\x12P\n" +
	"\bprogress\x18\x02 \x01(\v22.pluggableharness.agent.tool.v1.ToolEvent.ProgressH\x00R\bprogress\x12`\n" +
	"\x0epartial_result\x18\x03 \x01(\v27.pluggableharness.agent.tool.v1.ToolEvent.PartialResultH\x00R\rpartialResult\x12W\n" +
	"\vexit_status\x18\x04 \x01(\v24.pluggableharness.agent.tool.v1.ToolEvent.ExitStatusH\x00R\n" +
	"exitStatus\x12D\n" +
	"\x06result\x18\x05 \x01(\v2*.pluggableharness.agent.tool.v1.ToolResultH\x00R\x06result\x12A\n" +
	"\x05error\x18\x06 \x01(\v2).pluggableharness.agent.tool.v1.ToolErrorH\x00R\x05error\x1ag\n" +
	"\vOutputChunk\x12D\n" +
	"\x06stream\x18\x01 \x01(\x0e2,.pluggableharness.agent.tool.v1.OutputStreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x1al\n" +
	"\bProgress\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x120\n" +
	"\x11fraction_complete\x18\x02 \x01(\x01H\x00R\x10fractionComplete\x88\x01\x01B\x14\n" +
	"\x12_fraction_complete\x1aB\n" +
	"\rPartialResult\x121\n" +
	"\apayload\x18\x01 \x01(\v2\x17.google.protobuf.StructR\apayload\x1aQ\n" +
	"\n" +
	"ExitStatus\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1b\n" +
	"\x06signal\x18\x02 \x01(\tH\x00R\x06signal\x88\x01\x01B\t\n" +
	"\a_signalB\a\n" +
	"\x05event\"?\n" +
	"\n" +
	"ToolResult\x121\n" +
	"\apayload\x18\x01 \x01(\v2\x17.google.protobuf.StructR\apayload\"\xd6\x01\n" +
	"\tToolError\x12M\n" +
	"\bcategory\x18\x01 \x01(\x0e21.pluggableharness.agent.tool.v1.ToolErrorCategoryR\bcategory\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x126\n" +
	"\adetails\x18\x04 \x01(\v2\x17.google.protobuf.StructH\x00R\adetails\x88\x01\x01B\n" +
	"\n" +
	"\b_details\")\n" +
	"\rRenderRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\"R\n" +
	"\x0eRenderResponse\x12@\n" +
	"\x04tree\x18\x01 \x01(\v2,.pluggableharness.agent.render.v1.RenderTreeR\x04tree*s\n" +
	"\bToolKind\x12\x19\n" +
	"\x15TOOL_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TOOL_KIND_RESOURCE\x10\x01\x12\x19\n" +
	"\x15TOOL_KIND_DATA_SOURCE\x10\x02\x12\x19\n" +
	"\x15TOOL_KIND_INTERACTIVE\x10\x03*\x9c\x01\n" +
	"\tRiskClass\x12\x1a\n" +
	"\x16RISK_CLASS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RISK_CLASS_READ_ONLY\x10\x01\x12\x12\n" +
	"\x0eRISK_CLASS_LOW\x10\x02\x12\x17\n" +
	"\x13RISK_CLASS_MODERATE\x10\x03\x12\x13\n" +
	"\x0fRISK_CLASS_HIGH\x10\x04\x12\x17\n" +
	"\x13RISK_CLASS_CRITICAL\x10\x05*a\n" +
	"\fOutputStream\x12\x1d\n" +
	"\x19OUTPUT_STREAM_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OUTPUT_STREAM_STDOUT\x10\x01\x12\x18\n" +
	"\x14OUTPUT_STREAM_STDERR\x10\x02*\x97\x03\n" +
	"\x11ToolErrorCategory\x12#\n" +
	"\x1fTOOL_ERROR_CATEGORY_UNSPECIFIED\x10\x00\x12)\n" +
	"%TOOL_ERROR_CATEGORY_INVALID_ARGUMENTS\x10\x01\x12!\n" +
	"\x1dTOOL_ERROR_CATEGORY_NOT_FOUND\x10\x02\x12)\n" +
	"%TOOL_ERROR_CATEGORY_PERMISSION_DENIED\x10\x03\x12(\n" +
	"$TOOL_ERROR_CATEGORY_EXECUTION_FAILED\x10\x04\x12\x1f\n" +
	"\x1bTOOL_ERROR_CATEGORY_TIMEOUT\x10\x05\x12,\n" +
	"(TOOL_ERROR_CATEGORY_CONCURRENCY_CONFLICT\x10\x06\x12!\n" +
	"\x1dTOOL_ERROR_CATEGORY_CANCELLED\x10\a\x12'\n" +
	"#TOOL_ERROR_CATEGORY_PROCESS_CRASHED\x10\b\x12\x1f\n" +
	"\x1bTOOL_ERROR_CATEGORY_UNKNOWN\x10\t2\xc5\x03\n" +
	"\vToolService\x12p\n" +
	"\tGetSchema\x120.pluggableharness.agent.tool.v1.GetSchemaRequest\x1a1.pluggableharness.agent.tool.v1.GetSchemaResponse\x12p\n" +
	"\tConfigure\x120.pluggableharness.agent.tool.v1.ConfigureRequest\x1a1.pluggableharness.agent.tool.v1.ConfigureResponse\x12i\n" +
	"\x06Invoke\x12-.pluggableharness.agent.tool.v1.InvokeRequest\x1a..pluggableharness.agent.tool.v1.InvokeResponse0\x01\x12g\n" +
	"\x06Render\x12-.pluggableharness.agent.tool.v1.RenderRequest\x1a..pluggableharness.agent.tool.v1.RenderResponseB<Z:github.com/pluggableharness/agent/pkg/tool/proto/v1;toolv1b\x06proto3"

var (
	file_pluggableharness_agent_tool_v1_tool_proto_rawDescOnce sync.Once
	file_pluggableharness_agent_tool_v1_tool_proto_rawDescData []byte
)

func file_pluggableharness_agent_tool_v1_tool_proto_rawDescGZIP() []byte {
	file_pluggableharness_agent_tool_v1_tool_proto_rawDescOnce.Do(func() {
		file_pluggableharness_agent_tool_v1_tool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_agent_tool_v1_tool_proto_rawDesc), len(file_pluggableharness_agent_tool_v1_tool_proto_rawDesc)))
	})
	return file_pluggableharness_agent_tool_v1_tool_proto_rawDescData
}

var file_pluggableharness_agent_tool_v1_tool_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_pluggableharness_agent_tool_v1_tool_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pluggableharness_agent_tool_v1_tool_proto_goTypes = []any{
	(ToolKind)(0),                   // 0: pluggableharness.agent.tool.v1.ToolKind
	(RiskClass)(0),                  // 1: pluggableharness.agent.tool.v1.RiskClass
	(OutputStream)(0),               // 2: pluggableharness.agent.tool.v1.OutputStream
	(ToolErrorCategory)(0),          // 3: pluggableharness.agent.tool.v1.ToolErrorCategory
	(*GetSchemaRequest)(nil),        // 4: pluggableharness.agent.tool.v1.GetSchemaRequest
	(*GetSchemaResponse)(nil),       // 5: pluggableharness.agent.tool.v1.GetSchemaResponse
	(*ConfigureRequest)(nil),        // 6: pluggableharness.agent.tool.v1.ConfigureRequest
	(*ConfigureResponse)(nil),       // 7: pluggableharness.agent.tool.v1.ConfigureResponse
	(*ConcurrencySpec)(nil),         // 8: pluggableharness.agent.tool.v1.ConcurrencySpec
	(*ToolSchema)(nil),              // 9: pluggableharness.agent.tool.v1.ToolSchema
	(*InvokeRequest)(nil),           // 10: pluggableharness.agent.tool.v1.InvokeRequest
	(*InvokeResponse)(nil),          // 11: pluggableharness.agent.tool.v1.InvokeResponse
	(*ToolCall)(nil),                // 12: pluggableharness.agent.tool.v1.ToolCall
	(*ToolEvent)(nil),               // 13: pluggableharness.agent.tool.v1.ToolEvent
	(*ToolResult)(nil),              // 14: pluggableharness.agent.tool.v1.ToolResult
	(*ToolError)(nil),               // 15: pluggableharness.agent.tool.v1.ToolError
	(*RenderRequest)(nil),           // 16: pluggableharness.agent.tool.v1.RenderRequest
	(*RenderResponse)(nil),          // 17: pluggableharness.agent.tool.v1.RenderResponse
	(*ToolEvent_OutputChunk)(nil),   // 18: pluggableharness.agent.tool.v1.ToolEvent.OutputChunk
	(*ToolEvent_Progress)(nil),      // 19: pluggableharness.agent.tool.v1.ToolEvent.Progress
	(*ToolEvent_PartialResult)(nil), // 20: pluggableharness.agent.tool.v1.ToolEvent.PartialResult
	(*ToolEvent_ExitStatus)(nil),    // 21: pluggableharness.agent.tool.v1.ToolEvent.ExitStatus
	(*v1.SlashCommandSpec)(nil),     // 22: pluggableharness.agent.slashcommand.v1.SlashCommandSpec
	(*v11.ConfigSchema)(nil),        // 23: pluggableharness.agent.config.v1.ConfigSchema
	(*structpb.Struct)(nil),         // 24: google.protobuf.Struct
	(*v12.Schema)(nil),              // 25: pluggableharness.agent.schema.v1.Schema
	(*v13.RenderTree)(nil),          // 26: pluggableharness.agent.render.v1.RenderTree
}
var file_pluggableharness_agent_tool_v1_tool_proto_depIdxs = []int32{
	9,  // 0: pluggableharness.agent.tool.v1.GetSchemaResponse.tools:type_name -> pluggableharness.agent.tool.v1.ToolSchema
	22, // 1: pluggableharness.agent.tool.v1.GetSchemaResponse.slash_commands:type_name -> pluggableharness.agent.slashcommand.v1.SlashCommandSpec
	23, // 2: pluggableharness.agent.tool.v1.GetSchemaResponse.config_schema:type_name -> pluggableharness.agent.config.v1.ConfigSchema
	24, // 3: pluggableharness.agent.tool.v1.ConfigureRequest.config:type_name -> google.protobuf.Struct
	0,  // 4: pluggableharness.agent.tool.v1.ToolSchema.kind:type_name -> pluggableharness.agent.tool.v1.ToolKind
	1,  // 5: pluggableharness.agent.tool.v1.ToolSchema.risk:type_name -> pluggableharness.agent.tool.v1.RiskClass
	25, // 6: pluggableharness.agent.tool.v1.ToolSchema.input_schema:type_name -> pluggableharness.agent.schema.v1.Schema
	25, // 7: pluggableharness.agent.tool.v1.ToolSchema.output_schema:type_name -> pluggableharness.agent.schema.v1.Schema
	8,  // 8: pluggableharness.agent.tool.v1.ToolSchema.concurrency:type_name -> pluggableharness.agent.tool.v1.ConcurrencySpec
	12, // 9: pluggableharness.agent.tool.v1.InvokeRequest.call:type_name -> pluggableharness.agent.tool.v1.ToolCall
	13, // 10: pluggableharness.agent.tool.v1.InvokeResponse.event:type_name -> pluggableharness.agent.tool.v1.ToolEvent
	24, // 11: pluggableharness.agent.tool.v1.ToolCall.arguments:type_name -> google.protobuf.Struct
	18, // 12: pluggableharness.agent.tool.v1.ToolEvent.output_chunk:type_name -> pluggableharness.agent.tool.v1.ToolEvent.OutputChunk
	19, // 13: pluggableharness.agent.tool.v1.ToolEvent.progress:type_name -> pluggableharness.agent.tool.v1.ToolEvent.Progress
	20, // 14: pluggableharness.agent.tool.v1.ToolEvent.partial_result:type_name -> pluggableharness.agent.tool.v1.ToolEvent.PartialResult
	21, // 15: pluggableharness.agent.tool.v1.ToolEvent.exit_status:type_name -> pluggableharness.agent.tool.v1.ToolEvent.ExitStatus
	14, // 16: pluggableharness.agent.tool.v1.ToolEvent.result:type_name -> pluggableharness.agent.tool.v1.ToolResult
	15, // 17: pluggableharness.agent.tool.v1.ToolEvent.error:type_name -> pluggableharness.agent.tool.v1.ToolError
	24, // 18: pluggableharness.agent.tool.v1.ToolResult.payload:type_name -> google.protobuf.Struct
	3,  // 19: pluggableharness.agent.tool.v1.ToolError.category:type_name -> pluggableharness.agent.tool.v1.ToolErrorCategory
	24, // 20: pluggableharness.agent.tool.v1.ToolError.details:type_name -> google.protobuf.Struct
	26, // 21: pluggableharness.agent.tool.v1.RenderResponse.tree:type_name -> pluggableharness.agent.render.v1.RenderTree
	2,  // 22: pluggableharness.agent.tool.v1.ToolEvent.OutputChunk.stream:type_name -> pluggableharness.agent.tool.v1.OutputStream
	24, // 23: pluggableharness.agent.tool.v1.ToolEvent.PartialResult.payload:type_name -> google.protobuf.Struct
	4,  // 24: pluggableharness.agent.tool.v1.ToolService.GetSchema:input_type -> pluggableharness.agent.tool.v1.GetSchemaRequest
	6,  // 25: pluggableharness.agent.tool.v1.ToolService.Configure:input_type -> pluggableharness.agent.tool.v1.ConfigureRequest
	10, // 26: pluggableharness.agent.tool.v1.ToolService.Invoke:input_type -> pluggableharness.agent.tool.v1.InvokeRequest
	16, // 27: pluggableharness.agent.tool.v1.ToolService.Render:input_type -> pluggableharness.agent.tool.v1.RenderRequest
	5,  // 28: pluggableharness.agent.tool.v1.ToolService.GetSchema:output_type -> pluggableharness.agent.tool.v1.GetSchemaResponse
	7,  // 29: pluggableharness.agent.tool.v1.ToolService.Configure:output_type -> pluggableharness.agent.tool.v1.ConfigureResponse
	11, // 30: pluggableharness.agent.tool.v1.ToolService.Invoke:output_type -> pluggableharness.agent.tool.v1.InvokeResponse
	17, // 31: pluggableharness.agent.tool.v1.ToolService.Render:output_type -> pluggableharness.agent.tool.v1.RenderResponse
	28, // [28:32] is the sub-list for method output_type
	24, // [24:28] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_pluggableharness_agent_tool_v1_tool_proto_init() }
func file_pluggableharness_agent_tool_v1_tool_proto_init() {
	if File_pluggableharness_agent_tool_v1_tool_proto != nil {
		return
	}
	file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[9].OneofWrappers = []any{
		(*ToolEvent_OutputChunk_)(nil),
		(*ToolEvent_Progress_)(nil),
		(*ToolEvent_PartialResult_)(nil),
		(*ToolEvent_ExitStatus_)(nil),
		(*ToolEvent_Result)(nil),
		(*ToolEvent_Error)(nil),
	}
	file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[11].OneofWrappers = []any{}
	file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[15].OneofWrappers = []any{}
	file_pluggableharness_agent_tool_v1_tool_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_agent_tool_v1_tool_proto_rawDesc), len(file_pluggableharness_agent_tool_v1_tool_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluggableharness_agent_tool_v1_tool_proto_goTypes,
		DependencyIndexes: file_pluggableharness_agent_tool_v1_tool_proto_depIdxs,
		EnumInfos:         file_pluggableharness_agent_tool_v1_tool_proto_enumTypes,
		MessageInfos:      file_pluggableharness_agent_tool_v1_tool_proto_msgTypes,
	}.Build()
	File_pluggableharness_agent_tool_v1_tool_proto = out.File
	file_pluggableharness_agent_tool_v1_tool_proto_goTypes = nil
	file_pluggableharness_agent_tool_v1_tool_proto_depIdxs = nil
}
