// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/tool/v1/types.proto

package toolv1

import (
	v11 "github.com/pluggableharness/agent/pkg/common/proto/v1"
	v1 "github.com/pluggableharness/agent/pkg/schema/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ToolKind is the axis that drives the plan/apply gate, per tool.md §2.
// Deliberately separate from RiskClass: kind is the binary the gate
// mechanically needs, risk is a finer-grained classification within it.
type ToolKind int32

const (
	// Zero value. Never valid for a real operation; its presence on the wire
	// means a caller forgot to set the field.
	ToolKind_TOOL_KIND_UNSPECIFIED ToolKind = 0
	// Mutating. Gated behind the plan/apply approval gate.
	ToolKind_TOOL_KIND_RESOURCE ToolKind = 1
	// Read-only. Executes freely, subject only to the policy precheck
	// (agent-loop.md §5.4).
	ToolKind_TOOL_KIND_DATA_SOURCE ToolKind = 2
	// Blocks the current turn for human input, per tool.md §2.1. Produces no
	// state mutation of its own — the human's answer becomes the result.
	ToolKind_TOOL_KIND_INTERACTIVE ToolKind = 3
)

// Enum value maps for ToolKind.
var (
	ToolKind_name = map[int32]string{
		0: "TOOL_KIND_UNSPECIFIED",
		1: "TOOL_KIND_RESOURCE",
		2: "TOOL_KIND_DATA_SOURCE",
		3: "TOOL_KIND_INTERACTIVE",
	}
	ToolKind_value = map[string]int32{
		"TOOL_KIND_UNSPECIFIED": 0,
		"TOOL_KIND_RESOURCE":    1,
		"TOOL_KIND_DATA_SOURCE": 2,
		"TOOL_KIND_INTERACTIVE": 3,
	}
)

func (x ToolKind) Enum() *ToolKind {
	p := new(ToolKind)
	*p = x
	return p
}

func (x ToolKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolKind) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_tool_v1_types_proto_enumTypes[0].Descriptor()
}

func (ToolKind) Type() protoreflect.EnumType {
	return &file_pluggableharness_tool_v1_types_proto_enumTypes[0]
}

func (x ToolKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolKind.Descriptor instead.
func (ToolKind) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_types_proto_rawDescGZIP(), []int{0}
}

// RiskClass classifies an operation's blast radius, per tool.md §2. Orthogonal
// to ToolKind: kind determines whether the plan/apply gate applies at all,
// risk determines how significant the gated (or inherently ungated) action is.
type RiskClass int32

const (
	// Zero value. Never valid for a real operation; its presence on the wire
	// means a caller forgot to set the field.
	RiskClass_RISK_CLASS_UNSPECIFIED RiskClass = 0
	// Inherently unable to mutate anything the plugin controls. MUST be used
	// for TOOL_KIND_DATA_SOURCE and TOOL_KIND_INTERACTIVE alike — neither
	// mutates nor reads anything external, so neither has a blast radius to
	// classify.
	RiskClass_RISK_CLASS_READ_ONLY RiskClass = 1
	// A resource operation with narrow, easily-reversible blast radius, e.g.
	// a write to a scratch path.
	RiskClass_RISK_CLASS_LOW RiskClass = 2
	// A resource operation with real but bounded blast radius, e.g. editing
	// a tracked source file.
	RiskClass_RISK_CLASS_MODERATE RiskClass = 3
	// A resource operation with broad or hard-to-predict blast radius, e.g.
	// arbitrary shell execution.
	RiskClass_RISK_CLASS_HIGH RiskClass = 4
	// A resource operation capable of irreversible or wide-blast-radius
	// action, e.g. `rm -rf`, a force-push, or spawning a sub-agent with
	// further unattended write access.
	//
	// A TOOL_KIND_RESOURCE operation MUST declare one of LOW/MODERATE/HIGH/
	// CRITICAL — never READ_ONLY. There is no resource with read_only risk.
	RiskClass_RISK_CLASS_CRITICAL RiskClass = 5
)

// Enum value maps for RiskClass.
var (
	RiskClass_name = map[int32]string{
		0: "RISK_CLASS_UNSPECIFIED",
		1: "RISK_CLASS_READ_ONLY",
		2: "RISK_CLASS_LOW",
		3: "RISK_CLASS_MODERATE",
		4: "RISK_CLASS_HIGH",
		5: "RISK_CLASS_CRITICAL",
	}
	RiskClass_value = map[string]int32{
		"RISK_CLASS_UNSPECIFIED": 0,
		"RISK_CLASS_READ_ONLY":   1,
		"RISK_CLASS_LOW":         2,
		"RISK_CLASS_MODERATE":    3,
		"RISK_CLASS_HIGH":        4,
		"RISK_CLASS_CRITICAL":    5,
	}
)

func (x RiskClass) Enum() *RiskClass {
	p := new(RiskClass)
	*p = x
	return p
}

func (x RiskClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskClass) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_tool_v1_types_proto_enumTypes[1].Descriptor()
}

func (RiskClass) Type() protoreflect.EnumType {
	return &file_pluggableharness_tool_v1_types_proto_enumTypes[1]
}

func (x RiskClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskClass.Descriptor instead.
func (RiskClass) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_types_proto_rawDescGZIP(), []int{1}
}

// ConcurrencySpec declares whether this operation's Invoke calls may run
// concurrently against the same provider process, per tool.md §5.
type ConcurrencySpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MUST be set, per operation, except for TOOL_KIND_INTERACTIVE. false (or
	// an absent/unset default) means the kernel MUST NOT run any other Invoke
	// call against this provider process concurrently with this one — a
	// coarse, provider-wide lock. true means concurrent Invoke calls against
	// this provider are generally safe. A provider that does not populate
	// this field at all MUST be treated by the kernel as false — the
	// conservative default.
	Safe bool `protobuf:"varint,1,opt,name=safe,proto3" json:"safe,omitempty"`
	// Only meaningful when safe == true. Names of this operation's
	// input_schema fields whose value(s) form a serialization key. The
	// kernel computes key = (provider_name, tool_name, value(key_fields)) and
	// MUST serialize calls sharing an identical key, while still freely
	// parallelizing calls with distinct keys. Omitting key_fields under
	// safe == true asserts that no two calls to this operation can ever
	// conflict — a strong claim, true for e.g. web_search, false for e.g.
	// write_file.
	KeyFields     []string `protobuf:"bytes,2,rep,name=key_fields,json=keyFields,proto3" json:"key_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcurrencySpec) Reset() {
	*x = ConcurrencySpec{}
	mi := &file_pluggableharness_tool_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcurrencySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcurrencySpec) ProtoMessage() {}

func (x *ConcurrencySpec) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcurrencySpec.ProtoReflect.Descriptor instead.
func (*ConcurrencySpec) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *ConcurrencySpec) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *ConcurrencySpec) GetKeyFields() []string {
	if x != nil {
		return x.KeyFields
	}
	return nil
}

// ToolSchema declares one operation this provider exposes, per tool.md §2.
type ToolSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MUST — unique within this provider's namespace, e.g. "read_file".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// MUST — drives the plan/apply gate.
	Kind ToolKind `protobuf:"varint,2,opt,name=kind,proto3,enum=pluggableharness.tool.v1.ToolKind" json:"kind,omitempty"`
	// MUST — see RiskClass.
	Risk RiskClass `protobuf:"varint,3,opt,name=risk,proto3,enum=pluggableharness.tool.v1.RiskClass" json:"risk,omitempty"`
	// MUST — shown to the model for tool selection and in plan diffs.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// MUST — the common JSON-Schema subset per model.md §6, describing the
	// shape of ToolCall.arguments for this operation.
	InputSchema *v1.Schema `protobuf:"bytes,5,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	// MUST — the common JSON-Schema subset per model.md §6, describing the
	// shape of ToolResult.payload for this operation.
	OutputSchema *v1.Schema `protobuf:"bytes,6,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	// MUST — true if Invoke may emit intermediate ToolEvents (output_chunk,
	// progress, partial_result) before the terminal event; false if Invoke
	// always emits exactly one terminal event with no lead-up.
	Streaming bool `protobuf:"varint,7,opt,name=streaming,proto3" json:"streaming,omitempty"`
	// MUST, except MUST NOT be meaningfully set for TOOL_KIND_INTERACTIVE.
	Concurrency *ConcurrencySpec `protobuf:"bytes,8,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	// SHOULD — the deadline the kernel applies to Invoke for this operation
	// absent an agent.hcl override. Absent means the kernel's global default
	// applies instead (configuration/settings-and-global.md).
	DefaultTimeout *durationpb.Duration `protobuf:"bytes,9,opt,name=default_timeout,json=defaultTimeout,proto3,oneof" json:"default_timeout,omitempty"`
	// True iff re-running this operation with identical arguments cannot
	// produce a different end state than running it once. Gates whether the
	// kernel MAY auto-retry a retryable ToolError for a TOOL_KIND_RESOURCE
	// operation — see conformance.md#error-taxonomy's retry interaction.
	// TOOL_KIND_DATA_SOURCE operations are implicitly safe to retry
	// regardless of this field.
	Idempotent    bool `protobuf:"varint,10,opt,name=idempotent,proto3" json:"idempotent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolSchema) Reset() {
	*x = ToolSchema{}
	mi := &file_pluggableharness_tool_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolSchema) ProtoMessage() {}

func (x *ToolSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolSchema.ProtoReflect.Descriptor instead.
func (*ToolSchema) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *ToolSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolSchema) GetKind() ToolKind {
	if x != nil {
		return x.Kind
	}
	return ToolKind_TOOL_KIND_UNSPECIFIED
}

func (x *ToolSchema) GetRisk() RiskClass {
	if x != nil {
		return x.Risk
	}
	return RiskClass_RISK_CLASS_UNSPECIFIED
}

func (x *ToolSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolSchema) GetInputSchema() *v1.Schema {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *ToolSchema) GetOutputSchema() *v1.Schema {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *ToolSchema) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

func (x *ToolSchema) GetConcurrency() *ConcurrencySpec {
	if x != nil {
		return x.Concurrency
	}
	return nil
}

func (x *ToolSchema) GetDefaultTimeout() *durationpb.Duration {
	if x != nil {
		return x.DefaultTimeout
	}
	return nil
}

func (x *ToolSchema) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

// ToolCall is one request to execute an operation, per tool.md §4.
type ToolCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MUST — kernel-assigned. Echoed in every ToolEvent for this call, for
	// correlation.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// MUST — matches a ToolSchema.name from this provider's GetSchema
	// response.
	ToolName string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// MUST — already-parsed JSON conforming to that ToolSchema's
	// input_schema.
	Arguments *structpb.Struct `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"`
	// MUST be set by the kernel. Carries the session_id/turn_id this call
	// executes for — what the plugin echoes back on its own
	// KernelCallbackService.Emit/Log calls for attribution — and the
	// session's working_directory, which any process-backed operation
	// (the reference catalog's exec.bash, read_file, and similar) MUST
	// resolve relative-path arguments against. See
	// pluggableharness.common.v1.CallContext.
	CallContext   *v11.CallContext `protobuf:"bytes,4,opt,name=call_context,json=callContext,proto3" json:"call_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_pluggableharness_tool_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCall) GetArguments() *structpb.Struct {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ToolCall) GetCallContext() *v11.CallContext {
	if x != nil {
		return x.CallContext
	}
	return nil
}

// ToolResult is the terminal, successful outcome of an Invoke call.
type ToolResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MUST conform to the ToolSchema.output_schema declared for this call's
	// tool_name; the kernel strictly validates this — a non-conforming
	// payload becomes a ToolError with category TOOL_ERROR_CATEGORY_UNKNOWN
	// rather than being passed through to history.
	Payload       *structpb.Struct `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResult) Reset() {
	*x = ToolResult{}
	mi := &file_pluggableharness_tool_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResult) ProtoMessage() {}

func (x *ToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_tool_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResult.ProtoReflect.Descriptor instead.
func (*ToolResult) Descriptor() ([]byte, []int) {
	return file_pluggableharness_tool_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *ToolResult) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pluggableharness_tool_v1_types_proto protoreflect.FileDescriptor

const file_pluggableharness_tool_v1_types_proto_rawDesc = "" +
	"\n" +
	"$pluggableharness/tool/v1/types.proto\x12\x18pluggableharness.tool.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a&pluggableharness/common/v1/types.proto\x1a&pluggableharness/schema/v1/types.proto\"D\n" +
	"\x0fConcurrencySpec\x12\x12\n" +
	"\x04safe\x18\x01 \x01(\bR\x04safe\x12\x1d\n" +
	"\n" +
	"key_fields\x18\x02 \x03(\tR\tkeyFields\"\xab\x04\n" +
	"\n" +
	"ToolSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x04kind\x18\x02 \x01(\x0e2\".pluggableharness.tool.v1.ToolKindR\x04kind\x127\n" +
	"\x04risk\x18\x03 \x01(\x0e2#.pluggableharness.tool.v1.RiskClassR\x04risk\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12E\n" +
	"\finput_schema\x18\x05 \x01(\v2\".pluggableharness.schema.v1.SchemaR\vinputSchema\x12G\n" +
	"\routput_schema\x18\x06 \x01(\v2\".pluggableharness.schema.v1.SchemaR\foutputSchema\x12\x1c\n" +
	"\tstreaming\x18\a \x01(\bR\tstreaming\x12K\n" +
	"\vconcurrency\x18\b \x01(\v2).pluggableharness.tool.v1.ConcurrencySpecR\vconcurrency\x12G\n" +
	"\x0fdefault_timeout\x18\t \x01(\v2\x19.google.protobuf.DurationH\x00R\x0edefaultTimeout\x88\x01\x01\x12\x1e\n" +
	"\n" +
	"idempotent\x18\n" +
	" \x01(\bR\n" +
	"idempotentB\x12\n" +
	"\x10_default_timeout\"\xba\x01\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x125\n" +
	"\targuments\x18\x03 \x01(\v2\x17.google.protobuf.StructR\targuments\x12J\n" +
	"\fcall_context\x18\x04 \x01(\v2'.pluggableharness.common.v1.CallContextR\vcallContext\"?\n" +
	"\n" +
	"ToolResult\x121\n" +
	"\apayload\x18\x01 \x01(\v2\x17.google.protobuf.StructR\apayload*s\n" +
	"\bToolKind\x12\x19\n" +
	"\x15TOOL_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TOOL_KIND_RESOURCE\x10\x01\x12\x19\n" +
	"\x15TOOL_KIND_DATA_SOURCE\x10\x02\x12\x19\n" +
	"\x15TOOL_KIND_INTERACTIVE\x10\x03*\x9c\x01\n" +
	"\tRiskClass\x12\x1a\n" +
	"\x16RISK_CLASS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RISK_CLASS_READ_ONLY\x10\x01\x12\x12\n" +
	"\x0eRISK_CLASS_LOW\x10\x02\x12\x17\n" +
	"\x13RISK_CLASS_MODERATE\x10\x03\x12\x13\n" +
	"\x0fRISK_CLASS_HIGH\x10\x04\x12\x17\n" +
	"\x13RISK_CLASS_CRITICAL\x10\x05B<Z:github.com/pluggableharness/agent/pkg/tool/proto/v1;toolv1b\x06proto3"

var (
	file_pluggableharness_tool_v1_types_proto_rawDescOnce sync.Once
	file_pluggableharness_tool_v1_types_proto_rawDescData []byte
)

func file_pluggableharness_tool_v1_types_proto_rawDescGZIP() []byte {
	file_pluggableharness_tool_v1_types_proto_rawDescOnce.Do(func() {
		file_pluggableharness_tool_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_tool_v1_types_proto_rawDesc), len(file_pluggableharness_tool_v1_types_proto_rawDesc)))
	})
	return file_pluggableharness_tool_v1_types_proto_rawDescData
}

var file_pluggableharness_tool_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pluggableharness_tool_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pluggableharness_tool_v1_types_proto_goTypes = []any{
	(ToolKind)(0),               // 0: pluggableharness.tool.v1.ToolKind
	(RiskClass)(0),              // 1: pluggableharness.tool.v1.RiskClass
	(*ConcurrencySpec)(nil),     // 2: pluggableharness.tool.v1.ConcurrencySpec
	(*ToolSchema)(nil),          // 3: pluggableharness.tool.v1.ToolSchema
	(*ToolCall)(nil),            // 4: pluggableharness.tool.v1.ToolCall
	(*ToolResult)(nil),          // 5: pluggableharness.tool.v1.ToolResult
	(*v1.Schema)(nil),           // 6: pluggableharness.schema.v1.Schema
	(*durationpb.Duration)(nil), // 7: google.protobuf.Duration
	(*structpb.Struct)(nil),     // 8: google.protobuf.Struct
	(*v11.CallContext)(nil),     // 9: pluggableharness.common.v1.CallContext
}
var file_pluggableharness_tool_v1_types_proto_depIdxs = []int32{
	0, // 0: pluggableharness.tool.v1.ToolSchema.kind:type_name -> pluggableharness.tool.v1.ToolKind
	1, // 1: pluggableharness.tool.v1.ToolSchema.risk:type_name -> pluggableharness.tool.v1.RiskClass
	6, // 2: pluggableharness.tool.v1.ToolSchema.input_schema:type_name -> pluggableharness.schema.v1.Schema
	6, // 3: pluggableharness.tool.v1.ToolSchema.output_schema:type_name -> pluggableharness.schema.v1.Schema
	2, // 4: pluggableharness.tool.v1.ToolSchema.concurrency:type_name -> pluggableharness.tool.v1.ConcurrencySpec
	7, // 5: pluggableharness.tool.v1.ToolSchema.default_timeout:type_name -> google.protobuf.Duration
	8, // 6: pluggableharness.tool.v1.ToolCall.arguments:type_name -> google.protobuf.Struct
	9, // 7: pluggableharness.tool.v1.ToolCall.call_context:type_name -> pluggableharness.common.v1.CallContext
	8, // 8: pluggableharness.tool.v1.ToolResult.payload:type_name -> google.protobuf.Struct
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_pluggableharness_tool_v1_types_proto_init() }
func file_pluggableharness_tool_v1_types_proto_init() {
	if File_pluggableharness_tool_v1_types_proto != nil {
		return
	}
	file_pluggableharness_tool_v1_types_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_tool_v1_types_proto_rawDesc), len(file_pluggableharness_tool_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_tool_v1_types_proto_goTypes,
		DependencyIndexes: file_pluggableharness_tool_v1_types_proto_depIdxs,
		EnumInfos:         file_pluggableharness_tool_v1_types_proto_enumTypes,
		MessageInfos:      file_pluggableharness_tool_v1_types_proto_msgTypes,
	}.Build()
	File_pluggableharness_tool_v1_types_proto = out.File
	file_pluggableharness_tool_v1_types_proto_goTypes = nil
	file_pluggableharness_tool_v1_types_proto_depIdxs = nil
}
