// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pluggableharness/kernel/v1/kernel.proto

// Package pluggableharness.kernel.v1 defines the kernel-callback service described
// in specifications/kernel-callbacks.md (RunSession, CountTokens, Emit,
// Log) — the plugin-to-kernel calling direction every plugin category gets
// at handshake, the reverse of every other category's protocol in this
// series. Unlike a category plugin protocol, this service carries no
// GetCapabilities/Configure RPCs: it isn't something the kernel dials into
// a plugin, it's the connection every plugin subprocess is handed back to
// call into the kernel.

package kernelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelCallbackService_RunSession_FullMethodName  = "/pluggableharness.kernel.v1.KernelCallbackService/RunSession"
	KernelCallbackService_CountTokens_FullMethodName = "/pluggableharness.kernel.v1.KernelCallbackService/CountTokens"
	KernelCallbackService_Emit_FullMethodName        = "/pluggableharness.kernel.v1.KernelCallbackService/Emit"
	KernelCallbackService_Log_FullMethodName         = "/pluggableharness.kernel.v1.KernelCallbackService/Log"
)

// KernelCallbackServiceClient is the client API for KernelCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KernelCallbackService is the plugin-to-kernel callback channel described
// in specifications/kernel-callbacks.md §1. hashicorp/go-plugin natively
// supports bidirectional plugins, and this is that mechanism: every plugin
// subprocess, for every category defined across this series, MUST be given
// a client connection to this service at handshake time, unconditionally.
// A plugin that never calls back simply never uses it, but the channel's
// presence is not gated on category — a context provider needing
// CountTokens is just as valid a caller as a tool provider needing
// RunSession.
type KernelCallbackServiceClient interface {
	// RunSession dispatches a nested sub-agent session under a named
	// agent.hcl profile. Full semantics — profile resolution, budget
	// inheritance, visibility of intermediate turns — are defined in
	// agent-loop.md §7 and are not repeated here; kernel-callbacks.md §1
	// gives this RPC's calling contract.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// Response type is "RunSessionResult", the exact name agent-loop.md §7.1
	// uses in its own data-type definition. Not a uniqueness violation:
	// RunSessionResult is used by exactly this one RPC.
	RunSession(ctx context.Context, in *RunSessionRequest, opts ...grpc.CallOption) (*RunSessionResult, error)
	// CountTokens resolves the token-counting gap independently flagged by
	// context.md §12, configuration.md §12, memory.md §13, and frontend.md
	// §10: exactly one kernel-owned implementation, so that `tokens` figures
	// produced by different providers stay mutually comparable and additive
	// for configuration.md §6's budget-sum arithmetic. See
	// kernel-callbacks.md §2 for the resolution algorithm and §3 for the
	// single documented fallback formula.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// Response type is "CountTokensResult", the exact name kernel-callbacks.md
	// §2 uses. Not a uniqueness violation: used by exactly this one RPC.
	CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResult, error)
	// Emit is how a plugin persists anything into the session's state
	// backend. The kernel is the state backend's sole writer
	// (state-backend.md §3) — a plugin never opens or writes the sqlite file
	// directly; it calls Emit and the kernel performs the actual write,
	// assigning the ordering-authoritative sequence number and the stable
	// event id itself. See kernel-callbacks.md §4.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// Response type is "EmitResult", the exact name kernel-callbacks.md §4
	// uses. Not a uniqueness violation: used by exactly this one RPC.
	Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResult, error)
	// Log carries a plugin's own log output into the kernel's centralized
	// logging, so it doesn't vanish into an unread subprocess stderr.
	// Unlike Emit, a Log call is not tied to an active session — a plugin
	// MAY call Log before any session exists (process startup, or from
	// within Configure) or after one has ended (during shutdown). See
	// kernel-callbacks.md §5.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// Response type is "LogResult", the exact name kernel-callbacks.md §5
	// uses. Not a uniqueness violation: used by exactly this one RPC.
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResult, error)
}

type kernelCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelCallbackServiceClient(cc grpc.ClientConnInterface) KernelCallbackServiceClient {
	return &kernelCallbackServiceClient{cc}
}

func (c *kernelCallbackServiceClient) RunSession(ctx context.Context, in *RunSessionRequest, opts ...grpc.CallOption) (*RunSessionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSessionResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_RunSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountTokensResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_CountTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelCallbackServiceServer is the server API for KernelCallbackService service.
// All implementations must embed UnimplementedKernelCallbackServiceServer
// for forward compatibility.
//
// KernelCallbackService is the plugin-to-kernel callback channel described
// in specifications/kernel-callbacks.md §1. hashicorp/go-plugin natively
// supports bidirectional plugins, and this is that mechanism: every plugin
// subprocess, for every category defined across this series, MUST be given
// a client connection to this service at handshake time, unconditionally.
// A plugin that never calls back simply never uses it, but the channel's
// presence is not gated on category — a context provider needing
// CountTokens is just as valid a caller as a tool provider needing
// RunSession.
type KernelCallbackServiceServer interface {
	// RunSession dispatches a nested sub-agent session under a named
	// agent.hcl profile. Full semantics — profile resolution, budget
	// inheritance, visibility of intermediate turns — are defined in
	// agent-loop.md §7 and are not repeated here; kernel-callbacks.md §1
	// gives this RPC's calling contract.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// Response type is "RunSessionResult", the exact name agent-loop.md §7.1
	// uses in its own data-type definition. Not a uniqueness violation:
	// RunSessionResult is used by exactly this one RPC.
	RunSession(context.Context, *RunSessionRequest) (*RunSessionResult, error)
	// CountTokens resolves the token-counting gap independently flagged by
	// context.md §12, configuration.md §12, memory.md §13, and frontend.md
	// §10: exactly one kernel-owned implementation, so that `tokens` figures
	// produced by different providers stay mutually comparable and additive
	// for configuration.md §6's budget-sum arithmetic. See
	// kernel-callbacks.md §2 for the resolution algorithm and §3 for the
	// single documented fallback formula.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// Response type is "CountTokensResult", the exact name kernel-callbacks.md
	// §2 uses. Not a uniqueness violation: used by exactly this one RPC.
	CountTokens(context.Context, *CountTokensRequest) (*CountTokensResult, error)
	// Emit is how a plugin persists anything into the session's state
	// backend. The kernel is the state backend's sole writer
	// (state-backend.md §3) — a plugin never opens or writes the sqlite file
	// directly; it calls Emit and the kernel performs the actual write,
	// assigning the ordering-authoritative sequence number and the stable
	// event id itself. See kernel-callbacks.md §4.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// Response type is "EmitResult", the exact name kernel-callbacks.md §4
	// uses. Not a uniqueness violation: used by exactly this one RPC.
	Emit(context.Context, *EmitRequest) (*EmitResult, error)
	// Log carries a plugin's own log output into the kernel's centralized
	// logging, so it doesn't vanish into an unread subprocess stderr.
	// Unlike Emit, a Log call is not tied to an active session — a plugin
	// MAY call Log before any session exists (process startup, or from
	// within Configure) or after one has ended (during shutdown). See
	// kernel-callbacks.md §5.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	// Response type is "LogResult", the exact name kernel-callbacks.md §5
	// uses. Not a uniqueness violation: used by exactly this one RPC.
	Log(context.Context, *LogRequest) (*LogResult, error)
	mustEmbedUnimplementedKernelCallbackServiceServer()
}

// UnimplementedKernelCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelCallbackServiceServer struct{}

func (UnimplementedKernelCallbackServiceServer) RunSession(context.Context, *RunSessionRequest) (*RunSessionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSession not implemented")
}
func (UnimplementedKernelCallbackServiceServer) CountTokens(context.Context, *CountTokensRequest) (*CountTokensResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CountTokens not implemented")
}
func (UnimplementedKernelCallbackServiceServer) Emit(context.Context, *EmitRequest) (*EmitResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedKernelCallbackServiceServer) Log(context.Context, *LogRequest) (*LogResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedKernelCallbackServiceServer) mustEmbedUnimplementedKernelCallbackServiceServer() {}
func (UnimplementedKernelCallbackServiceServer) testEmbeddedByValue()                               {}

// UnsafeKernelCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelCallbackServiceServer will
// result in compilation errors.
type UnsafeKernelCallbackServiceServer interface {
	mustEmbedUnimplementedKernelCallbackServiceServer()
}

func RegisterKernelCallbackServiceServer(s grpc.ServiceRegistrar, srv KernelCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedKernelCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelCallbackService_ServiceDesc, srv)
}

func _KernelCallbackService_RunSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).RunSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_RunSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).RunSession(ctx, req.(*RunSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_CountTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).CountTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_CountTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).CountTokens(ctx, req.(*CountTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).Emit(ctx, req.(*EmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KernelCallbackService_ServiceDesc is the grpc.ServiceDesc for KernelCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pluggableharness.kernel.v1.KernelCallbackService",
	HandlerType: (*KernelCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunSession",
			Handler:    _KernelCallbackService_RunSession_Handler,
		},
		{
			MethodName: "CountTokens",
			Handler:    _KernelCallbackService_CountTokens_Handler,
		},
		{
			MethodName: "Emit",
			Handler:    _KernelCallbackService_Emit_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _KernelCallbackService_Log_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pluggableharness/kernel/v1/kernel.proto",
}
