// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: pluggableharness/kernel/v1/service.proto

// Package pluggableharness.kernel.v1 defines the kernel-callback service
// described in specifications/kernel-callbacks.md — the plugin-to-kernel
// calling direction every plugin category gets at handshake, the reverse
// of every other category's protocol in this series. Unlike a category
// plugin protocol, this service carries no GetCapabilities/Configure
// RPCs: it is not something the kernel dials into a plugin, it is the
// connection every plugin subprocess is handed back to call into the
// kernel.
//
// Frontend state surfaces (input, state, metadata, transcript backfill,
// token deltas) also live here: under go-plugin the plugin is the gRPC
// server, so kernel-push streams and frontend-originated control both
// use this channel rather than a category Attach RPC.

package kernelv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KernelCallbackService_RunSession_FullMethodName          = "/pluggableharness.kernel.v1.KernelCallbackService/RunSession"
	KernelCallbackService_CountTokens_FullMethodName         = "/pluggableharness.kernel.v1.KernelCallbackService/CountTokens"
	KernelCallbackService_Emit_FullMethodName                = "/pluggableharness.kernel.v1.KernelCallbackService/Emit"
	KernelCallbackService_Log_FullMethodName                 = "/pluggableharness.kernel.v1.KernelCallbackService/Log"
	KernelCallbackService_ExportSpans_FullMethodName         = "/pluggableharness.kernel.v1.KernelCallbackService/ExportSpans"
	KernelCallbackService_RecordMetrics_FullMethodName       = "/pluggableharness.kernel.v1.KernelCallbackService/RecordMetrics"
	KernelCallbackService_GetTelemetryConfig_FullMethodName  = "/pluggableharness.kernel.v1.KernelCallbackService/GetTelemetryConfig"
	KernelCallbackService_GetConfig_FullMethodName           = "/pluggableharness.kernel.v1.KernelCallbackService/GetConfig"
	KernelCallbackService_Publish_FullMethodName             = "/pluggableharness.kernel.v1.KernelCallbackService/Publish"
	KernelCallbackService_Subscribe_FullMethodName           = "/pluggableharness.kernel.v1.KernelCallbackService/Subscribe"
	KernelCallbackService_ReadEvents_FullMethodName          = "/pluggableharness.kernel.v1.KernelCallbackService/ReadEvents"
	KernelCallbackService_GetSession_FullMethodName          = "/pluggableharness.kernel.v1.KernelCallbackService/GetSession"
	KernelCallbackService_GetSessionState_FullMethodName     = "/pluggableharness.kernel.v1.KernelCallbackService/GetSessionState"
	KernelCallbackService_SubmitInput_FullMethodName         = "/pluggableharness.kernel.v1.KernelCallbackService/SubmitInput"
	KernelCallbackService_ResolvePlanDecision_FullMethodName = "/pluggableharness.kernel.v1.KernelCallbackService/ResolvePlanDecision"
	KernelCallbackService_ResolveInteractive_FullMethodName  = "/pluggableharness.kernel.v1.KernelCallbackService/ResolveInteractive"
	KernelCallbackService_Interrupt_FullMethodName           = "/pluggableharness.kernel.v1.KernelCallbackService/Interrupt"
	KernelCallbackService_CreateSession_FullMethodName       = "/pluggableharness.kernel.v1.KernelCallbackService/CreateSession"
	KernelCallbackService_AttachSession_FullMethodName       = "/pluggableharness.kernel.v1.KernelCallbackService/AttachSession"
	KernelCallbackService_ResumeSession_FullMethodName       = "/pluggableharness.kernel.v1.KernelCallbackService/ResumeSession"
	KernelCallbackService_DetachSession_FullMethodName       = "/pluggableharness.kernel.v1.KernelCallbackService/DetachSession"
	KernelCallbackService_ListSessions_FullMethodName        = "/pluggableharness.kernel.v1.KernelCallbackService/ListSessions"
	KernelCallbackService_PublishMetadata_FullMethodName     = "/pluggableharness.kernel.v1.KernelCallbackService/PublishMetadata"
	KernelCallbackService_RetractMetadata_FullMethodName     = "/pluggableharness.kernel.v1.KernelCallbackService/RetractMetadata"
	KernelCallbackService_ListMetadata_FullMethodName        = "/pluggableharness.kernel.v1.KernelCallbackService/ListMetadata"
	KernelCallbackService_StreamDeltas_FullMethodName        = "/pluggableharness.kernel.v1.KernelCallbackService/StreamDeltas"
	KernelCallbackService_InvokeSlashCommand_FullMethodName  = "/pluggableharness.kernel.v1.KernelCallbackService/InvokeSlashCommand"
	KernelCallbackService_TriggerAction_FullMethodName       = "/pluggableharness.kernel.v1.KernelCallbackService/TriggerAction"
)

// KernelCallbackServiceClient is the client API for KernelCallbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KernelCallbackService is the plugin-to-kernel callback channel described
// in specifications/kernel-callbacks.md. hashicorp/go-plugin natively
// supports bidirectional plugins, and this is that mechanism: every plugin
// subprocess, for every category, MUST be given a client connection to
// this service at handshake time, unconditionally.
//
// Application RPCs are unary or server-streaming. The connection itself is
// bidirectional at the transport layer; that is the only genuinely
// bidirectional surface in the protocol series (there is no category
// Attach stream).
type KernelCallbackServiceClient interface {
	// RunSession dispatches a nested sub-agent session under a named
	// agent.hcl profile. Full semantics live in agent-loop/subagents.md.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	RunSession(ctx context.Context, in *RunSessionRequest, opts ...grpc.CallOption) (*RunSessionResult, error)
	// CountTokens resolves the token-counting gap: exactly one kernel-owned
	// implementation so tokens figures stay mutually comparable.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResult, error)
	// Emit is how a plugin persists anything into the session's state
	// backend. The kernel is the sole writer.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResult, error)
	// Log carries a plugin's own log output into the kernel's centralized
	// logging.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResult, error)
	// ExportSpans relays a batch of a plugin's own completed trace spans.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ExportSpans(ctx context.Context, in *ExportSpansRequest, opts ...grpc.CallOption) (*ExportSpansResult, error)
	// RecordMetrics relays a batch of metric observations (bounded
	// attributes; not a transparent relay).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	RecordMetrics(ctx context.Context, in *RecordMetricsRequest, opts ...grpc.CallOption) (*RecordMetricsResult, error)
	// GetTelemetryConfig answers whether tracing/metrics/logs are enabled.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetTelemetryConfig(ctx context.Context, in *GetTelemetryConfigRequest, opts ...grpc.CallOption) (*GetTelemetryConfigResult, error)
	// GetConfig returns the calling plugin's own already-decoded agent.hcl
	// configuration.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResult, error)
	// Publish emits one event onto the ephemeral event bus.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResult, error)
	// Subscribe opens a server-streaming subscription to the event bus.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BusEvent], error)
	// ReadEvents reads back the calling plugin's own session's persisted
	// event log, ordered by sequence.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ReadEvents(ctx context.Context, in *ReadEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StoredEvent], error)
	// GetSession returns the calling plugin's own session's metadata plus
	// its live budget rollups.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResult, error)
	// GetSessionState returns the fixed-schema "where am I" snapshot for
	// one session. Pair with Subscribe on topic kernel.state for deltas.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetSessionState(ctx context.Context, in *GetSessionStateRequest, opts ...grpc.CallOption) (*GetSessionStateResult, error)
	// SubmitInput submits operator input as the next turn. Returns the
	// assigned turn_id for correlation.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	SubmitInput(ctx context.Context, in *SubmitInputRequest, opts ...grpc.CallOption) (*SubmitInputResult, error)
	// ResolvePlanDecision answers a pending plan item (policy ASK).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResolvePlanDecision(ctx context.Context, in *ResolvePlanDecisionRequest, opts ...grpc.CallOption) (*ResolvePlanDecisionResult, error)
	// ResolveInteractive answers a pending interactive-kind tool call.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResolveInteractive(ctx context.Context, in *ResolveInteractiveRequest, opts ...grpc.CallOption) (*ResolveInteractiveResult, error)
	// Interrupt cancels the running turn for a session.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResult, error)
	// CreateSession creates a new session and auto-attaches the caller.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResult, error)
	// AttachSession subscribes the caller to an existing session.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	AttachSession(ctx context.Context, in *AttachSessionRequest, opts ...grpc.CallOption) (*AttachSessionResult, error)
	// ResumeSession attaches a historical session for continuation or
	// replay-only.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResumeSession(ctx context.Context, in *ResumeSessionRequest, opts ...grpc.CallOption) (*ResumeSessionResult, error)
	// DetachSession unsubscribes the caller from a session.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	DetachSession(ctx context.Context, in *DetachSessionRequest, opts ...grpc.CallOption) (*DetachSessionResult, error)
	// ListSessions returns a filtered session summary list.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResult, error)
	// PublishMetadata upserts a MetadataBlock (producer and liveness
	// server-stamped).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	PublishMetadata(ctx context.Context, in *PublishMetadataRequest, opts ...grpc.CallOption) (*PublishMetadataResult, error)
	// RetractMetadata flips a block to DISCONNECTED and republishes; never
	// deletes.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	RetractMetadata(ctx context.Context, in *RetractMetadataRequest, opts ...grpc.CallOption) (*RetractMetadataResult, error)
	// ListMetadata returns every known MetadataBlock for a session
	// (snapshot half of snapshot-then-subscribe).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ListMetadata(ctx context.Context, in *ListMetadataRequest, opts ...grpc.CallOption) (*ListMetadataResult, error)
	// StreamDeltas is the live-only token fast path: server-streaming on
	// this channel, out-of-band with respect to the event bus. The kernel
	// does not batch; frontends coalesce to their own refresh.
	//
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamDeltas(ctx context.Context, in *StreamDeltasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenDelta], error)
	// InvokeSlashCommand dispatches a slash command against a session.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	InvokeSlashCommand(ctx context.Context, in *InvokeSlashCommandRequest, opts ...grpc.CallOption) (*InvokeSlashCommandResult, error)
	// TriggerAction dispatches an ActionNode activation (no model turn).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	TriggerAction(ctx context.Context, in *TriggerActionRequest, opts ...grpc.CallOption) (*TriggerActionResult, error)
}

type kernelCallbackServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKernelCallbackServiceClient(cc grpc.ClientConnInterface) KernelCallbackServiceClient {
	return &kernelCallbackServiceClient{cc}
}

func (c *kernelCallbackServiceClient) RunSession(ctx context.Context, in *RunSessionRequest, opts ...grpc.CallOption) (*RunSessionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunSessionResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_RunSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) CountTokens(ctx context.Context, in *CountTokensRequest, opts ...grpc.CallOption) (*CountTokensResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountTokensResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_CountTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) Emit(ctx context.Context, in *EmitRequest, opts ...grpc.CallOption) (*EmitResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_Emit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) Log(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_Log_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) ExportSpans(ctx context.Context, in *ExportSpansRequest, opts ...grpc.CallOption) (*ExportSpansResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSpansResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_ExportSpans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) RecordMetrics(ctx context.Context, in *RecordMetricsRequest, opts ...grpc.CallOption) (*RecordMetricsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordMetricsResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_RecordMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) GetTelemetryConfig(ctx context.Context, in *GetTelemetryConfigRequest, opts ...grpc.CallOption) (*GetTelemetryConfigResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTelemetryConfigResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_GetTelemetryConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BusEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelCallbackService_ServiceDesc.Streams[0], KernelCallbackService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, BusEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelCallbackService_SubscribeClient = grpc.ServerStreamingClient[BusEvent]

func (c *kernelCallbackServiceClient) ReadEvents(ctx context.Context, in *ReadEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StoredEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelCallbackService_ServiceDesc.Streams[1], KernelCallbackService_ReadEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadEventsRequest, StoredEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelCallbackService_ReadEventsClient = grpc.ServerStreamingClient[StoredEvent]

func (c *kernelCallbackServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) GetSessionState(ctx context.Context, in *GetSessionStateRequest, opts ...grpc.CallOption) (*GetSessionStateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionStateResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_GetSessionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) SubmitInput(ctx context.Context, in *SubmitInputRequest, opts ...grpc.CallOption) (*SubmitInputResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitInputResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_SubmitInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) ResolvePlanDecision(ctx context.Context, in *ResolvePlanDecisionRequest, opts ...grpc.CallOption) (*ResolvePlanDecisionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolvePlanDecisionResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_ResolvePlanDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) ResolveInteractive(ctx context.Context, in *ResolveInteractiveRequest, opts ...grpc.CallOption) (*ResolveInteractiveResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveInteractiveResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_ResolveInteractive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) Interrupt(ctx context.Context, in *InterruptRequest, opts ...grpc.CallOption) (*InterruptResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InterruptResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_Interrupt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) AttachSession(ctx context.Context, in *AttachSessionRequest, opts ...grpc.CallOption) (*AttachSessionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachSessionResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_AttachSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) ResumeSession(ctx context.Context, in *ResumeSessionRequest, opts ...grpc.CallOption) (*ResumeSessionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeSessionResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_ResumeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) DetachSession(ctx context.Context, in *DetachSessionRequest, opts ...grpc.CallOption) (*DetachSessionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachSessionResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_DetachSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) PublishMetadata(ctx context.Context, in *PublishMetadataRequest, opts ...grpc.CallOption) (*PublishMetadataResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishMetadataResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_PublishMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) RetractMetadata(ctx context.Context, in *RetractMetadataRequest, opts ...grpc.CallOption) (*RetractMetadataResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetractMetadataResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_RetractMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) ListMetadata(ctx context.Context, in *ListMetadataRequest, opts ...grpc.CallOption) (*ListMetadataResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMetadataResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_ListMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) StreamDeltas(ctx context.Context, in *StreamDeltasRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TokenDelta], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KernelCallbackService_ServiceDesc.Streams[2], KernelCallbackService_StreamDeltas_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamDeltasRequest, TokenDelta]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelCallbackService_StreamDeltasClient = grpc.ServerStreamingClient[TokenDelta]

func (c *kernelCallbackServiceClient) InvokeSlashCommand(ctx context.Context, in *InvokeSlashCommandRequest, opts ...grpc.CallOption) (*InvokeSlashCommandResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeSlashCommandResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_InvokeSlashCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kernelCallbackServiceClient) TriggerAction(ctx context.Context, in *TriggerActionRequest, opts ...grpc.CallOption) (*TriggerActionResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerActionResult)
	err := c.cc.Invoke(ctx, KernelCallbackService_TriggerAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KernelCallbackServiceServer is the server API for KernelCallbackService service.
// All implementations must embed UnimplementedKernelCallbackServiceServer
// for forward compatibility.
//
// KernelCallbackService is the plugin-to-kernel callback channel described
// in specifications/kernel-callbacks.md. hashicorp/go-plugin natively
// supports bidirectional plugins, and this is that mechanism: every plugin
// subprocess, for every category, MUST be given a client connection to
// this service at handshake time, unconditionally.
//
// Application RPCs are unary or server-streaming. The connection itself is
// bidirectional at the transport layer; that is the only genuinely
// bidirectional surface in the protocol series (there is no category
// Attach stream).
type KernelCallbackServiceServer interface {
	// RunSession dispatches a nested sub-agent session under a named
	// agent.hcl profile. Full semantics live in agent-loop/subagents.md.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	RunSession(context.Context, *RunSessionRequest) (*RunSessionResult, error)
	// CountTokens resolves the token-counting gap: exactly one kernel-owned
	// implementation so tokens figures stay mutually comparable.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	CountTokens(context.Context, *CountTokensRequest) (*CountTokensResult, error)
	// Emit is how a plugin persists anything into the session's state
	// backend. The kernel is the sole writer.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Emit(context.Context, *EmitRequest) (*EmitResult, error)
	// Log carries a plugin's own log output into the kernel's centralized
	// logging.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Log(context.Context, *LogRequest) (*LogResult, error)
	// ExportSpans relays a batch of a plugin's own completed trace spans.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ExportSpans(context.Context, *ExportSpansRequest) (*ExportSpansResult, error)
	// RecordMetrics relays a batch of metric observations (bounded
	// attributes; not a transparent relay).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	RecordMetrics(context.Context, *RecordMetricsRequest) (*RecordMetricsResult, error)
	// GetTelemetryConfig answers whether tracing/metrics/logs are enabled.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetTelemetryConfig(context.Context, *GetTelemetryConfigRequest) (*GetTelemetryConfigResult, error)
	// GetConfig returns the calling plugin's own already-decoded agent.hcl
	// configuration.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResult, error)
	// Publish emits one event onto the ephemeral event bus.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Publish(context.Context, *PublishRequest) (*PublishResult, error)
	// Subscribe opens a server-streaming subscription to the event bus.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[BusEvent]) error
	// ReadEvents reads back the calling plugin's own session's persisted
	// event log, ordered by sequence.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ReadEvents(*ReadEventsRequest, grpc.ServerStreamingServer[StoredEvent]) error
	// GetSession returns the calling plugin's own session's metadata plus
	// its live budget rollups.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResult, error)
	// GetSessionState returns the fixed-schema "where am I" snapshot for
	// one session. Pair with Subscribe on topic kernel.state for deltas.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetSessionState(context.Context, *GetSessionStateRequest) (*GetSessionStateResult, error)
	// SubmitInput submits operator input as the next turn. Returns the
	// assigned turn_id for correlation.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	SubmitInput(context.Context, *SubmitInputRequest) (*SubmitInputResult, error)
	// ResolvePlanDecision answers a pending plan item (policy ASK).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResolvePlanDecision(context.Context, *ResolvePlanDecisionRequest) (*ResolvePlanDecisionResult, error)
	// ResolveInteractive answers a pending interactive-kind tool call.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResolveInteractive(context.Context, *ResolveInteractiveRequest) (*ResolveInteractiveResult, error)
	// Interrupt cancels the running turn for a session.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	Interrupt(context.Context, *InterruptRequest) (*InterruptResult, error)
	// CreateSession creates a new session and auto-attaches the caller.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResult, error)
	// AttachSession subscribes the caller to an existing session.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	AttachSession(context.Context, *AttachSessionRequest) (*AttachSessionResult, error)
	// ResumeSession attaches a historical session for continuation or
	// replay-only.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ResumeSession(context.Context, *ResumeSessionRequest) (*ResumeSessionResult, error)
	// DetachSession unsubscribes the caller from a session.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	DetachSession(context.Context, *DetachSessionRequest) (*DetachSessionResult, error)
	// ListSessions returns a filtered session summary list.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResult, error)
	// PublishMetadata upserts a MetadataBlock (producer and liveness
	// server-stamped).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	PublishMetadata(context.Context, *PublishMetadataRequest) (*PublishMetadataResult, error)
	// RetractMetadata flips a block to DISCONNECTED and republishes; never
	// deletes.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	RetractMetadata(context.Context, *RetractMetadataRequest) (*RetractMetadataResult, error)
	// ListMetadata returns every known MetadataBlock for a session
	// (snapshot half of snapshot-then-subscribe).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	ListMetadata(context.Context, *ListMetadataRequest) (*ListMetadataResult, error)
	// StreamDeltas is the live-only token fast path: server-streaming on
	// this channel, out-of-band with respect to the event bus. The kernel
	// does not batch; frontends coalesce to their own refresh.
	//
	// buf:lint:ignore RPC_REQUEST_STANDARD_NAME
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	StreamDeltas(*StreamDeltasRequest, grpc.ServerStreamingServer[TokenDelta]) error
	// InvokeSlashCommand dispatches a slash command against a session.
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	InvokeSlashCommand(context.Context, *InvokeSlashCommandRequest) (*InvokeSlashCommandResult, error)
	// TriggerAction dispatches an ActionNode activation (no model turn).
	//
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	TriggerAction(context.Context, *TriggerActionRequest) (*TriggerActionResult, error)
	mustEmbedUnimplementedKernelCallbackServiceServer()
}

// UnimplementedKernelCallbackServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKernelCallbackServiceServer struct{}

func (UnimplementedKernelCallbackServiceServer) RunSession(context.Context, *RunSessionRequest) (*RunSessionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RunSession not implemented")
}
func (UnimplementedKernelCallbackServiceServer) CountTokens(context.Context, *CountTokensRequest) (*CountTokensResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CountTokens not implemented")
}
func (UnimplementedKernelCallbackServiceServer) Emit(context.Context, *EmitRequest) (*EmitResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Emit not implemented")
}
func (UnimplementedKernelCallbackServiceServer) Log(context.Context, *LogRequest) (*LogResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Log not implemented")
}
func (UnimplementedKernelCallbackServiceServer) ExportSpans(context.Context, *ExportSpansRequest) (*ExportSpansResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSpans not implemented")
}
func (UnimplementedKernelCallbackServiceServer) RecordMetrics(context.Context, *RecordMetricsRequest) (*RecordMetricsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordMetrics not implemented")
}
func (UnimplementedKernelCallbackServiceServer) GetTelemetryConfig(context.Context, *GetTelemetryConfigRequest) (*GetTelemetryConfigResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTelemetryConfig not implemented")
}
func (UnimplementedKernelCallbackServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedKernelCallbackServiceServer) Publish(context.Context, *PublishRequest) (*PublishResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedKernelCallbackServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[BusEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedKernelCallbackServiceServer) ReadEvents(*ReadEventsRequest, grpc.ServerStreamingServer[StoredEvent]) error {
	return status.Error(codes.Unimplemented, "method ReadEvents not implemented")
}
func (UnimplementedKernelCallbackServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedKernelCallbackServiceServer) GetSessionState(context.Context, *GetSessionStateRequest) (*GetSessionStateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionState not implemented")
}
func (UnimplementedKernelCallbackServiceServer) SubmitInput(context.Context, *SubmitInputRequest) (*SubmitInputResult, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitInput not implemented")
}
func (UnimplementedKernelCallbackServiceServer) ResolvePlanDecision(context.Context, *ResolvePlanDecisionRequest) (*ResolvePlanDecisionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolvePlanDecision not implemented")
}
func (UnimplementedKernelCallbackServiceServer) ResolveInteractive(context.Context, *ResolveInteractiveRequest) (*ResolveInteractiveResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveInteractive not implemented")
}
func (UnimplementedKernelCallbackServiceServer) Interrupt(context.Context, *InterruptRequest) (*InterruptResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Interrupt not implemented")
}
func (UnimplementedKernelCallbackServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedKernelCallbackServiceServer) AttachSession(context.Context, *AttachSessionRequest) (*AttachSessionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachSession not implemented")
}
func (UnimplementedKernelCallbackServiceServer) ResumeSession(context.Context, *ResumeSessionRequest) (*ResumeSessionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeSession not implemented")
}
func (UnimplementedKernelCallbackServiceServer) DetachSession(context.Context, *DetachSessionRequest) (*DetachSessionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachSession not implemented")
}
func (UnimplementedKernelCallbackServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedKernelCallbackServiceServer) PublishMetadata(context.Context, *PublishMetadataRequest) (*PublishMetadataResult, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishMetadata not implemented")
}
func (UnimplementedKernelCallbackServiceServer) RetractMetadata(context.Context, *RetractMetadataRequest) (*RetractMetadataResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RetractMetadata not implemented")
}
func (UnimplementedKernelCallbackServiceServer) ListMetadata(context.Context, *ListMetadataRequest) (*ListMetadataResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMetadata not implemented")
}
func (UnimplementedKernelCallbackServiceServer) StreamDeltas(*StreamDeltasRequest, grpc.ServerStreamingServer[TokenDelta]) error {
	return status.Error(codes.Unimplemented, "method StreamDeltas not implemented")
}
func (UnimplementedKernelCallbackServiceServer) InvokeSlashCommand(context.Context, *InvokeSlashCommandRequest) (*InvokeSlashCommandResult, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeSlashCommand not implemented")
}
func (UnimplementedKernelCallbackServiceServer) TriggerAction(context.Context, *TriggerActionRequest) (*TriggerActionResult, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerAction not implemented")
}
func (UnimplementedKernelCallbackServiceServer) mustEmbedUnimplementedKernelCallbackServiceServer() {}
func (UnimplementedKernelCallbackServiceServer) testEmbeddedByValue()                               {}

// UnsafeKernelCallbackServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KernelCallbackServiceServer will
// result in compilation errors.
type UnsafeKernelCallbackServiceServer interface {
	mustEmbedUnimplementedKernelCallbackServiceServer()
}

func RegisterKernelCallbackServiceServer(s grpc.ServiceRegistrar, srv KernelCallbackServiceServer) {
	// If the following call panics, it indicates UnimplementedKernelCallbackServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KernelCallbackService_ServiceDesc, srv)
}

func _KernelCallbackService_RunSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).RunSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_RunSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).RunSession(ctx, req.(*RunSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_CountTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).CountTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_CountTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).CountTokens(ctx, req.(*CountTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_Emit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).Emit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_Emit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).Emit(ctx, req.(*EmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_Log_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).Log(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_ExportSpans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSpansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).ExportSpans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_ExportSpans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).ExportSpans(ctx, req.(*ExportSpansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_RecordMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).RecordMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_RecordMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).RecordMetrics(ctx, req.(*RecordMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_GetTelemetryConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelemetryConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).GetTelemetryConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_GetTelemetryConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).GetTelemetryConfig(ctx, req.(*GetTelemetryConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelCallbackServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, BusEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelCallbackService_SubscribeServer = grpc.ServerStreamingServer[BusEvent]

func _KernelCallbackService_ReadEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelCallbackServiceServer).ReadEvents(m, &grpc.GenericServerStream[ReadEventsRequest, StoredEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelCallbackService_ReadEventsServer = grpc.ServerStreamingServer[StoredEvent]

func _KernelCallbackService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_GetSessionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).GetSessionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_GetSessionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).GetSessionState(ctx, req.(*GetSessionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_SubmitInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).SubmitInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_SubmitInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).SubmitInput(ctx, req.(*SubmitInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_ResolvePlanDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePlanDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).ResolvePlanDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_ResolvePlanDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).ResolvePlanDecision(ctx, req.(*ResolvePlanDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_ResolveInteractive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveInteractiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).ResolveInteractive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_ResolveInteractive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).ResolveInteractive(ctx, req.(*ResolveInteractiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_Interrupt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterruptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).Interrupt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_Interrupt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).Interrupt(ctx, req.(*InterruptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_AttachSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).AttachSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_AttachSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).AttachSession(ctx, req.(*AttachSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_ResumeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).ResumeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_ResumeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).ResumeSession(ctx, req.(*ResumeSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_DetachSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).DetachSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_DetachSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).DetachSession(ctx, req.(*DetachSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_PublishMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).PublishMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_PublishMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).PublishMetadata(ctx, req.(*PublishMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_RetractMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetractMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).RetractMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_RetractMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).RetractMetadata(ctx, req.(*RetractMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_ListMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).ListMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_ListMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).ListMetadata(ctx, req.(*ListMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_StreamDeltas_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamDeltasRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(KernelCallbackServiceServer).StreamDeltas(m, &grpc.GenericServerStream[StreamDeltasRequest, TokenDelta]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KernelCallbackService_StreamDeltasServer = grpc.ServerStreamingServer[TokenDelta]

func _KernelCallbackService_InvokeSlashCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeSlashCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).InvokeSlashCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_InvokeSlashCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).InvokeSlashCommand(ctx, req.(*InvokeSlashCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KernelCallbackService_TriggerAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KernelCallbackServiceServer).TriggerAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KernelCallbackService_TriggerAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KernelCallbackServiceServer).TriggerAction(ctx, req.(*TriggerActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KernelCallbackService_ServiceDesc is the grpc.ServiceDesc for KernelCallbackService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KernelCallbackService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pluggableharness.kernel.v1.KernelCallbackService",
	HandlerType: (*KernelCallbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunSession",
			Handler:    _KernelCallbackService_RunSession_Handler,
		},
		{
			MethodName: "CountTokens",
			Handler:    _KernelCallbackService_CountTokens_Handler,
		},
		{
			MethodName: "Emit",
			Handler:    _KernelCallbackService_Emit_Handler,
		},
		{
			MethodName: "Log",
			Handler:    _KernelCallbackService_Log_Handler,
		},
		{
			MethodName: "ExportSpans",
			Handler:    _KernelCallbackService_ExportSpans_Handler,
		},
		{
			MethodName: "RecordMetrics",
			Handler:    _KernelCallbackService_RecordMetrics_Handler,
		},
		{
			MethodName: "GetTelemetryConfig",
			Handler:    _KernelCallbackService_GetTelemetryConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _KernelCallbackService_GetConfig_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _KernelCallbackService_Publish_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _KernelCallbackService_GetSession_Handler,
		},
		{
			MethodName: "GetSessionState",
			Handler:    _KernelCallbackService_GetSessionState_Handler,
		},
		{
			MethodName: "SubmitInput",
			Handler:    _KernelCallbackService_SubmitInput_Handler,
		},
		{
			MethodName: "ResolvePlanDecision",
			Handler:    _KernelCallbackService_ResolvePlanDecision_Handler,
		},
		{
			MethodName: "ResolveInteractive",
			Handler:    _KernelCallbackService_ResolveInteractive_Handler,
		},
		{
			MethodName: "Interrupt",
			Handler:    _KernelCallbackService_Interrupt_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _KernelCallbackService_CreateSession_Handler,
		},
		{
			MethodName: "AttachSession",
			Handler:    _KernelCallbackService_AttachSession_Handler,
		},
		{
			MethodName: "ResumeSession",
			Handler:    _KernelCallbackService_ResumeSession_Handler,
		},
		{
			MethodName: "DetachSession",
			Handler:    _KernelCallbackService_DetachSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _KernelCallbackService_ListSessions_Handler,
		},
		{
			MethodName: "PublishMetadata",
			Handler:    _KernelCallbackService_PublishMetadata_Handler,
		},
		{
			MethodName: "RetractMetadata",
			Handler:    _KernelCallbackService_RetractMetadata_Handler,
		},
		{
			MethodName: "ListMetadata",
			Handler:    _KernelCallbackService_ListMetadata_Handler,
		},
		{
			MethodName: "InvokeSlashCommand",
			Handler:    _KernelCallbackService_InvokeSlashCommand_Handler,
		},
		{
			MethodName: "TriggerAction",
			Handler:    _KernelCallbackService_TriggerAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _KernelCallbackService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadEvents",
			Handler:       _KernelCallbackService_ReadEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamDeltas",
			Handler:       _KernelCallbackService_StreamDeltas_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pluggableharness/kernel/v1/service.proto",
}
