// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/agent/config/v1/config.proto

// Package pluggableharness.agent.config.v1 defines the on-the-wire config-schema
// advertisement described in specifications/configuration.md §4. This is
// what a provider returns alongside its capabilities so the kernel knows
// what agent.hcl fields it accepts; the schema-to-cty bridge itself (HCL
// decoding, hcldec, cty.Value) is kernel-internal and never crosses the
// wire — Configure receives already-decoded JSON, not HCL or cty.

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttrType is the small subset of HCL/cty attribute types a provider's
// config schema may use in v1. ATTR_TYPE_OBJECT is the one type with
// structure below the scalar/list/map level — ConfigAttribute.object_attributes
// carries its nested schema, recursively, rather than accepting an
// unvalidated dynamic object (configuration.md §The schema-to-cty bridge).
type AttrType int32

const (
	// Zero value. Never valid for a real attribute; its presence on the wire
	// means a caller forgot to set the field.
	AttrType_ATTR_TYPE_UNSPECIFIED AttrType = 0
	AttrType_ATTR_TYPE_STRING      AttrType = 1
	AttrType_ATTR_TYPE_NUMBER      AttrType = 2
	AttrType_ATTR_TYPE_BOOL        AttrType = 3
	AttrType_ATTR_TYPE_LIST_STRING AttrType = 4
	AttrType_ATTR_TYPE_LIST_NUMBER AttrType = 5
	AttrType_ATTR_TYPE_MAP_STRING  AttrType = 6
	AttrType_ATTR_TYPE_OBJECT      AttrType = 7
)

// Enum value maps for AttrType.
var (
	AttrType_name = map[int32]string{
		0: "ATTR_TYPE_UNSPECIFIED",
		1: "ATTR_TYPE_STRING",
		2: "ATTR_TYPE_NUMBER",
		3: "ATTR_TYPE_BOOL",
		4: "ATTR_TYPE_LIST_STRING",
		5: "ATTR_TYPE_LIST_NUMBER",
		6: "ATTR_TYPE_MAP_STRING",
		7: "ATTR_TYPE_OBJECT",
	}
	AttrType_value = map[string]int32{
		"ATTR_TYPE_UNSPECIFIED": 0,
		"ATTR_TYPE_STRING":      1,
		"ATTR_TYPE_NUMBER":      2,
		"ATTR_TYPE_BOOL":        3,
		"ATTR_TYPE_LIST_STRING": 4,
		"ATTR_TYPE_LIST_NUMBER": 5,
		"ATTR_TYPE_MAP_STRING":  6,
		"ATTR_TYPE_OBJECT":      7,
	}
)

func (x AttrType) Enum() *AttrType {
	p := new(AttrType)
	*p = x
	return p
}

func (x AttrType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttrType) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_agent_config_v1_config_proto_enumTypes[0].Descriptor()
}

func (AttrType) Type() protoreflect.EnumType {
	return &file_pluggableharness_agent_config_v1_config_proto_enumTypes[0]
}

func (x AttrType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttrType.Descriptor instead.
func (AttrType) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_agent_config_v1_config_proto_rawDescGZIP(), []int{0}
}

// ConfigAttribute declares one field a provider's agent.hcl config block
// accepts.
type ConfigAttribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The attribute's name, as it appears in the HCL block body.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The attribute's type.
	Type AttrType `protobuf:"varint,2,opt,name=type,proto3,enum=pluggableharness.agent.config.v1.AttrType" json:"type,omitempty"`
	// Whether agent.hcl MUST set this attribute. The kernel MUST reject a
	// Configure call with a missing required attribute via a structured
	// error, per model.md §3 / tool.md §3's shared Configure contract.
	Required bool `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	// MUST be true for any attribute that can hold a secret (API keys,
	// tokens, credentials). configuration.md §4 restricts a sensitive
	// attribute's HCL expression to env(...) indirection only — the kernel
	// resolves that indirection before Configure ever sees the literal
	// value, and a provider MUST NOT echo a sensitive value into Emit,
	// Render, logs, or errors.
	Sensitive bool `protobuf:"varint,4,opt,name=sensitive,proto3" json:"sensitive,omitempty"`
	// Human-readable description, shown wherever agent.hcl schema is
	// surfaced to an operator (docs generation, validation errors).
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// The nested attribute schema for this attribute's object shape. MUST
	// be set (non-empty) iff type == ATTR_TYPE_OBJECT; MUST be empty for
	// every other type. configuration.md's schema-to-cty bridge decodes
	// this the same way it decodes the provider's own top-level
	// ConfigSchema.attributes, so an object attribute's fields get the same
	// required/sensitive/description treatment as any top-level attribute.
	// One level of nesting is sanctioned per direct ConfigAttribute; deeper
	// nesting is expressed by an entry in object_attributes itself being
	// type == ATTR_TYPE_OBJECT with its own populated object_attributes —
	// the schema is recursive, not flat-capped.
	ObjectAttributes []*ConfigAttribute `protobuf:"bytes,6,rep,name=object_attributes,json=objectAttributes,proto3" json:"object_attributes,omitempty"`
	// A JSON-encoded default value applied when this attribute is optional
	// (required == false) and agent.hcl omits it. Absent means "no default
	// — an omitted optional attribute decodes to that type's cty zero
	// value." String-typed (rather than a typed field per AttrType, or a
	// google.protobuf.Struct/Value) to stay cty-agnostic at the proto
	// level: the kernel's schema-to-cty bridge is the only thing that
	// interprets this string, parsing it as JSON and converting the result
	// to the cty.Value this attribute's type expects — the wire type
	// itself doesn't need to model cty's type system to carry a default
	// through it. A default for an ATTR_TYPE_OBJECT attribute is a
	// JSON object matching object_attributes' shape.
	DefaultJson   *string `protobuf:"bytes,7,opt,name=default_json,json=defaultJson,proto3,oneof" json:"default_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAttribute) Reset() {
	*x = ConfigAttribute{}
	mi := &file_pluggableharness_agent_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAttribute) ProtoMessage() {}

func (x *ConfigAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAttribute.ProtoReflect.Descriptor instead.
func (*ConfigAttribute) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigAttribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigAttribute) GetType() AttrType {
	if x != nil {
		return x.Type
	}
	return AttrType_ATTR_TYPE_UNSPECIFIED
}

func (x *ConfigAttribute) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigAttribute) GetSensitive() bool {
	if x != nil {
		return x.Sensitive
	}
	return false
}

func (x *ConfigAttribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfigAttribute) GetObjectAttributes() []*ConfigAttribute {
	if x != nil {
		return x.ObjectAttributes
	}
	return nil
}

func (x *ConfigAttribute) GetDefaultJson() string {
	if x != nil && x.DefaultJson != nil {
		return *x.DefaultJson
	}
	return ""
}

// ConfigSchema is a provider's complete config-schema advertisement,
// returned alongside its capabilities.
type ConfigSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The provider's declared config attributes.
	Attributes    []*ConfigAttribute `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	mi := &file_pluggableharness_agent_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_agent_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_pluggableharness_agent_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigSchema) GetAttributes() []*ConfigAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_pluggableharness_agent_config_v1_config_proto protoreflect.FileDescriptor

const file_pluggableharness_agent_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"-pluggableharness/agent/config/v1/config.proto\x12 pluggableharness.agent.config.v1\"\xda\x02\n" +
	"\x0fConfigAttribute\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\x04type\x18\x02 \x01(\x0e2*.pluggableharness.agent.config.v1.AttrTypeR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12\x1c\n" +
	"\tsensitive\x18\x04 \x01(\bR\tsensitive\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12^\n" +
	"\x11object_attributes\x18\x06 \x03(\v21.pluggableharness.agent.config.v1.ConfigAttributeR\x10objectAttributes\x12&\n" +
	"\fdefault_json\x18\a \x01(\tH\x00R\vdefaultJson\x88\x01\x01B\x0f\n" +
	"\r_default_json\"a\n" +
	"\fConfigSchema\x12Q\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v21.pluggableharness.agent.config.v1.ConfigAttributeR\n" +
	"attributes*\xcb\x01\n" +
	"\bAttrType\x12\x19\n" +
	"\x15ATTR_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ATTR_TYPE_STRING\x10\x01\x12\x14\n" +
	"\x10ATTR_TYPE_NUMBER\x10\x02\x12\x12\n" +
	"\x0eATTR_TYPE_BOOL\x10\x03\x12\x19\n" +
	"\x15ATTR_TYPE_LIST_STRING\x10\x04\x12\x19\n" +
	"\x15ATTR_TYPE_LIST_NUMBER\x10\x05\x12\x18\n" +
	"\x14ATTR_TYPE_MAP_STRING\x10\x06\x12\x14\n" +
	"\x10ATTR_TYPE_OBJECT\x10\aB@Z>github.com/pluggableharness/agent/pkg/config/proto/v1;configv1b\x06proto3"

var (
	file_pluggableharness_agent_config_v1_config_proto_rawDescOnce sync.Once
	file_pluggableharness_agent_config_v1_config_proto_rawDescData []byte
)

func file_pluggableharness_agent_config_v1_config_proto_rawDescGZIP() []byte {
	file_pluggableharness_agent_config_v1_config_proto_rawDescOnce.Do(func() {
		file_pluggableharness_agent_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_agent_config_v1_config_proto_rawDesc), len(file_pluggableharness_agent_config_v1_config_proto_rawDesc)))
	})
	return file_pluggableharness_agent_config_v1_config_proto_rawDescData
}

var file_pluggableharness_agent_config_v1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pluggableharness_agent_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pluggableharness_agent_config_v1_config_proto_goTypes = []any{
	(AttrType)(0),           // 0: pluggableharness.agent.config.v1.AttrType
	(*ConfigAttribute)(nil), // 1: pluggableharness.agent.config.v1.ConfigAttribute
	(*ConfigSchema)(nil),    // 2: pluggableharness.agent.config.v1.ConfigSchema
}
var file_pluggableharness_agent_config_v1_config_proto_depIdxs = []int32{
	0, // 0: pluggableharness.agent.config.v1.ConfigAttribute.type:type_name -> pluggableharness.agent.config.v1.AttrType
	1, // 1: pluggableharness.agent.config.v1.ConfigAttribute.object_attributes:type_name -> pluggableharness.agent.config.v1.ConfigAttribute
	1, // 2: pluggableharness.agent.config.v1.ConfigSchema.attributes:type_name -> pluggableharness.agent.config.v1.ConfigAttribute
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pluggableharness_agent_config_v1_config_proto_init() }
func file_pluggableharness_agent_config_v1_config_proto_init() {
	if File_pluggableharness_agent_config_v1_config_proto != nil {
		return
	}
	file_pluggableharness_agent_config_v1_config_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_agent_config_v1_config_proto_rawDesc), len(file_pluggableharness_agent_config_v1_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_agent_config_v1_config_proto_goTypes,
		DependencyIndexes: file_pluggableharness_agent_config_v1_config_proto_depIdxs,
		EnumInfos:         file_pluggableharness_agent_config_v1_config_proto_enumTypes,
		MessageInfos:      file_pluggableharness_agent_config_v1_config_proto_msgTypes,
	}.Build()
	File_pluggableharness_agent_config_v1_config_proto = out.File
	file_pluggableharness_agent_config_v1_config_proto_goTypes = nil
	file_pluggableharness_agent_config_v1_config_proto_depIdxs = nil
}
