// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/hook/v1/errors.proto

package hookv1

import (
	v1 "github.com/pluggableharness/agent/pkg/common/proto/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HookErrorCategory classifies why a hook dispatch to one subscriber
// failed. Deliberately its own enum, not reused from tool.v1 or model.v1 —
// per .claude/rules/proto.md, a category proto's error taxonomy is never
// merged with another category's even where the surrounding shape is
// parallel.
type HookErrorCategory int32

const (
	// Zero value. Never valid for a real error; its presence on the wire
	// means a caller forgot to set the field.
	HookErrorCategory_HOOK_ERROR_CATEGORY_UNSPECIFIED HookErrorCategory = 0
	// A transform subscriber raised an error or returned a malformed
	// response. Aborts the remainder of that hook's chain
	// (agent-loop/hook-dispatch.md#subscriber-error-handling).
	HookErrorCategory_HOOK_ERROR_CATEGORY_TRANSFORM_FAILED HookErrorCategory = 1
	// A veto subscriber raised an error. Treated identically to an
	// explicit deny — fail-closed
	// (agent-loop/hook-dispatch.md#subscriber-error-handling).
	HookErrorCategory_HOOK_ERROR_CATEGORY_VETO_FAILED HookErrorCategory = 2
	// The subscriber exceeded its per-subscriber deadline
	// (agent-loop/hook-dispatch.md#timeout-behavior). For a veto
	// subscriber, resolved identically to HOOK_ERROR_CATEGORY_VETO_FAILED —
	// fail-closed deny.
	HookErrorCategory_HOOK_ERROR_CATEGORY_TIMEOUT HookErrorCategory = 3
	// The subscriber's DispatchHookResponse didn't match what its declared
	// HookMode requires — wrong oneof variant, or (for transform) a
	// payload variant that doesn't match the request's, or a mutation to a
	// field this hook point doesn't document as transform-mutable.
	HookErrorCategory_HOOK_ERROR_CATEGORY_INVALID_RESPONSE HookErrorCategory = 4
	// The subscriber's plugin subprocess died mid-dispatch (transport
	// error, not a graceful error the plugin chose to return). MUST be
	// kernel-synthesized only, mirroring
	// tool/conformance.md#error-taxonomy's TOOL_ERROR_CATEGORY_PROCESS_CRASHED
	// — a plugin process that crashes obviously cannot emit this itself.
	HookErrorCategory_HOOK_ERROR_CATEGORY_PROCESS_CRASHED HookErrorCategory = 5
	// Anything else.
	HookErrorCategory_HOOK_ERROR_CATEGORY_UNKNOWN HookErrorCategory = 6
)

// Enum value maps for HookErrorCategory.
var (
	HookErrorCategory_name = map[int32]string{
		0: "HOOK_ERROR_CATEGORY_UNSPECIFIED",
		1: "HOOK_ERROR_CATEGORY_TRANSFORM_FAILED",
		2: "HOOK_ERROR_CATEGORY_VETO_FAILED",
		3: "HOOK_ERROR_CATEGORY_TIMEOUT",
		4: "HOOK_ERROR_CATEGORY_INVALID_RESPONSE",
		5: "HOOK_ERROR_CATEGORY_PROCESS_CRASHED",
		6: "HOOK_ERROR_CATEGORY_UNKNOWN",
	}
	HookErrorCategory_value = map[string]int32{
		"HOOK_ERROR_CATEGORY_UNSPECIFIED":      0,
		"HOOK_ERROR_CATEGORY_TRANSFORM_FAILED": 1,
		"HOOK_ERROR_CATEGORY_VETO_FAILED":      2,
		"HOOK_ERROR_CATEGORY_TIMEOUT":          3,
		"HOOK_ERROR_CATEGORY_INVALID_RESPONSE": 4,
		"HOOK_ERROR_CATEGORY_PROCESS_CRASHED":  5,
		"HOOK_ERROR_CATEGORY_UNKNOWN":          6,
	}
)

func (x HookErrorCategory) Enum() *HookErrorCategory {
	p := new(HookErrorCategory)
	*p = x
	return p
}

func (x HookErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HookErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_pluggableharness_hook_v1_errors_proto_enumTypes[0].Descriptor()
}

func (HookErrorCategory) Type() protoreflect.EnumType {
	return &file_pluggableharness_hook_v1_errors_proto_enumTypes[0]
}

func (x HookErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HookErrorCategory.Descriptor instead.
func (HookErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_pluggableharness_hook_v1_errors_proto_rawDescGZIP(), []int{0}
}

// HookError is the structured detail describing one failed hook dispatch.
// Also the payload shape the kernel-synthesized EVENT_KIND_HOOK_ERROR
// event carries (kernel.v1.EventKind, state-backend.md §The kind enum) —
// the forthcoming event.v1 package's HookErrorEvent wraps this same
// message rather than redefining it.
type HookError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which hook point the failing dispatch was for. MUST be set.
	Point v1.HookPoint `protobuf:"varint,1,opt,name=point,proto3,enum=pluggableharness.common.v1.HookPoint" json:"point,omitempty"`
	// Which plugin build the failing subscriber was. MUST be set.
	Subscriber *v1.ProducerRef `protobuf:"bytes,2,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	// The HookMode the failing subscription was declared under. MUST be
	// set.
	Mode HookMode `protobuf:"varint,3,opt,name=mode,proto3,enum=pluggableharness.hook.v1.HookMode" json:"mode,omitempty"`
	// Which category of failure this is. MUST be set.
	Category HookErrorCategory `protobuf:"varint,4,opt,name=category,proto3,enum=pluggableharness.hook.v1.HookErrorCategory" json:"category,omitempty"`
	// Human-readable detail, e.g. the raw subscriber error message.
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookError) Reset() {
	*x = HookError{}
	mi := &file_pluggableharness_hook_v1_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookError) ProtoMessage() {}

func (x *HookError) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_hook_v1_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookError.ProtoReflect.Descriptor instead.
func (*HookError) Descriptor() ([]byte, []int) {
	return file_pluggableharness_hook_v1_errors_proto_rawDescGZIP(), []int{0}
}

func (x *HookError) GetPoint() v1.HookPoint {
	if x != nil {
		return x.Point
	}
	return v1.HookPoint(0)
}

func (x *HookError) GetSubscriber() *v1.ProducerRef {
	if x != nil {
		return x.Subscriber
	}
	return nil
}

func (x *HookError) GetMode() HookMode {
	if x != nil {
		return x.Mode
	}
	return HookMode_HOOK_MODE_UNSPECIFIED
}

func (x *HookError) GetCategory() HookErrorCategory {
	if x != nil {
		return x.Category
	}
	return HookErrorCategory_HOOK_ERROR_CATEGORY_UNSPECIFIED
}

func (x *HookError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pluggableharness_hook_v1_errors_proto protoreflect.FileDescriptor

const file_pluggableharness_hook_v1_errors_proto_rawDesc = "" +
	"\n" +
	"%pluggableharness/hook/v1/errors.proto\x12\x18pluggableharness.hook.v1\x1a&pluggableharness/common/v1/types.proto\x1a$pluggableharness/hook/v1/types.proto\"\xac\x02\n" +
	"\tHookError\x12;\n" +
	"\x05point\x18\x01 \x01(\x0e2%.pluggableharness.common.v1.HookPointR\x05point\x12G\n" +
	"\n" +
	"subscriber\x18\x02 \x01(\v2'.pluggableharness.common.v1.ProducerRefR\n" +
	"subscriber\x126\n" +
	"\x04mode\x18\x03 \x01(\x0e2\".pluggableharness.hook.v1.HookModeR\x04mode\x12G\n" +
	"\bcategory\x18\x04 \x01(\x0e2+.pluggableharness.hook.v1.HookErrorCategoryR\bcategory\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage*\x9c\x02\n" +
	"\x11HookErrorCategory\x12#\n" +
	"\x1fHOOK_ERROR_CATEGORY_UNSPECIFIED\x10\x00\x12(\n" +
	"$HOOK_ERROR_CATEGORY_TRANSFORM_FAILED\x10\x01\x12#\n" +
	"\x1fHOOK_ERROR_CATEGORY_VETO_FAILED\x10\x02\x12\x1f\n" +
	"\x1bHOOK_ERROR_CATEGORY_TIMEOUT\x10\x03\x12(\n" +
	"$HOOK_ERROR_CATEGORY_INVALID_RESPONSE\x10\x04\x12'\n" +
	"#HOOK_ERROR_CATEGORY_PROCESS_CRASHED\x10\x05\x12\x1f\n" +
	"\x1bHOOK_ERROR_CATEGORY_UNKNOWN\x10\x06B<Z:github.com/pluggableharness/agent/pkg/hook/proto/v1;hookv1b\x06proto3"

var (
	file_pluggableharness_hook_v1_errors_proto_rawDescOnce sync.Once
	file_pluggableharness_hook_v1_errors_proto_rawDescData []byte
)

func file_pluggableharness_hook_v1_errors_proto_rawDescGZIP() []byte {
	file_pluggableharness_hook_v1_errors_proto_rawDescOnce.Do(func() {
		file_pluggableharness_hook_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_hook_v1_errors_proto_rawDesc), len(file_pluggableharness_hook_v1_errors_proto_rawDesc)))
	})
	return file_pluggableharness_hook_v1_errors_proto_rawDescData
}

var file_pluggableharness_hook_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pluggableharness_hook_v1_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pluggableharness_hook_v1_errors_proto_goTypes = []any{
	(HookErrorCategory)(0), // 0: pluggableharness.hook.v1.HookErrorCategory
	(*HookError)(nil),      // 1: pluggableharness.hook.v1.HookError
	(v1.HookPoint)(0),      // 2: pluggableharness.common.v1.HookPoint
	(*v1.ProducerRef)(nil), // 3: pluggableharness.common.v1.ProducerRef
	(HookMode)(0),          // 4: pluggableharness.hook.v1.HookMode
}
var file_pluggableharness_hook_v1_errors_proto_depIdxs = []int32{
	2, // 0: pluggableharness.hook.v1.HookError.point:type_name -> pluggableharness.common.v1.HookPoint
	3, // 1: pluggableharness.hook.v1.HookError.subscriber:type_name -> pluggableharness.common.v1.ProducerRef
	4, // 2: pluggableharness.hook.v1.HookError.mode:type_name -> pluggableharness.hook.v1.HookMode
	0, // 3: pluggableharness.hook.v1.HookError.category:type_name -> pluggableharness.hook.v1.HookErrorCategory
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pluggableharness_hook_v1_errors_proto_init() }
func file_pluggableharness_hook_v1_errors_proto_init() {
	if File_pluggableharness_hook_v1_errors_proto != nil {
		return
	}
	file_pluggableharness_hook_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_hook_v1_errors_proto_rawDesc), len(file_pluggableharness_hook_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_hook_v1_errors_proto_goTypes,
		DependencyIndexes: file_pluggableharness_hook_v1_errors_proto_depIdxs,
		EnumInfos:         file_pluggableharness_hook_v1_errors_proto_enumTypes,
		MessageInfos:      file_pluggableharness_hook_v1_errors_proto_msgTypes,
	}.Build()
	File_pluggableharness_hook_v1_errors_proto = out.File
	file_pluggableharness_hook_v1_errors_proto_goTypes = nil
	file_pluggableharness_hook_v1_errors_proto_depIdxs = nil
}
