// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/hook/v1/rpc_request.proto

package hookv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DispatchHookRequest is one hook-point firing delivered to one
// subscriber.
type DispatchHookRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The payload for this firing. MUST be set; the set oneof variant
	// implicitly identifies the hook point.
	Payload *HookPayload `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// The operator-configured mode this subscription runs under
	// (agent.hcl's hook{} block). MUST be set — tells the subscriber which
	// of DispatchHookResponse's three outcome shapes is expected back.
	Mode HookMode `protobuf:"varint,2,opt,name=mode,proto3,enum=pluggableharness.hook.v1.HookMode" json:"mode,omitempty"`
	// Disambiguates a plugin declaring more than one hook{} block at the
	// same HookPoint. Absent when a plugin has exactly one subscription at
	// this point.
	SubscriptionId *string `protobuf:"bytes,3,opt,name=subscription_id,json=subscriptionId,proto3,oneof" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DispatchHookRequest) Reset() {
	*x = DispatchHookRequest{}
	mi := &file_pluggableharness_hook_v1_rpc_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchHookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchHookRequest) ProtoMessage() {}

func (x *DispatchHookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pluggableharness_hook_v1_rpc_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchHookRequest.ProtoReflect.Descriptor instead.
func (*DispatchHookRequest) Descriptor() ([]byte, []int) {
	return file_pluggableharness_hook_v1_rpc_request_proto_rawDescGZIP(), []int{0}
}

func (x *DispatchHookRequest) GetPayload() *HookPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DispatchHookRequest) GetMode() HookMode {
	if x != nil {
		return x.Mode
	}
	return HookMode_HOOK_MODE_UNSPECIFIED
}

func (x *DispatchHookRequest) GetSubscriptionId() string {
	if x != nil && x.SubscriptionId != nil {
		return *x.SubscriptionId
	}
	return ""
}

var File_pluggableharness_hook_v1_rpc_request_proto protoreflect.FileDescriptor

const file_pluggableharness_hook_v1_rpc_request_proto_rawDesc = "" +
	"\n" +
	"*pluggableharness/hook/v1/rpc_request.proto\x12\x18pluggableharness.hook.v1\x1a%pluggableharness/hook/v1/events.proto\x1a$pluggableharness/hook/v1/types.proto\"\xd0\x01\n" +
	"\x13DispatchHookRequest\x12?\n" +
	"\apayload\x18\x01 \x01(\v2%.pluggableharness.hook.v1.HookPayloadR\apayload\x126\n" +
	"\x04mode\x18\x02 \x01(\x0e2\".pluggableharness.hook.v1.HookModeR\x04mode\x12,\n" +
	"\x0fsubscription_id\x18\x03 \x01(\tH\x00R\x0esubscriptionId\x88\x01\x01B\x12\n" +
	"\x10_subscription_idB<Z:github.com/pluggableharness/agent/pkg/hook/proto/v1;hookv1b\x06proto3"

var (
	file_pluggableharness_hook_v1_rpc_request_proto_rawDescOnce sync.Once
	file_pluggableharness_hook_v1_rpc_request_proto_rawDescData []byte
)

func file_pluggableharness_hook_v1_rpc_request_proto_rawDescGZIP() []byte {
	file_pluggableharness_hook_v1_rpc_request_proto_rawDescOnce.Do(func() {
		file_pluggableharness_hook_v1_rpc_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluggableharness_hook_v1_rpc_request_proto_rawDesc), len(file_pluggableharness_hook_v1_rpc_request_proto_rawDesc)))
	})
	return file_pluggableharness_hook_v1_rpc_request_proto_rawDescData
}

var file_pluggableharness_hook_v1_rpc_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pluggableharness_hook_v1_rpc_request_proto_goTypes = []any{
	(*DispatchHookRequest)(nil), // 0: pluggableharness.hook.v1.DispatchHookRequest
	(*HookPayload)(nil),         // 1: pluggableharness.hook.v1.HookPayload
	(HookMode)(0),               // 2: pluggableharness.hook.v1.HookMode
}
var file_pluggableharness_hook_v1_rpc_request_proto_depIdxs = []int32{
	1, // 0: pluggableharness.hook.v1.DispatchHookRequest.payload:type_name -> pluggableharness.hook.v1.HookPayload
	2, // 1: pluggableharness.hook.v1.DispatchHookRequest.mode:type_name -> pluggableharness.hook.v1.HookMode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pluggableharness_hook_v1_rpc_request_proto_init() }
func file_pluggableharness_hook_v1_rpc_request_proto_init() {
	if File_pluggableharness_hook_v1_rpc_request_proto != nil {
		return
	}
	file_pluggableharness_hook_v1_events_proto_init()
	file_pluggableharness_hook_v1_types_proto_init()
	file_pluggableharness_hook_v1_rpc_request_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_hook_v1_rpc_request_proto_rawDesc), len(file_pluggableharness_hook_v1_rpc_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluggableharness_hook_v1_rpc_request_proto_goTypes,
		DependencyIndexes: file_pluggableharness_hook_v1_rpc_request_proto_depIdxs,
		MessageInfos:      file_pluggableharness_hook_v1_rpc_request_proto_msgTypes,
	}.Build()
	File_pluggableharness_hook_v1_rpc_request_proto = out.File
	file_pluggableharness_hook_v1_rpc_request_proto_goTypes = nil
	file_pluggableharness_hook_v1_rpc_request_proto_depIdxs = nil
}
