// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pluggableharness/hook/v1/service.proto

// Package pluggableharness.hook.v1 defines the hook-dispatch RPC surface
// described in agent-loop/hook-dispatch.md and architecture.md §Hook
// dispatch semantics: the wire contract the kernel uses to invoke any
// plugin (of any of the six categories) that declares a `hook{}` block in
// agent.hcl. This is deliberately one shared service rather than a
// per-category RPC — hashicorp/go-plugin (.claude/rules/plugin-runtime.md)
// muxes multiple gRPC services over one broker connection, so the kernel
// dials HookSubscriberService on the same subprocess that already serves
// that plugin's own category service. A plugin with no `hook{}` blocks in
// agent.hcl simply never has it called.
//
// context-assemble is deliberately absent from this surface's hook-point
// vocabulary (common.v1.HookPoint) — it stays on ContextService.Contribute
// (context/protocol.md#contribute-the-context-assemble-rpc; architecture.md
// §Hook dispatch semantics), which already carries the full accumulated
// ContextSection chain and doesn't need a second, competing dispatch path.
// This surface serves the other eight hook points only.

package hookv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_pluggableharness_hook_v1_service_proto protoreflect.FileDescriptor

const file_pluggableharness_hook_v1_service_proto_rawDesc = "" +
	"\n" +
	"&pluggableharness/hook/v1/service.proto\x12\x18pluggableharness.hook.v1\x1a*pluggableharness/hook/v1/rpc_request.proto\x1a+pluggableharness/hook/v1/rpc_response.proto2\x86\x01\n" +
	"\x15HookSubscriberService\x12m\n" +
	"\fDispatchHook\x12-.pluggableharness.hook.v1.DispatchHookRequest\x1a..pluggableharness.hook.v1.DispatchHookResponseB<Z:github.com/pluggableharness/agent/pkg/hook/proto/v1;hookv1b\x06proto3"

var file_pluggableharness_hook_v1_service_proto_goTypes = []any{
	(*DispatchHookRequest)(nil),  // 0: pluggableharness.hook.v1.DispatchHookRequest
	(*DispatchHookResponse)(nil), // 1: pluggableharness.hook.v1.DispatchHookResponse
}
var file_pluggableharness_hook_v1_service_proto_depIdxs = []int32{
	0, // 0: pluggableharness.hook.v1.HookSubscriberService.DispatchHook:input_type -> pluggableharness.hook.v1.DispatchHookRequest
	1, // 1: pluggableharness.hook.v1.HookSubscriberService.DispatchHook:output_type -> pluggableharness.hook.v1.DispatchHookResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pluggableharness_hook_v1_service_proto_init() }
func file_pluggableharness_hook_v1_service_proto_init() {
	if File_pluggableharness_hook_v1_service_proto != nil {
		return
	}
	file_pluggableharness_hook_v1_rpc_request_proto_init()
	file_pluggableharness_hook_v1_rpc_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluggableharness_hook_v1_service_proto_rawDesc), len(file_pluggableharness_hook_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pluggableharness_hook_v1_service_proto_goTypes,
		DependencyIndexes: file_pluggableharness_hook_v1_service_proto_depIdxs,
	}.Build()
	File_pluggableharness_hook_v1_service_proto = out.File
	file_pluggableharness_hook_v1_service_proto_goTypes = nil
	file_pluggableharness_hook_v1_service_proto_depIdxs = nil
}
