// Package statebackend implements the kernel state backend specified in
// docs/specifications/state-backend.md: sqlite-per-session persistence for
// everything the kernel needs to durably reconstruct a session after the
// fact. Each session gets its own sqlite file holding an append-only event
// log (events), a single mutable summary row (session_meta), a structured
// spend ledger (cost_ledger), and a plan/apply audit trail (plan_items) —
// see docs/specifications/state-backend.md#schema for the full five-table
// shape (the fifth table, producers, is the distinct-plugin manifest
// AppendEvent/AppendMessage/AppendPlan maintain alongside events).
//
// Store (statebackend.go) manages the directory of per-session files
// (docs/specifications/state-backend.md#file-layout); Session is an open
// handle to one file, with append methods in session.go — the kernel's
// sole-writer path (AppendEvent, AppendMessage, AppendPlan, SetStatus) —
// and read methods in query.go (Meta, Events, Producers, CostLedger,
// PlanItems). Replay reconstructs a session by iterating Events in
// sequence order: sequence is the only ordering authority anywhere in
// this package (docs/specifications/state-backend.md#ordering--concurrency,
// .claude/rules/determinism.md), never wall-clock time. Corruption
// recovery (integrity.go) and schema migration (schema.go) both run
// inside Store.Open, before any other operation touches a file, per
// docs/specifications/state-backend.md#schema-migration--corruption-recovery.
//
// # Design decisions
//
// The spec leaves some choices open; this package makes them as follows,
// coordinator-approved:
//
//   - Every TEXT timestamp column is stored as RFC 3339, UTC, millisecond
//     precision (formatTimestamp/parseTimestamp, statebackend.go). This is
//     display-only, exactly as the spec requires — sequence remains the
//     sole ordering authority; no code path in this package compares
//     timestamps to order events.
//   - session_meta.depth stores the remaining_depth value carried on the
//     RunSessionRequest at spawn time
//     (docs/specifications/agent-loop/subagents.md#depth-limits), not a
//     freshly re-derived value — a cache that avoids a parent-chain walk
//     when scanning.
//   - cost_ledger and plan_items declare their event_sequence foreign key
//     with no ON DELETE clause: events is append-only and its rows are
//     never deleted, so no delete-cascade behavior is needed or defined.
//   - Event.ID is caller-supplied, not generated by this package;
//     uniqueness within a session's file is enforced here (a UNIQUE
//     constraint on events.id, surfaced to callers as
//     ErrDuplicateEventID).
//   - Session.Close runs PRAGMA wal_checkpoint(TRUNCATE), folding the WAL
//     back into the main file rather than leaving a -wal sidecar behind.
//   - The Store directory is created mode 0700, and each session file is
//     created mode 0600 — session state is treated as sensitive by
//     default, readable only by the user running the kernel. Enforced on
//     Unix-like systems only; Windows ACLs are out of scope.
//   - cost_ledger.cost_usd stores exactly the cost_usd value the caller
//     computed (the model provider protocol's own cost computation,
//     docs/specifications/model/protocol.md#cost-computation); this
//     package never recomputes a cost or token figure itself
//     (.claude/rules/determinism.md).
//   - events.producer_category and producers.category store the lowercase
//     plugin-category vocabulary: model, tool, context, memory,
//     frontend, widget — the same names docs/specifications/ uses as its
//     own per-category directory names.
//   - Store.List and Store.Children read each file's session_meta row
//     directly (scan, statebackend.go), bypassing Open's schema-version
//     check and migration path — a metadata scan MUST NOT have the side
//     effect of migrating every file it merely lists.
package statebackend
